"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's7-巨龙之境',
 '版本信息': '12.11',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '12.11-2022.S7',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.11-2022.S7/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.11-2022.S7/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.11-2022.S7/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.11-2022.S7/equip.js',
 'url_hex_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.11-2022.S7/hex.js'}

    all_chess_name_str = ('奥拉夫-弗拉基米尔-瑞兹-索拉卡-崔丝塔娜-努努-艾希-图奇-艾尼维亚-娑娜-库奇-卡尔玛-塔里克-斯维因-伊莉丝-李青-斯卡纳-黑默丁格-奈德丽-伊泽瑞尔-蕾欧娜-泰隆-慎-希瓦娜-沃利贝尔-韦鲁斯-瑟庄妮-璐璐-赫卡里姆-黛安娜-奥瑞利安 '
 '· '
 '索尔-凯隐-佐伊-纳尔-亚索-布隆-金克丝-塔姆-赛娜-奇亚娜-亚托克斯-娜美-锤石-俄洛伊-巴德-霞-奥恩-塞拉斯-妮蔻-派克-永恩-瑟提-莉莉娅-迭嘉-石傲玉-艾达丝-赛芬-敖兴-玉猫雕像-诺姆希')

    all_race_name_str = '星界龙-冒险家-玉龙-幻镜龙-怒翼龙-神龙烈焰-屠龙勇士-金鳞龙-风暴龙-驯龙大师-幽影龙'

    all_job_name_str = '刺客-吟游诗人-格斗家-强袭炮手-重骑兵-神龙尊者-魔导师-护卫-传奇半神-法师-秘术师-换形师-迅捷射手-狂刃战士-龙神-窃法巧手-唤星者-召唤物'

    race_chess = {'星界龙': ['弗拉基米尔', '斯卡纳', '奈德丽', '韦鲁斯', '奥瑞利安 · 索尔', '娜美', '俄洛伊'],
 '冒险家': ['瑞兹', '图奇', '泰隆', '瑟庄妮', '巴德'],
 '玉龙': ['索拉卡', '艾希', '艾尼维亚', '卡尔玛', '塔里克', '纳尔', '妮蔻', '石傲玉', '玉猫雕像'],
 '幻镜龙': ['努努', '蕾欧娜', '亚索', '永恩', '迭嘉'],
 '怒翼龙': ['斯维因', '慎', '希瓦娜', '赫卡里姆', '凯隐', '赛娜', '霞', '瑟提'],
 '神龙烈焰': ['娑娜', '库奇', '金克丝', '塔姆'],
 '屠龙勇士': ['奥拉夫', '黛安娜', '布隆', '莉莉娅'],
 '金鳞龙': ['沃利贝尔', '凯隐', '佐伊', '亚托克斯', '艾达丝'],
 '风暴龙': ['李青', '伊泽瑞尔', '奇亚娜', '奥恩', '敖兴'],
 '驯龙大师': ['崔丝塔娜', '黑默丁格', '璐璐', '诺姆希'],
 '幽影龙': ['伊莉丝', '锤石', '塞拉斯', '派克', '赛芬']}

    job_chess = {'刺客': ['泰隆', '黛安娜', '凯隐', '奇亚娜', '派克'],
 '吟游诗人': ['巴德'],
 '格斗家': ['奥拉夫', '斯卡纳', '慎', '塔姆', '俄洛伊', '奥恩', '塞拉斯', '赛芬'],
 '强袭炮手': ['崔丝塔娜', '库奇', '金克丝', '赛娜'],
 '重骑兵': ['努努', '瑟庄妮', '赫卡里姆', '莉莉娅'],
 '神龙尊者': ['艾希', '卡尔玛', '斯维因', '李青', '沃利贝尔', '亚索', '瑟提'],
 '魔导师': ['艾尼维亚', '娑娜', '璐璐', '奥瑞利安 · 索尔'],
 '护卫': ['塔里克', '蕾欧娜', '布隆', '锤石', '艾达丝'],
 '传奇半神': ['艾尼维亚', '沃利贝尔', '奥恩'],
 '法师': ['弗拉基米尔', '瑞兹', '黑默丁格', '佐伊', '娜美', '塞拉斯', '莉莉娅'],
 '秘术师': ['璐璐', '娜美', '巴德', '石傲玉'],
 '换形师': ['斯维因', '伊莉丝', '奈德丽', '希瓦娜', '纳尔', '妮蔻', '诺姆希'],
 '迅捷射手': ['艾希', '图奇', '伊泽瑞尔', '韦鲁斯', '霞'],
 '狂刃战士': ['奥拉夫', '慎', '亚索', '亚托克斯', '永恩'],
 '龙神': ['希瓦娜', '奥瑞利安 · 索尔', '迭嘉', '石傲玉', '艾达丝', '赛芬', '敖兴'],
 '窃法巧手': ['佐伊'],
 '唤星者': ['索拉卡'],
 '召唤物': ['玉猫雕像']}

    price_chess = {'0': ['玉猫雕像', '诺姆希'],
 '1': ['弗拉基米尔', '卡尔玛', '塔里克', '斯卡纳', '黑默丁格', '奈德丽', '伊泽瑞尔', '蕾欧娜', '瑟庄妮', '塔姆', '赛娜', '亚托克斯', '瑟提'],
 '10': ['希瓦娜', '奥瑞利安 · 索尔', '敖兴'],
 '2': ['崔丝塔娜', '艾希', '图奇', '慎', '凯隐', '纳尔', '布隆', '金克丝', '奇亚娜', '娜美', '锤石', '永恩', '莉莉娅'],
 '3': ['奥拉夫', '瑞兹', '努努', '艾尼维亚', '斯维因', '伊莉丝', '李青', '沃利贝尔', '韦鲁斯', '璐璐', '黛安娜', '俄洛伊', '塞拉斯'],
 '4': ['娑娜', '库奇', '泰隆', '赫卡里姆', '霞', '奥恩', '妮蔻'],
 '5': ['索拉卡', '佐伊', '亚索', '巴德', '派克'],
 '8': ['迭嘉', '石傲玉', '艾达丝', '赛芬']}

    chess_name_info = {'奥拉夫': {'name': '奥拉夫',
         'jobs': ['格斗家', '狂刃战士'],
         'races': ['屠龙勇士'],
         'price': '3',
         'gui_name': '3-奥拉夫',
         'gui_checkbox_key': 'checkbox_奥拉夫',
         'gui_combo_num_key': 'combo_num_奥拉夫'},
 '弗拉基米尔': {'name': '弗拉基米尔',
           'jobs': ['法师'],
           'races': ['星界龙'],
           'price': '1',
           'gui_name': '1-弗拉基米尔',
           'gui_checkbox_key': 'checkbox_弗拉基米尔',
           'gui_combo_num_key': 'combo_num_弗拉基米尔'},
 '瑞兹': {'name': '瑞兹',
        'jobs': ['法师'],
        'races': ['冒险家'],
        'price': '3',
        'gui_name': '3-瑞兹',
        'gui_checkbox_key': 'checkbox_瑞兹',
        'gui_combo_num_key': 'combo_num_瑞兹'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['唤星者'],
         'races': ['玉龙'],
         'price': '5',
         'gui_name': '5-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '崔丝塔娜': {'name': '崔丝塔娜',
          'jobs': ['强袭炮手'],
          'races': ['驯龙大师'],
          'price': '2',
          'gui_name': '2-崔丝塔娜',
          'gui_checkbox_key': 'checkbox_崔丝塔娜',
          'gui_combo_num_key': 'combo_num_崔丝塔娜'},
 '努努': {'name': '努努',
        'jobs': ['重骑兵'],
        'races': ['幻镜龙'],
        'price': '3',
        'gui_name': '3-努努',
        'gui_checkbox_key': 'checkbox_努努',
        'gui_combo_num_key': 'combo_num_努努'},
 '艾希': {'name': '艾希',
        'jobs': ['神龙尊者', '迅捷射手'],
        'races': ['玉龙'],
        'price': '2',
        'gui_name': '2-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '图奇': {'name': '图奇',
        'jobs': ['迅捷射手'],
        'races': ['冒险家'],
        'price': '2',
        'gui_name': '2-图奇',
        'gui_checkbox_key': 'checkbox_图奇',
        'gui_combo_num_key': 'combo_num_图奇'},
 '艾尼维亚': {'name': '艾尼维亚',
          'jobs': ['魔导师', '传奇半神'],
          'races': ['玉龙'],
          'price': '3',
          'gui_name': '3-艾尼维亚',
          'gui_checkbox_key': 'checkbox_艾尼维亚',
          'gui_combo_num_key': 'combo_num_艾尼维亚'},
 '娑娜': {'name': '娑娜',
        'jobs': ['魔导师'],
        'races': ['神龙烈焰'],
        'price': '4',
        'gui_name': '4-娑娜',
        'gui_checkbox_key': 'checkbox_娑娜',
        'gui_combo_num_key': 'combo_num_娑娜'},
 '库奇': {'name': '库奇',
        'jobs': ['强袭炮手'],
        'races': ['神龙烈焰'],
        'price': '4',
        'gui_name': '4-库奇',
        'gui_checkbox_key': 'checkbox_库奇',
        'gui_combo_num_key': 'combo_num_库奇'},
 '卡尔玛': {'name': '卡尔玛',
         'jobs': ['神龙尊者'],
         'races': ['玉龙'],
         'price': '1',
         'gui_name': '1-卡尔玛',
         'gui_checkbox_key': 'checkbox_卡尔玛',
         'gui_combo_num_key': 'combo_num_卡尔玛'},
 '塔里克': {'name': '塔里克',
         'jobs': ['护卫'],
         'races': ['玉龙'],
         'price': '1',
         'gui_name': '1-塔里克',
         'gui_checkbox_key': 'checkbox_塔里克',
         'gui_combo_num_key': 'combo_num_塔里克'},
 '斯维因': {'name': '斯维因',
         'jobs': ['神龙尊者', '换形师'],
         'races': ['怒翼龙'],
         'price': '3',
         'gui_name': '3-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '伊莉丝': {'name': '伊莉丝',
         'jobs': ['换形师'],
         'races': ['幽影龙'],
         'price': '3',
         'gui_name': '3-伊莉丝',
         'gui_checkbox_key': 'checkbox_伊莉丝',
         'gui_combo_num_key': 'combo_num_伊莉丝'},
 '李青': {'name': '李青',
        'jobs': ['神龙尊者'],
        'races': ['风暴龙'],
        'price': '3',
        'gui_name': '3-李青',
        'gui_checkbox_key': 'checkbox_李青',
        'gui_combo_num_key': 'combo_num_李青'},
 '斯卡纳': {'name': '斯卡纳',
         'jobs': ['格斗家'],
         'races': ['星界龙'],
         'price': '1',
         'gui_name': '1-斯卡纳',
         'gui_checkbox_key': 'checkbox_斯卡纳',
         'gui_combo_num_key': 'combo_num_斯卡纳'},
 '黑默丁格': {'name': '黑默丁格',
          'jobs': ['法师'],
          'races': ['驯龙大师'],
          'price': '1',
          'gui_name': '1-黑默丁格',
          'gui_checkbox_key': 'checkbox_黑默丁格',
          'gui_combo_num_key': 'combo_num_黑默丁格'},
 '奈德丽': {'name': '奈德丽',
         'jobs': ['换形师'],
         'races': ['星界龙'],
         'price': '1',
         'gui_name': '1-奈德丽',
         'gui_checkbox_key': 'checkbox_奈德丽',
         'gui_combo_num_key': 'combo_num_奈德丽'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['迅捷射手'],
          'races': ['风暴龙'],
          'price': '1',
          'gui_name': '1-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '蕾欧娜': {'name': '蕾欧娜',
         'jobs': ['护卫'],
         'races': ['幻镜龙'],
         'price': '1',
         'gui_name': '1-蕾欧娜',
         'gui_checkbox_key': 'checkbox_蕾欧娜',
         'gui_combo_num_key': 'combo_num_蕾欧娜'},
 '泰隆': {'name': '泰隆',
        'jobs': ['刺客'],
        'races': ['冒险家'],
        'price': '4',
        'gui_name': '4-泰隆',
        'gui_checkbox_key': 'checkbox_泰隆',
        'gui_combo_num_key': 'combo_num_泰隆'},
 '慎': {'name': '慎',
       'jobs': ['格斗家', '狂刃战士'],
       'races': ['怒翼龙'],
       'price': '2',
       'gui_name': '2-慎',
       'gui_checkbox_key': 'checkbox_慎',
       'gui_combo_num_key': 'combo_num_慎'},
 '希瓦娜': {'name': '希瓦娜',
         'jobs': ['换形师', '龙神'],
         'races': ['怒翼龙'],
         'price': '10',
         'gui_name': '10-希瓦娜',
         'gui_checkbox_key': 'checkbox_希瓦娜',
         'gui_combo_num_key': 'combo_num_希瓦娜'},
 '沃利贝尔': {'name': '沃利贝尔',
          'jobs': ['神龙尊者', '传奇半神'],
          'races': ['金鳞龙'],
          'price': '3',
          'gui_name': '3-沃利贝尔',
          'gui_checkbox_key': 'checkbox_沃利贝尔',
          'gui_combo_num_key': 'combo_num_沃利贝尔'},
 '韦鲁斯': {'name': '韦鲁斯',
         'jobs': ['迅捷射手'],
         'races': ['星界龙'],
         'price': '3',
         'gui_name': '3-韦鲁斯',
         'gui_checkbox_key': 'checkbox_韦鲁斯',
         'gui_combo_num_key': 'combo_num_韦鲁斯'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['重骑兵'],
         'races': ['冒险家'],
         'price': '1',
         'gui_name': '1-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '璐璐': {'name': '璐璐',
        'jobs': ['魔导师', '秘术师'],
        'races': ['驯龙大师'],
        'price': '3',
        'gui_name': '3-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '赫卡里姆': {'name': '赫卡里姆',
          'jobs': ['重骑兵'],
          'races': ['怒翼龙'],
          'price': '4',
          'gui_name': '4-赫卡里姆',
          'gui_checkbox_key': 'checkbox_赫卡里姆',
          'gui_combo_num_key': 'combo_num_赫卡里姆'},
 '黛安娜': {'name': '黛安娜',
         'jobs': ['刺客'],
         'races': ['屠龙勇士'],
         'price': '3',
         'gui_name': '3-黛安娜',
         'gui_checkbox_key': 'checkbox_黛安娜',
         'gui_combo_num_key': 'combo_num_黛安娜'},
 '奥瑞利安 · 索尔': {'name': '奥瑞利安 · 索尔',
               'jobs': ['魔导师', '龙神'],
               'races': ['星界龙'],
               'price': '10',
               'gui_name': '10-奥瑞利安 · 索尔',
               'gui_checkbox_key': 'checkbox_奥瑞利安 · 索尔',
               'gui_combo_num_key': 'combo_num_奥瑞利安 · 索尔'},
 '凯隐': {'name': '凯隐',
        'jobs': ['刺客'],
        'races': ['怒翼龙', '金鳞龙'],
        'price': '2',
        'gui_name': '2-凯隐',
        'gui_checkbox_key': 'checkbox_凯隐',
        'gui_combo_num_key': 'combo_num_凯隐'},
 '佐伊': {'name': '佐伊',
        'jobs': ['法师', '窃法巧手'],
        'races': ['金鳞龙'],
        'price': '5',
        'gui_name': '5-佐伊',
        'gui_checkbox_key': 'checkbox_佐伊',
        'gui_combo_num_key': 'combo_num_佐伊'},
 '纳尔': {'name': '纳尔',
        'jobs': ['换形师'],
        'races': ['玉龙'],
        'price': '2',
        'gui_name': '2-纳尔',
        'gui_checkbox_key': 'checkbox_纳尔',
        'gui_combo_num_key': 'combo_num_纳尔'},
 '亚索': {'name': '亚索',
        'jobs': ['神龙尊者', '狂刃战士'],
        'races': ['幻镜龙'],
        'price': '5',
        'gui_name': '5-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '布隆': {'name': '布隆',
        'jobs': ['护卫'],
        'races': ['屠龙勇士'],
        'price': '2',
        'gui_name': '2-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '金克丝': {'name': '金克丝',
         'jobs': ['强袭炮手'],
         'races': ['神龙烈焰'],
         'price': '2',
         'gui_name': '2-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '塔姆': {'name': '塔姆',
        'jobs': ['格斗家'],
        'races': ['神龙烈焰'],
        'price': '1',
        'gui_name': '1-塔姆',
        'gui_checkbox_key': 'checkbox_塔姆',
        'gui_combo_num_key': 'combo_num_塔姆'},
 '赛娜': {'name': '赛娜',
        'jobs': ['强袭炮手'],
        'races': ['怒翼龙'],
        'price': '1',
        'gui_name': '1-赛娜',
        'gui_checkbox_key': 'checkbox_赛娜',
        'gui_combo_num_key': 'combo_num_赛娜'},
 '奇亚娜': {'name': '奇亚娜',
         'jobs': ['刺客'],
         'races': ['风暴龙'],
         'price': '2',
         'gui_name': '2-奇亚娜',
         'gui_checkbox_key': 'checkbox_奇亚娜',
         'gui_combo_num_key': 'combo_num_奇亚娜'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['狂刃战士'],
          'races': ['金鳞龙'],
          'price': '1',
          'gui_name': '1-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '娜美': {'name': '娜美',
        'jobs': ['法师', '秘术师'],
        'races': ['星界龙'],
        'price': '2',
        'gui_name': '2-娜美',
        'gui_checkbox_key': 'checkbox_娜美',
        'gui_combo_num_key': 'combo_num_娜美'},
 '锤石': {'name': '锤石',
        'jobs': ['护卫'],
        'races': ['幽影龙'],
        'price': '2',
        'gui_name': '2-锤石',
        'gui_checkbox_key': 'checkbox_锤石',
        'gui_combo_num_key': 'combo_num_锤石'},
 '俄洛伊': {'name': '俄洛伊',
         'jobs': ['格斗家'],
         'races': ['星界龙'],
         'price': '3',
         'gui_name': '3-俄洛伊',
         'gui_checkbox_key': 'checkbox_俄洛伊',
         'gui_combo_num_key': 'combo_num_俄洛伊'},
 '巴德': {'name': '巴德',
        'jobs': ['吟游诗人', '秘术师'],
        'races': ['冒险家'],
        'price': '5',
        'gui_name': '5-巴德',
        'gui_checkbox_key': 'checkbox_巴德',
        'gui_combo_num_key': 'combo_num_巴德'},
 '霞': {'name': '霞',
       'jobs': ['迅捷射手'],
       'races': ['怒翼龙'],
       'price': '4',
       'gui_name': '4-霞',
       'gui_checkbox_key': 'checkbox_霞',
       'gui_combo_num_key': 'combo_num_霞'},
 '奥恩': {'name': '奥恩',
        'jobs': ['格斗家', '传奇半神'],
        'races': ['风暴龙'],
        'price': '4',
        'gui_name': '4-奥恩',
        'gui_checkbox_key': 'checkbox_奥恩',
        'gui_combo_num_key': 'combo_num_奥恩'},
 '塞拉斯': {'name': '塞拉斯',
         'jobs': ['格斗家', '法师'],
         'races': ['幽影龙'],
         'price': '3',
         'gui_name': '3-塞拉斯',
         'gui_checkbox_key': 'checkbox_塞拉斯',
         'gui_combo_num_key': 'combo_num_塞拉斯'},
 '妮蔻': {'name': '妮蔻',
        'jobs': ['换形师'],
        'races': ['玉龙'],
        'price': '4',
        'gui_name': '4-妮蔻',
        'gui_checkbox_key': 'checkbox_妮蔻',
        'gui_combo_num_key': 'combo_num_妮蔻'},
 '派克': {'name': '派克',
        'jobs': ['刺客'],
        'races': ['幽影龙'],
        'price': '5',
        'gui_name': '5-派克',
        'gui_checkbox_key': 'checkbox_派克',
        'gui_combo_num_key': 'combo_num_派克'},
 '永恩': {'name': '永恩',
        'jobs': ['狂刃战士'],
        'races': ['幻镜龙'],
        'price': '2',
        'gui_name': '2-永恩',
        'gui_checkbox_key': 'checkbox_永恩',
        'gui_combo_num_key': 'combo_num_永恩'},
 '瑟提': {'name': '瑟提',
        'jobs': ['神龙尊者'],
        'races': ['怒翼龙'],
        'price': '1',
        'gui_name': '1-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'},
 '莉莉娅': {'name': '莉莉娅',
         'jobs': ['重骑兵', '法师'],
         'races': ['屠龙勇士'],
         'price': '2',
         'gui_name': '2-莉莉娅',
         'gui_checkbox_key': 'checkbox_莉莉娅',
         'gui_combo_num_key': 'combo_num_莉莉娅'},
 '迭嘉': {'name': '迭嘉',
        'jobs': ['龙神'],
        'races': ['幻镜龙'],
        'price': '8',
        'gui_name': '8-迭嘉',
        'gui_checkbox_key': 'checkbox_迭嘉',
        'gui_combo_num_key': 'combo_num_迭嘉'},
 '石傲玉': {'name': '石傲玉',
         'jobs': ['秘术师', '龙神'],
         'races': ['玉龙'],
         'price': '8',
         'gui_name': '8-石傲玉',
         'gui_checkbox_key': 'checkbox_石傲玉',
         'gui_combo_num_key': 'combo_num_石傲玉'},
 '艾达丝': {'name': '艾达丝',
         'jobs': ['护卫', '龙神'],
         'races': ['金鳞龙'],
         'price': '8',
         'gui_name': '8-艾达丝',
         'gui_checkbox_key': 'checkbox_艾达丝',
         'gui_combo_num_key': 'combo_num_艾达丝'},
 '赛芬': {'name': '赛芬',
        'jobs': ['格斗家', '龙神'],
        'races': ['幽影龙'],
        'price': '8',
        'gui_name': '8-赛芬',
        'gui_checkbox_key': 'checkbox_赛芬',
        'gui_combo_num_key': 'combo_num_赛芬'},
 '敖兴': {'name': '敖兴',
        'jobs': ['龙神'],
        'races': ['风暴龙'],
        'price': '10',
        'gui_name': '10-敖兴',
        'gui_checkbox_key': 'checkbox_敖兴',
        'gui_combo_num_key': 'combo_num_敖兴'},
 '玉猫雕像': {'name': '玉猫雕像',
          'jobs': ['召唤物'],
          'races': ['玉龙'],
          'price': '0',
          'gui_name': '0-玉猫雕像',
          'gui_checkbox_key': 'checkbox_玉猫雕像',
          'gui_combo_num_key': 'combo_num_玉猫雕像'},
 '诺姆希': {'name': '诺姆希',
         'jobs': ['换形师'],
         'races': ['驯龙大师'],
         'price': '0',
         'gui_name': '0-诺姆希',
         'gui_checkbox_key': 'checkbox_诺姆希',
         'gui_combo_num_key': 'combo_num_诺姆希'}}
