"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's6.5-霓虹之夜',
 '版本信息': '12.4',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '12.4-2022.S6',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.4-2022.S6/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.4-2022.S6/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.4-2022.S6/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.4-2022.S6/equip.js',
 'url_hex_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.4-2022.S6/hex.js'}

    all_chess_name_str = '加里奥-阿利斯塔-希维尔-沃里克-厄运小姐-艾希-泰达米尔-莫甘娜-基兰-辛吉德-图奇-科加斯-卡萨丁-艾瑞莉娅-普朗克-库奇-维迦-斯维因-凯特琳-布里茨-魔腾-嘉文四世-奥莉安娜-布兰德-波比-伊泽瑞尔-蕾欧娜-玛尔扎哈-泰隆-阿狸-维克托-瑟庄妮-吉格斯-璐璐-德莱文-卡兹克-德莱厄斯-杰斯-奎因-辛德拉-婕拉-卡莎-萨勒芬妮-纳尔-扎克-卡蜜尔-布隆-烬-泽丽-金克丝-塔姆-赛娜-卢锡安-艾克-蔚-俄洛伊-雷克塞-薇古丝-烈娜塔-希尔科'

    all_race_name_str = '炼金科技-精密发条-执法官-变异战士-赏金猎人-极客-社交名流-辛迪加-约德尔人-食神-约德尔大王-海克斯科技-执事-宿敌-微光首脑'

    all_job_name_str = '黑魔法师-刺客-格斗家-保镖-巨像-挑战者-白魔法师-发明家-学者-狙神-枪手-未来守护者-强袭战士'

    race_chess = {'炼金科技': ['沃里克', '泰达米尔', '辛吉德', '图奇', '维克托', '扎克', '烈娜塔'],
 '精密发条': ['基兰', '奥莉安娜', '卡蜜尔', '烬'],
 '执法官': ['凯特琳', '瑟庄妮', '杰斯', '蔚'],
 '变异战士': ['科加斯', '卡萨丁', '玛尔扎哈', '卡兹克', '卡莎', '雷克塞'],
 '赏金猎人': ['厄运小姐', '普朗克', '奎因', '塔姆', '俄洛伊'],
 '极客': ['艾瑞莉娅', '布里茨', '伊泽瑞尔', '吉格斯', '金克丝', '艾克'],
 '社交名流': ['加里奥', '萨勒芬妮', '纳尔', '赛娜'],
 '辛迪加': ['艾希', '莫甘娜', '阿狸', '德莱厄斯', '婕拉', '布隆'],
 '约德尔人': ['库奇', '波比', '吉格斯', '璐璐', '纳尔', '薇古丝'],
 '食神': ['塔姆'],
 '约德尔大王': ['维迦'],
 '海克斯科技': ['阿利斯塔', '希维尔', '斯维因', '魔腾', '嘉文四世', '瑟庄妮', '卢锡安'],
 '执事': ['布兰德', '蕾欧娜', '泰隆', '德莱文', '辛德拉', '泽丽'],
 '宿敌': ['金克丝', '蔚'],
 '微光首脑': ['希尔科']}

    job_chess = {'黑魔法师': ['斯维因', '布兰德', '玛尔扎哈', '阿狸', '维克托', '吉格斯', '薇古丝'],
 '刺客': ['图奇', '魔腾', '泰隆', '卡兹克', '艾克'],
 '格斗家': ['科加斯', '瑟庄妮', '扎克', '塔姆', '蔚', '俄洛伊', '雷克塞'],
 '保镖': ['加里奥', '布里茨', '波比', '蕾欧娜', '德莱厄斯', '布隆'],
 '巨像': ['加里奥', '阿利斯塔', '科加斯'],
 '挑战者': ['沃里克', '泰达米尔', '德莱文', '奎因', '卡莎', '卡蜜尔'],
 '白魔法师': ['莫甘娜', '奥莉安娜', '璐璐', '赛娜'],
 '发明家': ['基兰', '辛吉德', '伊泽瑞尔', '杰斯', '萨勒芬妮', '艾克'],
 '学者': ['卡萨丁', '辛德拉', '婕拉', '烈娜塔', '希尔科'],
 '狙神': ['厄运小姐', '艾希', '凯特琳', '烬', '泽丽'],
 '枪手': ['普朗克', '库奇', '金克丝', '卢锡安'],
 '未来守护者': ['杰斯'],
 '强袭战士': ['希维尔', '艾瑞莉娅', '嘉文四世', '纳尔', '雷克塞']}

    price_chess = {'1': ['辛吉德', '图奇', '卡萨丁', '凯特琳', '魔腾', '嘉文四世', '布兰德', '波比', '伊泽瑞尔', '吉格斯', '德莱厄斯', '卡蜜尔', '俄洛伊'],
 '2': ['沃里克', '艾希', '基兰', '库奇', '斯维因', '布里茨', '泰隆', '瑟庄妮', '璐璐', '奎因', '辛德拉', '婕拉', '雷克塞'],
 '3': ['厄运小姐', '泰达米尔', '莫甘娜', '科加斯', '普朗克', '蕾欧娜', '玛尔扎哈', '纳尔', '扎克', '赛娜', '卢锡安', '艾克', '薇古丝'],
 '4': ['阿利斯塔', '希维尔', '艾瑞莉娅', '奥莉安娜', '阿狸', '德莱文', '卡兹克', '萨勒芬妮', '布隆', '烬', '蔚', '烈娜塔'],
 '5': ['加里奥', '维迦', '维克托', '杰斯', '卡莎', '泽丽', '金克丝', '塔姆', '希尔科']}

    chess_name_info = {'加里奥': {'name': '加里奥',
         'jobs': ['保镖', '巨像'],
         'races': ['社交名流'],
         'price': '5',
         'gui_name': '5-加里奥',
         'gui_checkbox_key': 'checkbox_加里奥',
         'gui_combo_num_key': 'combo_num_加里奥'},
 '阿利斯塔': {'name': '阿利斯塔',
          'jobs': ['巨像'],
          'races': ['海克斯科技'],
          'price': '4',
          'gui_name': '4-阿利斯塔',
          'gui_checkbox_key': 'checkbox_阿利斯塔',
          'gui_combo_num_key': 'combo_num_阿利斯塔'},
 '希维尔': {'name': '希维尔',
         'jobs': ['强袭战士'],
         'races': ['海克斯科技'],
         'price': '4',
         'gui_name': '4-希维尔',
         'gui_checkbox_key': 'checkbox_希维尔',
         'gui_combo_num_key': 'combo_num_希维尔'},
 '沃里克': {'name': '沃里克',
         'jobs': ['挑战者'],
         'races': ['炼金科技'],
         'price': '2',
         'gui_name': '2-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '厄运小姐': {'name': '厄运小姐',
          'jobs': ['狙神'],
          'races': ['赏金猎人'],
          'price': '3',
          'gui_name': '3-厄运小姐',
          'gui_checkbox_key': 'checkbox_厄运小姐',
          'gui_combo_num_key': 'combo_num_厄运小姐'},
 '艾希': {'name': '艾希',
        'jobs': ['狙神'],
        'races': ['辛迪加'],
        'price': '2',
        'gui_name': '2-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '泰达米尔': {'name': '泰达米尔',
          'jobs': ['挑战者'],
          'races': ['炼金科技'],
          'price': '3',
          'gui_name': '3-泰达米尔',
          'gui_checkbox_key': 'checkbox_泰达米尔',
          'gui_combo_num_key': 'combo_num_泰达米尔'},
 '莫甘娜': {'name': '莫甘娜',
         'jobs': ['白魔法师'],
         'races': ['辛迪加'],
         'price': '3',
         'gui_name': '3-莫甘娜',
         'gui_checkbox_key': 'checkbox_莫甘娜',
         'gui_combo_num_key': 'combo_num_莫甘娜'},
 '基兰': {'name': '基兰',
        'jobs': ['发明家'],
        'races': ['精密发条'],
        'price': '2',
        'gui_name': '2-基兰',
        'gui_checkbox_key': 'checkbox_基兰',
        'gui_combo_num_key': 'combo_num_基兰'},
 '辛吉德': {'name': '辛吉德',
         'jobs': ['发明家'],
         'races': ['炼金科技'],
         'price': '1',
         'gui_name': '1-辛吉德',
         'gui_checkbox_key': 'checkbox_辛吉德',
         'gui_combo_num_key': 'combo_num_辛吉德'},
 '图奇': {'name': '图奇',
        'jobs': ['刺客'],
        'races': ['炼金科技'],
        'price': '1',
        'gui_name': '1-图奇',
        'gui_checkbox_key': 'checkbox_图奇',
        'gui_combo_num_key': 'combo_num_图奇'},
 '科加斯': {'name': '科加斯',
         'jobs': ['格斗家', '巨像'],
         'races': ['变异战士'],
         'price': '3',
         'gui_name': '3-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '卡萨丁': {'name': '卡萨丁',
         'jobs': ['学者'],
         'races': ['变异战士'],
         'price': '1',
         'gui_name': '1-卡萨丁',
         'gui_checkbox_key': 'checkbox_卡萨丁',
         'gui_combo_num_key': 'combo_num_卡萨丁'},
 '艾瑞莉娅': {'name': '艾瑞莉娅',
          'jobs': ['强袭战士'],
          'races': ['极客'],
          'price': '4',
          'gui_name': '4-艾瑞莉娅',
          'gui_checkbox_key': 'checkbox_艾瑞莉娅',
          'gui_combo_num_key': 'combo_num_艾瑞莉娅'},
 '普朗克': {'name': '普朗克',
         'jobs': ['枪手'],
         'races': ['赏金猎人'],
         'price': '3',
         'gui_name': '3-普朗克',
         'gui_checkbox_key': 'checkbox_普朗克',
         'gui_combo_num_key': 'combo_num_普朗克'},
 '库奇': {'name': '库奇',
        'jobs': ['枪手'],
        'races': ['约德尔人'],
        'price': '2',
        'gui_name': '2-库奇',
        'gui_checkbox_key': 'checkbox_库奇',
        'gui_combo_num_key': 'combo_num_库奇'},
 '维迦': {'name': '维迦',
        'jobs': [],
        'races': ['约德尔大王'],
        'price': '5',
        'gui_name': '5-维迦',
        'gui_checkbox_key': 'checkbox_维迦',
        'gui_combo_num_key': 'combo_num_维迦'},
 '斯维因': {'name': '斯维因',
         'jobs': ['黑魔法师'],
         'races': ['海克斯科技'],
         'price': '2',
         'gui_name': '2-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '凯特琳': {'name': '凯特琳',
         'jobs': ['狙神'],
         'races': ['执法官'],
         'price': '1',
         'gui_name': '1-凯特琳',
         'gui_checkbox_key': 'checkbox_凯特琳',
         'gui_combo_num_key': 'combo_num_凯特琳'},
 '布里茨': {'name': '布里茨',
         'jobs': ['保镖'],
         'races': ['极客'],
         'price': '2',
         'gui_name': '2-布里茨',
         'gui_checkbox_key': 'checkbox_布里茨',
         'gui_combo_num_key': 'combo_num_布里茨'},
 '魔腾': {'name': '魔腾',
        'jobs': ['刺客'],
        'races': ['海克斯科技'],
        'price': '1',
        'gui_name': '1-魔腾',
        'gui_checkbox_key': 'checkbox_魔腾',
        'gui_combo_num_key': 'combo_num_魔腾'},
 '嘉文四世': {'name': '嘉文四世',
          'jobs': ['强袭战士'],
          'races': ['海克斯科技'],
          'price': '1',
          'gui_name': '1-嘉文四世',
          'gui_checkbox_key': 'checkbox_嘉文四世',
          'gui_combo_num_key': 'combo_num_嘉文四世'},
 '奥莉安娜': {'name': '奥莉安娜',
          'jobs': ['白魔法师'],
          'races': ['精密发条'],
          'price': '4',
          'gui_name': '4-奥莉安娜',
          'gui_checkbox_key': 'checkbox_奥莉安娜',
          'gui_combo_num_key': 'combo_num_奥莉安娜'},
 '布兰德': {'name': '布兰德',
         'jobs': ['黑魔法师'],
         'races': ['执事'],
         'price': '1',
         'gui_name': '1-布兰德',
         'gui_checkbox_key': 'checkbox_布兰德',
         'gui_combo_num_key': 'combo_num_布兰德'},
 '波比': {'name': '波比',
        'jobs': ['保镖'],
        'races': ['约德尔人'],
        'price': '1',
        'gui_name': '1-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['发明家'],
          'races': ['极客'],
          'price': '1',
          'gui_name': '1-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '蕾欧娜': {'name': '蕾欧娜',
         'jobs': ['保镖'],
         'races': ['执事'],
         'price': '3',
         'gui_name': '3-蕾欧娜',
         'gui_checkbox_key': 'checkbox_蕾欧娜',
         'gui_combo_num_key': 'combo_num_蕾欧娜'},
 '玛尔扎哈': {'name': '玛尔扎哈',
          'jobs': ['黑魔法师'],
          'races': ['变异战士'],
          'price': '3',
          'gui_name': '3-玛尔扎哈',
          'gui_checkbox_key': 'checkbox_玛尔扎哈',
          'gui_combo_num_key': 'combo_num_玛尔扎哈'},
 '泰隆': {'name': '泰隆',
        'jobs': ['刺客'],
        'races': ['执事'],
        'price': '2',
        'gui_name': '2-泰隆',
        'gui_checkbox_key': 'checkbox_泰隆',
        'gui_combo_num_key': 'combo_num_泰隆'},
 '阿狸': {'name': '阿狸',
        'jobs': ['黑魔法师'],
        'races': ['辛迪加'],
        'price': '4',
        'gui_name': '4-阿狸',
        'gui_checkbox_key': 'checkbox_阿狸',
        'gui_combo_num_key': 'combo_num_阿狸'},
 '维克托': {'name': '维克托',
         'jobs': ['黑魔法师'],
         'races': ['炼金科技'],
         'price': '5',
         'gui_name': '5-维克托',
         'gui_checkbox_key': 'checkbox_维克托',
         'gui_combo_num_key': 'combo_num_维克托'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['格斗家'],
         'races': ['执法官', '海克斯科技'],
         'price': '2',
         'gui_name': '2-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '吉格斯': {'name': '吉格斯',
         'jobs': ['黑魔法师'],
         'races': ['极客', '约德尔人'],
         'price': '1',
         'gui_name': '1-吉格斯',
         'gui_checkbox_key': 'checkbox_吉格斯',
         'gui_combo_num_key': 'combo_num_吉格斯'},
 '璐璐': {'name': '璐璐',
        'jobs': ['白魔法师'],
        'races': ['约德尔人'],
        'price': '2',
        'gui_name': '2-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '德莱文': {'name': '德莱文',
         'jobs': ['挑战者'],
         'races': ['执事'],
         'price': '4',
         'gui_name': '4-德莱文',
         'gui_checkbox_key': 'checkbox_德莱文',
         'gui_combo_num_key': 'combo_num_德莱文'},
 '卡兹克': {'name': '卡兹克',
         'jobs': ['刺客'],
         'races': ['变异战士'],
         'price': '4',
         'gui_name': '4-卡兹克',
         'gui_checkbox_key': 'checkbox_卡兹克',
         'gui_combo_num_key': 'combo_num_卡兹克'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['保镖'],
          'races': ['辛迪加'],
          'price': '1',
          'gui_name': '1-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '杰斯': {'name': '杰斯',
        'jobs': ['发明家', '未来守护者'],
        'races': ['执法官'],
        'price': '5',
        'gui_name': '5-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '奎因': {'name': '奎因',
        'jobs': ['挑战者'],
        'races': ['赏金猎人'],
        'price': '2',
        'gui_name': '2-奎因',
        'gui_checkbox_key': 'checkbox_奎因',
        'gui_combo_num_key': 'combo_num_奎因'},
 '辛德拉': {'name': '辛德拉',
         'jobs': ['学者'],
         'races': ['执事'],
         'price': '2',
         'gui_name': '2-辛德拉',
         'gui_checkbox_key': 'checkbox_辛德拉',
         'gui_combo_num_key': 'combo_num_辛德拉'},
 '婕拉': {'name': '婕拉',
        'jobs': ['学者'],
        'races': ['辛迪加'],
        'price': '2',
        'gui_name': '2-婕拉',
        'gui_checkbox_key': 'checkbox_婕拉',
        'gui_combo_num_key': 'combo_num_婕拉'},
 '卡莎': {'name': '卡莎',
        'jobs': ['挑战者'],
        'races': ['变异战士'],
        'price': '5',
        'gui_name': '5-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'},
 '萨勒芬妮': {'name': '萨勒芬妮',
          'jobs': ['发明家'],
          'races': ['社交名流'],
          'price': '4',
          'gui_name': '4-萨勒芬妮',
          'gui_checkbox_key': 'checkbox_萨勒芬妮',
          'gui_combo_num_key': 'combo_num_萨勒芬妮'},
 '纳尔': {'name': '纳尔',
        'jobs': ['强袭战士'],
        'races': ['社交名流', '约德尔人'],
        'price': '3',
        'gui_name': '3-纳尔',
        'gui_checkbox_key': 'checkbox_纳尔',
        'gui_combo_num_key': 'combo_num_纳尔'},
 '扎克': {'name': '扎克',
        'jobs': ['格斗家'],
        'races': ['炼金科技'],
        'price': '3',
        'gui_name': '3-扎克',
        'gui_checkbox_key': 'checkbox_扎克',
        'gui_combo_num_key': 'combo_num_扎克'},
 '卡蜜尔': {'name': '卡蜜尔',
         'jobs': ['挑战者'],
         'races': ['精密发条'],
         'price': '1',
         'gui_name': '1-卡蜜尔',
         'gui_checkbox_key': 'checkbox_卡蜜尔',
         'gui_combo_num_key': 'combo_num_卡蜜尔'},
 '布隆': {'name': '布隆',
        'jobs': ['保镖'],
        'races': ['辛迪加'],
        'price': '4',
        'gui_name': '4-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '烬': {'name': '烬',
       'jobs': ['狙神'],
       'races': ['精密发条'],
       'price': '4',
       'gui_name': '4-烬',
       'gui_checkbox_key': 'checkbox_烬',
       'gui_combo_num_key': 'combo_num_烬'},
 '泽丽': {'name': '泽丽',
        'jobs': ['狙神'],
        'races': ['执事'],
        'price': '5',
        'gui_name': '5-泽丽',
        'gui_checkbox_key': 'checkbox_泽丽',
        'gui_combo_num_key': 'combo_num_泽丽'},
 '金克丝': {'name': '金克丝',
         'jobs': ['枪手'],
         'races': ['极客', '宿敌'],
         'price': '5',
         'gui_name': '5-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '塔姆': {'name': '塔姆',
        'jobs': ['格斗家'],
        'races': ['赏金猎人', '食神'],
        'price': '5',
        'gui_name': '5-塔姆',
        'gui_checkbox_key': 'checkbox_塔姆',
        'gui_combo_num_key': 'combo_num_塔姆'},
 '赛娜': {'name': '赛娜',
        'jobs': ['白魔法师'],
        'races': ['社交名流'],
        'price': '3',
        'gui_name': '3-赛娜',
        'gui_checkbox_key': 'checkbox_赛娜',
        'gui_combo_num_key': 'combo_num_赛娜'},
 '卢锡安': {'name': '卢锡安',
         'jobs': ['枪手'],
         'races': ['海克斯科技'],
         'price': '3',
         'gui_name': '3-卢锡安',
         'gui_checkbox_key': 'checkbox_卢锡安',
         'gui_combo_num_key': 'combo_num_卢锡安'},
 '艾克': {'name': '艾克',
        'jobs': ['刺客', '发明家'],
        'races': ['极客'],
        'price': '3',
        'gui_name': '3-艾克',
        'gui_checkbox_key': 'checkbox_艾克',
        'gui_combo_num_key': 'combo_num_艾克'},
 '蔚': {'name': '蔚',
       'jobs': ['格斗家'],
       'races': ['执法官', '宿敌'],
       'price': '4',
       'gui_name': '4-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '俄洛伊': {'name': '俄洛伊',
         'jobs': ['格斗家'],
         'races': ['赏金猎人'],
         'price': '1',
         'gui_name': '1-俄洛伊',
         'gui_checkbox_key': 'checkbox_俄洛伊',
         'gui_combo_num_key': 'combo_num_俄洛伊'},
 '雷克塞': {'name': '雷克塞',
         'jobs': ['格斗家', '强袭战士'],
         'races': ['变异战士'],
         'price': '2',
         'gui_name': '2-雷克塞',
         'gui_checkbox_key': 'checkbox_雷克塞',
         'gui_combo_num_key': 'combo_num_雷克塞'},
 '薇古丝': {'name': '薇古丝',
         'jobs': ['黑魔法师'],
         'races': ['约德尔人'],
         'price': '3',
         'gui_name': '3-薇古丝',
         'gui_checkbox_key': 'checkbox_薇古丝',
         'gui_combo_num_key': 'combo_num_薇古丝'},
 '烈娜塔': {'name': '烈娜塔',
         'jobs': ['学者'],
         'races': ['炼金科技'],
         'price': '4',
         'gui_name': '4-烈娜塔',
         'gui_checkbox_key': 'checkbox_烈娜塔',
         'gui_combo_num_key': 'combo_num_烈娜塔'},
 '希尔科': {'name': '希尔科',
         'jobs': ['学者'],
         'races': ['微光首脑'],
         'price': '5',
         'gui_name': '5-希尔科',
         'gui_checkbox_key': 'checkbox_希尔科',
         'gui_combo_num_key': 'combo_num_希尔科'}}
