"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's7.5-隐秘海域',
 '版本信息': '12.17',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '12.17-2022.S7',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.17-2022.S7/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.17-2022.S7/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.17-2022.S7/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.17-2022.S7/equip.js',
 'url_hex_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/12.17-2022.S7/hex.js'}

    all_chess_name_str = ('奥拉夫-弗拉基米尔-索拉卡-崔丝塔娜-努努和威朗普-贾克斯-图奇-卡尔玛-墨菲特-孙悟空-李青-斯卡纳-黑默丁格-内瑟斯-奈德丽-潘森-伊泽瑞尔-蕾欧娜-拉克丝-希瓦娜-格雷福斯-沃利贝尔-雷恩加尔-韦鲁斯-瑟庄妮-璐璐-赫卡里姆-杰斯-黛安娜-奥瑞利安 '
 '· '
 '索尔-佐伊-婕拉-卡莎-萨勒芬妮-纳尔-扎克-亚索-塔莉垭-布隆-泽丽-赛娜-奇亚娜-巴德-洛-霞-塞拉斯-厄斐琉斯-芮尔-永恩-瑟提-莉莉娅-尼菈-迭嘉-石傲玉-斯维因-艾达丝-赛芬-敖兴-诺姆希-诺姆希-诺姆希-索姆-泰拉-呲呲-玉猫雕像')

    all_race_name_str = '星界龙-冒险家-玉龙-幻镜龙-怒翼龙-屠龙勇士-金鳞龙-风暴龙-幽影龙-黯灵龙-碧波龙-巨岩龙-龙族小天才'

    all_job_name_str = '刺客-吟游诗人-格斗家-强袭炮手-重骑兵-神龙尊者-魔导师-护卫-法师-秘术师-换形师-迅捷射手-狂刃战士-龙神-窃法巧手-唤星者-召唤物'

    race_chess = {'星界龙': ['弗拉基米尔', '斯卡纳', '奈德丽', '拉克丝', '韦鲁斯', '奥瑞利安 · 索尔'],
 '冒险家': ['图奇', '瑟庄妮', '杰斯', '巴德', '呲呲'],
 '玉龙': ['索拉卡', '贾克斯', '卡尔玛', '孙悟空', '纳尔', '石傲玉', '玉猫雕像'],
 '幻镜龙': ['努努和威朗普', '蕾欧娜', '亚索', '永恩', '迭嘉'],
 '怒翼龙': ['希瓦娜', '赫卡里姆', '赛娜', '洛', '霞', '瑟提'],
 '屠龙勇士': ['奥拉夫', '黛安娜', '布隆', '莉莉娅'],
 '金鳞龙': ['贾克斯', '内瑟斯', '沃利贝尔', '佐伊', '艾达丝'],
 '风暴龙': ['李青', '伊泽瑞尔', '格雷福斯', '奇亚娜', '敖兴'],
 '幽影龙': ['潘森', '婕拉', '塞拉斯', '赛芬'],
 '黯灵龙': ['雷恩加尔', '厄斐琉斯', '芮尔', '斯维因'],
 '碧波龙': ['墨菲特', '卡莎', '萨勒芬妮', '扎克', '塔莉垭', '泽丽', '尼菈', '索姆'],
 '巨岩龙': ['泰拉'],
 '龙族小天才': ['崔丝塔娜', '黑默丁格', '璐璐', '诺姆希', '诺姆希', '诺姆希']}

    job_chess = {'刺客': ['雷恩加尔', '黛安娜', '奇亚娜', '尼菈'],
 '吟游诗人': ['巴德'],
 '格斗家': ['奥拉夫', '贾克斯', '墨菲特', '斯卡纳', '塞拉斯', '赛芬'],
 '强袭炮手': ['崔丝塔娜', '格雷福斯', '泽丽', '赛娜', '厄斐琉斯', '诺姆希'],
 '重骑兵': ['努努和威朗普', '瑟庄妮', '赫卡里姆', '芮尔', '莉莉娅'],
 '神龙尊者': ['卡尔玛', '李青', '沃利贝尔', '卡莎', '亚索', '瑟提'],
 '魔导师': ['璐璐', '奥瑞利安 · 索尔', '婕拉', '萨勒芬妮', '诺姆希'],
 '护卫': ['内瑟斯', '蕾欧娜', '扎克', '布隆', '洛', '艾达丝'],
 '法师': ['弗拉基米尔', '黑默丁格', '拉克丝', '佐伊', '塔莉垭', '塞拉斯', '莉莉娅', '诺姆希', '索姆'],
 '秘术师': ['萨勒芬妮', '巴德', '洛', '石傲玉'],
 '换形师': ['奈德丽', '希瓦娜', '杰斯', '纳尔'],
 '迅捷射手': ['图奇', '伊泽瑞尔', '韦鲁斯', '霞'],
 '狂刃战士': ['奥拉夫', '孙悟空', '潘森', '亚索', '永恩'],
 '龙神': ['希瓦娜',
        '奥瑞利安 · 索尔',
        '迭嘉',
        '石傲玉',
        '斯维因',
        '艾达丝',
        '赛芬',
        '敖兴',
        '诺姆希',
        '诺姆希',
        '诺姆希',
        '索姆',
        '泰拉',
        '呲呲'],
 '窃法巧手': ['佐伊'],
 '唤星者': ['索拉卡'],
 '召唤物': ['崔丝塔娜', '黑默丁格', '璐璐', '玉猫雕像']}

    price_chess = {'0': ['崔丝塔娜', '黑默丁格', '璐璐', '玉猫雕像'],
 '1': ['弗拉基米尔', '卡尔玛', '墨菲特', '孙悟空', '斯卡纳', '内瑟斯', '奈德丽', '伊泽瑞尔', '蕾欧娜', '瑟庄妮', '塔莉垭', '赛娜', '瑟提'],
 '2': ['贾克斯', '图奇', '拉克丝', '婕拉', '卡莎', '纳尔', '扎克', '布隆', '奇亚娜', '厄斐琉斯', '芮尔', '永恩', '莉莉娅'],
 '3': ['奥拉夫', '努努和威朗普', '李青', '沃利贝尔', '雷恩加尔', '韦鲁斯', '黛安娜', '萨勒芬妮', '泽丽', '洛', '塞拉斯'],
 '4': ['潘森', '格雷福斯', '赫卡里姆', '杰斯', '霞', '尼菈'],
 '5': ['索拉卡', '佐伊', '亚索', '巴德'],
 '6': ['诺姆希', '诺姆希', '诺姆希', '呲呲'],
 '7': ['迭嘉', '石傲玉', '斯维因', '艾达丝', '赛芬', '索姆'],
 '8': ['希瓦娜', '奥瑞利安 · 索尔', '敖兴', '泰拉']}

    chess_name_info = {'奥拉夫': {'name': '奥拉夫',
         'jobs': ['格斗家', '狂刃战士'],
         'races': ['屠龙勇士'],
         'price': '3',
         'gui_name': '3-奥拉夫',
         'gui_checkbox_key': 'checkbox_奥拉夫',
         'gui_combo_num_key': 'combo_num_奥拉夫'},
 '弗拉基米尔': {'name': '弗拉基米尔',
           'jobs': ['法师'],
           'races': ['星界龙'],
           'price': '1',
           'gui_name': '1-弗拉基米尔',
           'gui_checkbox_key': 'checkbox_弗拉基米尔',
           'gui_combo_num_key': 'combo_num_弗拉基米尔'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['唤星者'],
         'races': ['玉龙'],
         'price': '5',
         'gui_name': '5-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '崔丝塔娜': {'name': '崔丝塔娜',
          'jobs': ['强袭炮手', '召唤物'],
          'races': ['龙族小天才'],
          'price': '0',
          'gui_name': '0-崔丝塔娜',
          'gui_checkbox_key': 'checkbox_崔丝塔娜',
          'gui_combo_num_key': 'combo_num_崔丝塔娜'},
 '努努和威朗普': {'name': '努努和威朗普',
            'jobs': ['重骑兵'],
            'races': ['幻镜龙'],
            'price': '3',
            'gui_name': '3-努努和威朗普',
            'gui_checkbox_key': 'checkbox_努努和威朗普',
            'gui_combo_num_key': 'combo_num_努努和威朗普'},
 '贾克斯': {'name': '贾克斯',
         'jobs': ['格斗家'],
         'races': ['玉龙', '金鳞龙'],
         'price': '2',
         'gui_name': '2-贾克斯',
         'gui_checkbox_key': 'checkbox_贾克斯',
         'gui_combo_num_key': 'combo_num_贾克斯'},
 '图奇': {'name': '图奇',
        'jobs': ['迅捷射手'],
        'races': ['冒险家'],
        'price': '2',
        'gui_name': '2-图奇',
        'gui_checkbox_key': 'checkbox_图奇',
        'gui_combo_num_key': 'combo_num_图奇'},
 '卡尔玛': {'name': '卡尔玛',
         'jobs': ['神龙尊者'],
         'races': ['玉龙'],
         'price': '1',
         'gui_name': '1-卡尔玛',
         'gui_checkbox_key': 'checkbox_卡尔玛',
         'gui_combo_num_key': 'combo_num_卡尔玛'},
 '墨菲特': {'name': '墨菲特',
         'jobs': ['格斗家'],
         'races': ['碧波龙'],
         'price': '1',
         'gui_name': '1-墨菲特',
         'gui_checkbox_key': 'checkbox_墨菲特',
         'gui_combo_num_key': 'combo_num_墨菲特'},
 '孙悟空': {'name': '孙悟空',
         'jobs': ['狂刃战士'],
         'races': ['玉龙'],
         'price': '1',
         'gui_name': '1-孙悟空',
         'gui_checkbox_key': 'checkbox_孙悟空',
         'gui_combo_num_key': 'combo_num_孙悟空'},
 '李青': {'name': '李青',
        'jobs': ['神龙尊者'],
        'races': ['风暴龙'],
        'price': '3',
        'gui_name': '3-李青',
        'gui_checkbox_key': 'checkbox_李青',
        'gui_combo_num_key': 'combo_num_李青'},
 '斯卡纳': {'name': '斯卡纳',
         'jobs': ['格斗家'],
         'races': ['星界龙'],
         'price': '1',
         'gui_name': '1-斯卡纳',
         'gui_checkbox_key': 'checkbox_斯卡纳',
         'gui_combo_num_key': 'combo_num_斯卡纳'},
 '黑默丁格': {'name': '黑默丁格',
          'jobs': ['法师', '召唤物'],
          'races': ['龙族小天才'],
          'price': '0',
          'gui_name': '0-黑默丁格',
          'gui_checkbox_key': 'checkbox_黑默丁格',
          'gui_combo_num_key': 'combo_num_黑默丁格'},
 '内瑟斯': {'name': '内瑟斯',
         'jobs': ['护卫'],
         'races': ['金鳞龙'],
         'price': '1',
         'gui_name': '1-内瑟斯',
         'gui_checkbox_key': 'checkbox_内瑟斯',
         'gui_combo_num_key': 'combo_num_内瑟斯'},
 '奈德丽': {'name': '奈德丽',
         'jobs': ['换形师'],
         'races': ['星界龙'],
         'price': '1',
         'gui_name': '1-奈德丽',
         'gui_checkbox_key': 'checkbox_奈德丽',
         'gui_combo_num_key': 'combo_num_奈德丽'},
 '潘森': {'name': '潘森',
        'jobs': ['狂刃战士'],
        'races': ['幽影龙'],
        'price': '4',
        'gui_name': '4-潘森',
        'gui_checkbox_key': 'checkbox_潘森',
        'gui_combo_num_key': 'combo_num_潘森'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['迅捷射手'],
          'races': ['风暴龙'],
          'price': '1',
          'gui_name': '1-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '蕾欧娜': {'name': '蕾欧娜',
         'jobs': ['护卫'],
         'races': ['幻镜龙'],
         'price': '1',
         'gui_name': '1-蕾欧娜',
         'gui_checkbox_key': 'checkbox_蕾欧娜',
         'gui_combo_num_key': 'combo_num_蕾欧娜'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['法师'],
         'races': ['星界龙'],
         'price': '2',
         'gui_name': '2-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '希瓦娜': {'name': '希瓦娜',
         'jobs': ['换形师', '龙神'],
         'races': ['怒翼龙'],
         'price': '8',
         'gui_name': '8-希瓦娜',
         'gui_checkbox_key': 'checkbox_希瓦娜',
         'gui_combo_num_key': 'combo_num_希瓦娜'},
 '格雷福斯': {'name': '格雷福斯',
          'jobs': ['强袭炮手'],
          'races': ['风暴龙'],
          'price': '4',
          'gui_name': '4-格雷福斯',
          'gui_checkbox_key': 'checkbox_格雷福斯',
          'gui_combo_num_key': 'combo_num_格雷福斯'},
 '沃利贝尔': {'name': '沃利贝尔',
          'jobs': ['神龙尊者'],
          'races': ['金鳞龙'],
          'price': '3',
          'gui_name': '3-沃利贝尔',
          'gui_checkbox_key': 'checkbox_沃利贝尔',
          'gui_combo_num_key': 'combo_num_沃利贝尔'},
 '雷恩加尔': {'name': '雷恩加尔',
          'jobs': ['刺客'],
          'races': ['黯灵龙'],
          'price': '3',
          'gui_name': '3-雷恩加尔',
          'gui_checkbox_key': 'checkbox_雷恩加尔',
          'gui_combo_num_key': 'combo_num_雷恩加尔'},
 '韦鲁斯': {'name': '韦鲁斯',
         'jobs': ['迅捷射手'],
         'races': ['星界龙'],
         'price': '3',
         'gui_name': '3-韦鲁斯',
         'gui_checkbox_key': 'checkbox_韦鲁斯',
         'gui_combo_num_key': 'combo_num_韦鲁斯'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['重骑兵'],
         'races': ['冒险家'],
         'price': '1',
         'gui_name': '1-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '璐璐': {'name': '璐璐',
        'jobs': ['魔导师', '召唤物'],
        'races': ['龙族小天才'],
        'price': '0',
        'gui_name': '0-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '赫卡里姆': {'name': '赫卡里姆',
          'jobs': ['重骑兵'],
          'races': ['怒翼龙'],
          'price': '4',
          'gui_name': '4-赫卡里姆',
          'gui_checkbox_key': 'checkbox_赫卡里姆',
          'gui_combo_num_key': 'combo_num_赫卡里姆'},
 '杰斯': {'name': '杰斯',
        'jobs': ['换形师'],
        'races': ['冒险家'],
        'price': '4',
        'gui_name': '4-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '黛安娜': {'name': '黛安娜',
         'jobs': ['刺客'],
         'races': ['屠龙勇士'],
         'price': '3',
         'gui_name': '3-黛安娜',
         'gui_checkbox_key': 'checkbox_黛安娜',
         'gui_combo_num_key': 'combo_num_黛安娜'},
 '奥瑞利安 · 索尔': {'name': '奥瑞利安 · 索尔',
               'jobs': ['魔导师', '龙神'],
               'races': ['星界龙'],
               'price': '8',
               'gui_name': '8-奥瑞利安 · 索尔',
               'gui_checkbox_key': 'checkbox_奥瑞利安 · 索尔',
               'gui_combo_num_key': 'combo_num_奥瑞利安 · 索尔'},
 '佐伊': {'name': '佐伊',
        'jobs': ['法师', '窃法巧手'],
        'races': ['金鳞龙'],
        'price': '5',
        'gui_name': '5-佐伊',
        'gui_checkbox_key': 'checkbox_佐伊',
        'gui_combo_num_key': 'combo_num_佐伊'},
 '婕拉': {'name': '婕拉',
        'jobs': ['魔导师'],
        'races': ['幽影龙'],
        'price': '2',
        'gui_name': '2-婕拉',
        'gui_checkbox_key': 'checkbox_婕拉',
        'gui_combo_num_key': 'combo_num_婕拉'},
 '卡莎': {'name': '卡莎',
        'jobs': ['神龙尊者'],
        'races': ['碧波龙'],
        'price': '2',
        'gui_name': '2-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'},
 '萨勒芬妮': {'name': '萨勒芬妮',
          'jobs': ['魔导师', '秘术师'],
          'races': ['碧波龙'],
          'price': '3',
          'gui_name': '3-萨勒芬妮',
          'gui_checkbox_key': 'checkbox_萨勒芬妮',
          'gui_combo_num_key': 'combo_num_萨勒芬妮'},
 '纳尔': {'name': '纳尔',
        'jobs': ['换形师'],
        'races': ['玉龙'],
        'price': '2',
        'gui_name': '2-纳尔',
        'gui_checkbox_key': 'checkbox_纳尔',
        'gui_combo_num_key': 'combo_num_纳尔'},
 '扎克': {'name': '扎克',
        'jobs': ['护卫'],
        'races': ['碧波龙'],
        'price': '2',
        'gui_name': '2-扎克',
        'gui_checkbox_key': 'checkbox_扎克',
        'gui_combo_num_key': 'combo_num_扎克'},
 '亚索': {'name': '亚索',
        'jobs': ['神龙尊者', '狂刃战士'],
        'races': ['幻镜龙'],
        'price': '5',
        'gui_name': '5-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '塔莉垭': {'name': '塔莉垭',
         'jobs': ['法师'],
         'races': ['碧波龙'],
         'price': '1',
         'gui_name': '1-塔莉垭',
         'gui_checkbox_key': 'checkbox_塔莉垭',
         'gui_combo_num_key': 'combo_num_塔莉垭'},
 '布隆': {'name': '布隆',
        'jobs': ['护卫'],
        'races': ['屠龙勇士'],
        'price': '2',
        'gui_name': '2-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '泽丽': {'name': '泽丽',
        'jobs': ['强袭炮手'],
        'races': ['碧波龙'],
        'price': '3',
        'gui_name': '3-泽丽',
        'gui_checkbox_key': 'checkbox_泽丽',
        'gui_combo_num_key': 'combo_num_泽丽'},
 '赛娜': {'name': '赛娜',
        'jobs': ['强袭炮手'],
        'races': ['怒翼龙'],
        'price': '1',
        'gui_name': '1-赛娜',
        'gui_checkbox_key': 'checkbox_赛娜',
        'gui_combo_num_key': 'combo_num_赛娜'},
 '奇亚娜': {'name': '奇亚娜',
         'jobs': ['刺客'],
         'races': ['风暴龙'],
         'price': '2',
         'gui_name': '2-奇亚娜',
         'gui_checkbox_key': 'checkbox_奇亚娜',
         'gui_combo_num_key': 'combo_num_奇亚娜'},
 '巴德': {'name': '巴德',
        'jobs': ['吟游诗人', '秘术师'],
        'races': ['冒险家'],
        'price': '5',
        'gui_name': '5-巴德',
        'gui_checkbox_key': 'checkbox_巴德',
        'gui_combo_num_key': 'combo_num_巴德'},
 '洛': {'name': '洛',
       'jobs': ['护卫', '秘术师'],
       'races': ['怒翼龙'],
       'price': '3',
       'gui_name': '3-洛',
       'gui_checkbox_key': 'checkbox_洛',
       'gui_combo_num_key': 'combo_num_洛'},
 '霞': {'name': '霞',
       'jobs': ['迅捷射手'],
       'races': ['怒翼龙'],
       'price': '4',
       'gui_name': '4-霞',
       'gui_checkbox_key': 'checkbox_霞',
       'gui_combo_num_key': 'combo_num_霞'},
 '塞拉斯': {'name': '塞拉斯',
         'jobs': ['格斗家', '法师'],
         'races': ['幽影龙'],
         'price': '3',
         'gui_name': '3-塞拉斯',
         'gui_checkbox_key': 'checkbox_塞拉斯',
         'gui_combo_num_key': 'combo_num_塞拉斯'},
 '厄斐琉斯': {'name': '厄斐琉斯',
          'jobs': ['强袭炮手'],
          'races': ['黯灵龙'],
          'price': '2',
          'gui_name': '2-厄斐琉斯',
          'gui_checkbox_key': 'checkbox_厄斐琉斯',
          'gui_combo_num_key': 'combo_num_厄斐琉斯'},
 '芮尔': {'name': '芮尔',
        'jobs': ['重骑兵'],
        'races': ['黯灵龙'],
        'price': '2',
        'gui_name': '2-芮尔',
        'gui_checkbox_key': 'checkbox_芮尔',
        'gui_combo_num_key': 'combo_num_芮尔'},
 '永恩': {'name': '永恩',
        'jobs': ['狂刃战士'],
        'races': ['幻镜龙'],
        'price': '2',
        'gui_name': '2-永恩',
        'gui_checkbox_key': 'checkbox_永恩',
        'gui_combo_num_key': 'combo_num_永恩'},
 '瑟提': {'name': '瑟提',
        'jobs': ['神龙尊者'],
        'races': ['怒翼龙'],
        'price': '1',
        'gui_name': '1-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'},
 '莉莉娅': {'name': '莉莉娅',
         'jobs': ['重骑兵', '法师'],
         'races': ['屠龙勇士'],
         'price': '2',
         'gui_name': '2-莉莉娅',
         'gui_checkbox_key': 'checkbox_莉莉娅',
         'gui_combo_num_key': 'combo_num_莉莉娅'},
 '尼菈': {'name': '尼菈',
        'jobs': ['刺客'],
        'races': ['碧波龙'],
        'price': '4',
        'gui_name': '4-尼菈',
        'gui_checkbox_key': 'checkbox_尼菈',
        'gui_combo_num_key': 'combo_num_尼菈'},
 '迭嘉': {'name': '迭嘉',
        'jobs': ['龙神'],
        'races': ['幻镜龙'],
        'price': '7',
        'gui_name': '7-迭嘉',
        'gui_checkbox_key': 'checkbox_迭嘉',
        'gui_combo_num_key': 'combo_num_迭嘉'},
 '石傲玉': {'name': '石傲玉',
         'jobs': ['秘术师', '龙神'],
         'races': ['玉龙'],
         'price': '7',
         'gui_name': '7-石傲玉',
         'gui_checkbox_key': 'checkbox_石傲玉',
         'gui_combo_num_key': 'combo_num_石傲玉'},
 '斯维因': {'name': '斯维因',
         'jobs': ['龙神'],
         'races': ['黯灵龙'],
         'price': '7',
         'gui_name': '7-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '艾达丝': {'name': '艾达丝',
         'jobs': ['护卫', '龙神'],
         'races': ['金鳞龙'],
         'price': '7',
         'gui_name': '7-艾达丝',
         'gui_checkbox_key': 'checkbox_艾达丝',
         'gui_combo_num_key': 'combo_num_艾达丝'},
 '赛芬': {'name': '赛芬',
        'jobs': ['格斗家', '龙神'],
        'races': ['幽影龙'],
        'price': '7',
        'gui_name': '7-赛芬',
        'gui_checkbox_key': 'checkbox_赛芬',
        'gui_combo_num_key': 'combo_num_赛芬'},
 '敖兴': {'name': '敖兴',
        'jobs': ['龙神'],
        'races': ['风暴龙'],
        'price': '8',
        'gui_name': '8-敖兴',
        'gui_checkbox_key': 'checkbox_敖兴',
        'gui_combo_num_key': 'combo_num_敖兴'},
 '诺姆希': {'name': '诺姆希',
         'jobs': ['强袭炮手', '魔导师', '法师', '龙神'],
         'races': ['龙族小天才'],
         'price': '6',
         'gui_name': '6-诺姆希',
         'gui_checkbox_key': 'checkbox_诺姆希',
         'gui_combo_num_key': 'combo_num_诺姆希'},
 '索姆': {'name': '索姆',
        'jobs': ['法师', '龙神'],
        'races': ['碧波龙'],
        'price': '7',
        'gui_name': '7-索姆',
        'gui_checkbox_key': 'checkbox_索姆',
        'gui_combo_num_key': 'combo_num_索姆'},
 '泰拉': {'name': '泰拉',
        'jobs': ['龙神'],
        'races': ['巨岩龙'],
        'price': '8',
        'gui_name': '8-泰拉',
        'gui_checkbox_key': 'checkbox_泰拉',
        'gui_combo_num_key': 'combo_num_泰拉'},
 '呲呲': {'name': '呲呲',
        'jobs': ['龙神'],
        'races': ['冒险家'],
        'price': '6',
        'gui_name': '6-呲呲',
        'gui_checkbox_key': 'checkbox_呲呲',
        'gui_combo_num_key': 'combo_num_呲呲'},
 '玉猫雕像': {'name': '玉猫雕像',
          'jobs': ['召唤物'],
          'races': ['玉龙'],
          'price': '0',
          'gui_name': '0-玉猫雕像',
          'gui_checkbox_key': 'checkbox_玉猫雕像',
          'gui_combo_num_key': 'combo_num_玉猫雕像'}}
