"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's1-初代赛季',
 '版本信息': '9.21',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '9.21-2019.S1',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.21-2019.S1/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.21-2019.S1/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.21-2019.S1/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.21-2019.S1/equip.js',
 'url_hex_data': None,
 '强化符文说明': '该赛季尚未引入强化符文系统'}

    all_chess_name_str = ('卡特琳娜-德莱厄斯-斯维因-德莱文-沃利贝尔-瑟庄妮-布隆-艾希-丽桑卓-艾尼维亚-伊芙琳-莫甘娜-伊莉丝-亚托克斯-韦鲁斯-布兰德-菲奥娜-盖伦-凯尔-卢锡安-曙光女神\t'
 '-薇恩-血港魅影-海洋之灾-法外狂徒-赏金猎人\t'
 '-死亡颂唱者-铁铠冥魂-永猎双子-蒸汽机器人-疾风剑豪-铸星龙王-龙血武姬-影流之主-离群之刺-暮光之眼-狂暴之心-虚空掠夺者-雷克塞-科加斯-卡萨丁-雷恩加尔-沃里克-阿狸-奈德丽-纳尔-璐璐-维迦-波比-崔丝塔娜-崔斯特-金克丝-蔚-杰斯-卡蜜尔-潘森-卡莎')

    all_race_name_str = '恶魔-龙-浪人-极地-帝国-忍者-贵族-暗影-海盗-机器人-虚空-狂野-约德尔人-海克斯'

    all_job_name_str = '法师-刺客-剑士-斗士-元素使-护卫-枪手-骑士-游侠-换形师'

    race_chess = {'恶魔': ['斯维因', '伊芙琳', '莫甘娜', '伊莉丝', '亚托克斯', '韦鲁斯', '布兰德'],
 '龙': ['铸星龙王', '龙血武姬', '潘森'],
 '浪人': ['疾风剑豪'],
 '极地': ['沃利贝尔', '瑟庄妮', '布隆', '艾希', '丽桑卓', '艾尼维亚'],
 '帝国': ['卡特琳娜', '德莱厄斯', '斯维因', '德莱文'],
 '忍者': ['影流之主', '离群之刺', '暮光之眼', '狂暴之心'],
 '贵族': ['菲奥娜', '盖伦', '凯尔', '卢锡安', '曙光女神\t', '薇恩'],
 '暗影': ['死亡颂唱者', '铁铠冥魂', '永猎双子'],
 '海盗': ['血港魅影', '海洋之灾', '法外狂徒', '赏金猎人\t', '崔斯特'],
 '机器人': ['蒸汽机器人'],
 '虚空': ['虚空掠夺者', '雷克塞', '科加斯', '卡萨丁', '卡莎'],
 '狂野': ['雷恩加尔', '沃里克', '阿狸', '奈德丽'],
 '约德尔人': ['纳尔', '璐璐', '维迦', '波比', '崔丝塔娜'],
 '海克斯': ['金克丝', '蔚', '杰斯', '卡蜜尔']}

    job_chess = {'法师': ['莫甘娜', '布兰德', '死亡颂唱者', '铸星龙王', '卡萨丁', '阿狸', '璐璐', '维迦', '崔斯特'],
 '刺客': ['卡特琳娜', '伊芙琳', '血港魅影', '影流之主', '离群之刺', '虚空掠夺者', '雷恩加尔', '卡莎'],
 '剑士': ['德莱文', '亚托克斯', '菲奥娜', '海洋之灾', '疾风剑豪', '暮光之眼', '卡蜜尔'],
 '斗士': ['沃利贝尔', '蒸汽机器人', '雷克塞', '科加斯', '沃里克', '蔚'],
 '元素使': ['丽桑卓', '艾尼维亚', '狂暴之心'],
 '护卫': ['布隆', '曙光女神\t', '潘森'],
 '枪手': ['卢锡安', '海洋之灾', '法外狂徒', '赏金猎人\t', '崔丝塔娜', '金克丝'],
 '骑士': ['德莱厄斯', '瑟庄妮', '盖伦', '凯尔', '铁铠冥魂', '波比'],
 '游侠': ['艾希', '韦鲁斯', '薇恩', '永猎双子', '卡莎'],
 '换形师': ['斯维因', '伊莉丝', '龙血武姬', '奈德丽', '纳尔', '杰斯']}

    price_chess = {'1': ['德莱厄斯',
       '伊莉丝',
       '菲奥娜',
       '盖伦',
       '薇恩',
       '法外狂徒',
       '铁铠冥魂',
       '虚空掠夺者',
       '卡萨丁',
       '沃里克',
       '奈德丽',
       '崔丝塔娜',
       '卡蜜尔'],
 '2': ['布隆',
       '丽桑卓',
       '韦鲁斯',
       '卢锡安',
       '血港魅影',
       '死亡颂唱者',
       '永猎双子',
       '蒸汽机器人',
       '影流之主',
       '暮光之眼',
       '雷克塞',
       '阿狸',
       '璐璐',
       '崔斯特',
       '杰斯'],
 '3': ['卡特琳娜',
       '沃利贝尔',
       '艾希',
       '伊芙琳',
       '莫甘娜',
       '亚托克斯',
       '海洋之灾',
       '赏金猎人\t',
       '龙血武姬',
       '狂暴之心',
       '雷恩加尔',
       '维迦',
       '波比',
       '蔚'],
 '4': ['德莱文', '瑟庄妮', '布兰德', '曙光女神\t', '铸星龙王', '离群之刺', '科加斯', '纳尔', '金克丝'],
 '5': ['斯维因', '艾尼维亚', '凯尔', '疾风剑豪', '潘森', '卡莎']}

    chess_name_info = {'卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['刺客'],
          'races': ['帝国'],
          'price': '3',
          'gui_name': '3-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['骑士'],
          'races': ['帝国'],
          'price': '1',
          'gui_name': '1-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '斯维因': {'name': '斯维因',
         'jobs': ['换形师'],
         'races': ['恶魔', '帝国'],
         'price': '5',
         'gui_name': '5-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '德莱文': {'name': '德莱文',
         'jobs': ['剑士'],
         'races': ['帝国'],
         'price': '4',
         'gui_name': '4-德莱文',
         'gui_checkbox_key': 'checkbox_德莱文',
         'gui_combo_num_key': 'combo_num_德莱文'},
 '沃利贝尔': {'name': '沃利贝尔',
          'jobs': ['斗士'],
          'races': ['极地'],
          'price': '3',
          'gui_name': '3-沃利贝尔',
          'gui_checkbox_key': 'checkbox_沃利贝尔',
          'gui_combo_num_key': 'combo_num_沃利贝尔'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['骑士'],
         'races': ['极地'],
         'price': '4',
         'gui_name': '4-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '布隆': {'name': '布隆',
        'jobs': ['护卫'],
        'races': ['极地'],
        'price': '2',
        'gui_name': '2-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '艾希': {'name': '艾希',
        'jobs': ['游侠'],
        'races': ['极地'],
        'price': '3',
        'gui_name': '3-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '丽桑卓': {'name': '丽桑卓',
         'jobs': ['元素使'],
         'races': ['极地'],
         'price': '2',
         'gui_name': '2-丽桑卓',
         'gui_checkbox_key': 'checkbox_丽桑卓',
         'gui_combo_num_key': 'combo_num_丽桑卓'},
 '艾尼维亚': {'name': '艾尼维亚',
          'jobs': ['元素使'],
          'races': ['极地'],
          'price': '5',
          'gui_name': '5-艾尼维亚',
          'gui_checkbox_key': 'checkbox_艾尼维亚',
          'gui_combo_num_key': 'combo_num_艾尼维亚'},
 '伊芙琳': {'name': '伊芙琳',
         'jobs': ['刺客'],
         'races': ['恶魔'],
         'price': '3',
         'gui_name': '3-伊芙琳',
         'gui_checkbox_key': 'checkbox_伊芙琳',
         'gui_combo_num_key': 'combo_num_伊芙琳'},
 '莫甘娜': {'name': '莫甘娜',
         'jobs': ['法师'],
         'races': ['恶魔'],
         'price': '3',
         'gui_name': '3-莫甘娜',
         'gui_checkbox_key': 'checkbox_莫甘娜',
         'gui_combo_num_key': 'combo_num_莫甘娜'},
 '伊莉丝': {'name': '伊莉丝',
         'jobs': ['换形师'],
         'races': ['恶魔'],
         'price': '1',
         'gui_name': '1-伊莉丝',
         'gui_checkbox_key': 'checkbox_伊莉丝',
         'gui_combo_num_key': 'combo_num_伊莉丝'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['剑士'],
          'races': ['恶魔'],
          'price': '3',
          'gui_name': '3-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '韦鲁斯': {'name': '韦鲁斯',
         'jobs': ['游侠'],
         'races': ['恶魔'],
         'price': '2',
         'gui_name': '2-韦鲁斯',
         'gui_checkbox_key': 'checkbox_韦鲁斯',
         'gui_combo_num_key': 'combo_num_韦鲁斯'},
 '布兰德': {'name': '布兰德',
         'jobs': ['法师'],
         'races': ['恶魔'],
         'price': '4',
         'gui_name': '4-布兰德',
         'gui_checkbox_key': 'checkbox_布兰德',
         'gui_combo_num_key': 'combo_num_布兰德'},
 '菲奥娜': {'name': '菲奥娜',
         'jobs': ['剑士'],
         'races': ['贵族'],
         'price': '1',
         'gui_name': '1-菲奥娜',
         'gui_checkbox_key': 'checkbox_菲奥娜',
         'gui_combo_num_key': 'combo_num_菲奥娜'},
 '盖伦': {'name': '盖伦',
        'jobs': ['骑士'],
        'races': ['贵族'],
        'price': '1',
        'gui_name': '1-盖伦',
        'gui_checkbox_key': 'checkbox_盖伦',
        'gui_combo_num_key': 'combo_num_盖伦'},
 '凯尔': {'name': '凯尔',
        'jobs': ['骑士'],
        'races': ['贵族'],
        'price': '5',
        'gui_name': '5-凯尔',
        'gui_checkbox_key': 'checkbox_凯尔',
        'gui_combo_num_key': 'combo_num_凯尔'},
 '卢锡安': {'name': '卢锡安',
         'jobs': ['枪手'],
         'races': ['贵族'],
         'price': '2',
         'gui_name': '2-卢锡安',
         'gui_checkbox_key': 'checkbox_卢锡安',
         'gui_combo_num_key': 'combo_num_卢锡安'},
 '曙光女神\t': {'name': '曙光女神\t',
            'jobs': ['护卫'],
            'races': ['贵族'],
            'price': '4',
            'gui_name': '4-曙光女神\t',
            'gui_checkbox_key': 'checkbox_曙光女神\t',
            'gui_combo_num_key': 'combo_num_曙光女神\t'},
 '薇恩': {'name': '薇恩',
        'jobs': ['游侠'],
        'races': ['贵族'],
        'price': '1',
        'gui_name': '1-薇恩',
        'gui_checkbox_key': 'checkbox_薇恩',
        'gui_combo_num_key': 'combo_num_薇恩'},
 '血港魅影': {'name': '血港魅影',
          'jobs': ['刺客'],
          'races': ['海盗'],
          'price': '2',
          'gui_name': '2-血港魅影',
          'gui_checkbox_key': 'checkbox_血港魅影',
          'gui_combo_num_key': 'combo_num_血港魅影'},
 '海洋之灾': {'name': '海洋之灾',
          'jobs': ['剑士', '枪手'],
          'races': ['海盗'],
          'price': '3',
          'gui_name': '3-海洋之灾',
          'gui_checkbox_key': 'checkbox_海洋之灾',
          'gui_combo_num_key': 'combo_num_海洋之灾'},
 '法外狂徒': {'name': '法外狂徒',
          'jobs': ['枪手'],
          'races': ['海盗'],
          'price': '1',
          'gui_name': '1-法外狂徒',
          'gui_checkbox_key': 'checkbox_法外狂徒',
          'gui_combo_num_key': 'combo_num_法外狂徒'},
 '赏金猎人\t': {'name': '赏金猎人\t',
            'jobs': ['枪手'],
            'races': ['海盗'],
            'price': '3',
            'gui_name': '3-赏金猎人\t',
            'gui_checkbox_key': 'checkbox_赏金猎人\t',
            'gui_combo_num_key': 'combo_num_赏金猎人\t'},
 '死亡颂唱者': {'name': '死亡颂唱者',
           'jobs': ['法师'],
           'races': ['暗影'],
           'price': '2',
           'gui_name': '2-死亡颂唱者',
           'gui_checkbox_key': 'checkbox_死亡颂唱者',
           'gui_combo_num_key': 'combo_num_死亡颂唱者'},
 '铁铠冥魂': {'name': '铁铠冥魂',
          'jobs': ['骑士'],
          'races': ['暗影'],
          'price': '1',
          'gui_name': '1-铁铠冥魂',
          'gui_checkbox_key': 'checkbox_铁铠冥魂',
          'gui_combo_num_key': 'combo_num_铁铠冥魂'},
 '永猎双子': {'name': '永猎双子',
          'jobs': ['游侠'],
          'races': ['暗影'],
          'price': '2',
          'gui_name': '2-永猎双子',
          'gui_checkbox_key': 'checkbox_永猎双子',
          'gui_combo_num_key': 'combo_num_永猎双子'},
 '蒸汽机器人': {'name': '蒸汽机器人',
           'jobs': ['斗士'],
           'races': ['机器人'],
           'price': '2',
           'gui_name': '2-蒸汽机器人',
           'gui_checkbox_key': 'checkbox_蒸汽机器人',
           'gui_combo_num_key': 'combo_num_蒸汽机器人'},
 '疾风剑豪': {'name': '疾风剑豪',
          'jobs': ['剑士'],
          'races': ['浪人'],
          'price': '5',
          'gui_name': '5-疾风剑豪',
          'gui_checkbox_key': 'checkbox_疾风剑豪',
          'gui_combo_num_key': 'combo_num_疾风剑豪'},
 '铸星龙王': {'name': '铸星龙王',
          'jobs': ['法师'],
          'races': ['龙'],
          'price': '4',
          'gui_name': '4-铸星龙王',
          'gui_checkbox_key': 'checkbox_铸星龙王',
          'gui_combo_num_key': 'combo_num_铸星龙王'},
 '龙血武姬': {'name': '龙血武姬',
          'jobs': ['换形师'],
          'races': ['龙'],
          'price': '3',
          'gui_name': '3-龙血武姬',
          'gui_checkbox_key': 'checkbox_龙血武姬',
          'gui_combo_num_key': 'combo_num_龙血武姬'},
 '影流之主': {'name': '影流之主',
          'jobs': ['刺客'],
          'races': ['忍者'],
          'price': '2',
          'gui_name': '2-影流之主',
          'gui_checkbox_key': 'checkbox_影流之主',
          'gui_combo_num_key': 'combo_num_影流之主'},
 '离群之刺': {'name': '离群之刺',
          'jobs': ['刺客'],
          'races': ['忍者'],
          'price': '4',
          'gui_name': '4-离群之刺',
          'gui_checkbox_key': 'checkbox_离群之刺',
          'gui_combo_num_key': 'combo_num_离群之刺'},
 '暮光之眼': {'name': '暮光之眼',
          'jobs': ['剑士'],
          'races': ['忍者'],
          'price': '2',
          'gui_name': '2-暮光之眼',
          'gui_checkbox_key': 'checkbox_暮光之眼',
          'gui_combo_num_key': 'combo_num_暮光之眼'},
 '狂暴之心': {'name': '狂暴之心',
          'jobs': ['元素使'],
          'races': ['忍者'],
          'price': '3',
          'gui_name': '3-狂暴之心',
          'gui_checkbox_key': 'checkbox_狂暴之心',
          'gui_combo_num_key': 'combo_num_狂暴之心'},
 '虚空掠夺者': {'name': '虚空掠夺者',
           'jobs': ['刺客'],
           'races': ['虚空'],
           'price': '1',
           'gui_name': '1-虚空掠夺者',
           'gui_checkbox_key': 'checkbox_虚空掠夺者',
           'gui_combo_num_key': 'combo_num_虚空掠夺者'},
 '雷克塞': {'name': '雷克塞',
         'jobs': ['斗士'],
         'races': ['虚空'],
         'price': '2',
         'gui_name': '2-雷克塞',
         'gui_checkbox_key': 'checkbox_雷克塞',
         'gui_combo_num_key': 'combo_num_雷克塞'},
 '科加斯': {'name': '科加斯',
         'jobs': ['斗士'],
         'races': ['虚空'],
         'price': '4',
         'gui_name': '4-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '卡萨丁': {'name': '卡萨丁',
         'jobs': ['法师'],
         'races': ['虚空'],
         'price': '1',
         'gui_name': '1-卡萨丁',
         'gui_checkbox_key': 'checkbox_卡萨丁',
         'gui_combo_num_key': 'combo_num_卡萨丁'},
 '雷恩加尔': {'name': '雷恩加尔',
          'jobs': ['刺客'],
          'races': ['狂野'],
          'price': '3',
          'gui_name': '3-雷恩加尔',
          'gui_checkbox_key': 'checkbox_雷恩加尔',
          'gui_combo_num_key': 'combo_num_雷恩加尔'},
 '沃里克': {'name': '沃里克',
         'jobs': ['斗士'],
         'races': ['狂野'],
         'price': '1',
         'gui_name': '1-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '阿狸': {'name': '阿狸',
        'jobs': ['法师'],
        'races': ['狂野'],
        'price': '2',
        'gui_name': '2-阿狸',
        'gui_checkbox_key': 'checkbox_阿狸',
        'gui_combo_num_key': 'combo_num_阿狸'},
 '奈德丽': {'name': '奈德丽',
         'jobs': ['换形师'],
         'races': ['狂野'],
         'price': '1',
         'gui_name': '1-奈德丽',
         'gui_checkbox_key': 'checkbox_奈德丽',
         'gui_combo_num_key': 'combo_num_奈德丽'},
 '纳尔': {'name': '纳尔',
        'jobs': ['换形师'],
        'races': ['约德尔人'],
        'price': '4',
        'gui_name': '4-纳尔',
        'gui_checkbox_key': 'checkbox_纳尔',
        'gui_combo_num_key': 'combo_num_纳尔'},
 '璐璐': {'name': '璐璐',
        'jobs': ['法师'],
        'races': ['约德尔人'],
        'price': '2',
        'gui_name': '2-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '维迦': {'name': '维迦',
        'jobs': ['法师'],
        'races': ['约德尔人'],
        'price': '3',
        'gui_name': '3-维迦',
        'gui_checkbox_key': 'checkbox_维迦',
        'gui_combo_num_key': 'combo_num_维迦'},
 '波比': {'name': '波比',
        'jobs': ['骑士'],
        'races': ['约德尔人'],
        'price': '3',
        'gui_name': '3-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '崔丝塔娜': {'name': '崔丝塔娜',
          'jobs': ['枪手'],
          'races': ['约德尔人'],
          'price': '1',
          'gui_name': '1-崔丝塔娜',
          'gui_checkbox_key': 'checkbox_崔丝塔娜',
          'gui_combo_num_key': 'combo_num_崔丝塔娜'},
 '崔斯特': {'name': '崔斯特',
         'jobs': ['法师'],
         'races': ['海盗'],
         'price': '2',
         'gui_name': '2-崔斯特',
         'gui_checkbox_key': 'checkbox_崔斯特',
         'gui_combo_num_key': 'combo_num_崔斯特'},
 '金克丝': {'name': '金克丝',
         'jobs': ['枪手'],
         'races': ['海克斯'],
         'price': '4',
         'gui_name': '4-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '蔚': {'name': '蔚',
       'jobs': ['斗士'],
       'races': ['海克斯'],
       'price': '3',
       'gui_name': '3-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '杰斯': {'name': '杰斯',
        'jobs': ['换形师'],
        'races': ['海克斯'],
        'price': '2',
        'gui_name': '2-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '卡蜜尔': {'name': '卡蜜尔',
         'jobs': ['剑士'],
         'races': ['海克斯'],
         'price': '1',
         'gui_name': '1-卡蜜尔',
         'gui_checkbox_key': 'checkbox_卡蜜尔',
         'gui_combo_num_key': 'combo_num_卡蜜尔'},
 '潘森': {'name': '潘森',
        'jobs': ['护卫'],
        'races': ['龙'],
        'price': '5',
        'gui_name': '5-潘森',
        'gui_checkbox_key': 'checkbox_潘森',
        'gui_combo_num_key': 'combo_num_潘森'},
 '卡莎': {'name': '卡莎',
        'jobs': ['刺客', '游侠'],
        'races': ['虚空'],
        'price': '5',
        'gui_name': '5-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'}}
