"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's4.5-瑞兽闹新春',
 '版本信息': '11.2',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '11.2-2021.S4',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.2-2021.S4/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.2-2021.S4/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.2-2021.S4/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.2-2021.S4/equip.js',
 'url_hex_data': None,
 '强化符文说明': '该赛季尚未引入强化符文系统'}

    all_chess_name_str = '安妮-奥拉夫-崔斯特-弗拉基米尔-凯尔-希维尔-提莫-崔丝塔娜-努努和威朗普-泰达米尔-贾克斯-莫甘娜-基兰-科加斯-艾瑞莉娅-迦娜-维迦-斯维因-卡特琳娜-茂凯-嘉文四世-伊莉丝-孙悟空-布兰德-李青-内瑟斯-奈德丽-阿卡丽-凯南-盖伦-泰隆-慎-希瓦娜-诺提勒斯-瑟庄妮-菲奥娜-璐璐-德莱厄斯-黛安娜-奥瑞利安·索尔-亚索-布隆-千珏-塔姆-劫-蔚-亚托克斯-阿兹尔-悠米-莎弥拉-卡莉丝塔-洛-霞-奥恩-妮蔻-派克-永恩-瑟提'

    all_race_name_str = '腥红之月-天神-永恒之森-玉剑仙-浪人-福星-忍者-灵魂莲华明昼-霸王-三国猛将-龙魂-山海绘卷-主宰'

    all_job_name_str = '宗师-刺客-斗士-决斗大师-神盾使-魔法师-秘术师-神射手-重装战士-枭雄-神使-战神-裁决使-铁匠'

    race_chess = {'腥红之月': ['崔斯特', '弗拉基米尔', '希维尔', '基兰', '伊莉丝', '亚托克斯', '卡莉丝塔', '派克'],
 '天神': ['凯尔', '贾克斯', '艾瑞莉娅', '孙悟空', '李青', '内瑟斯'],
 '永恒之森': ['努努和威朗普', '维迦', '茂凯', '璐璐', '洛', '霞', '奥恩'],
 '玉剑仙': ['莫甘娜', '艾瑞莉娅', '迦娜', '泰隆', '菲奥娜'],
 '浪人': ['亚索', '永恩'],
 '福星': ['安妮', '卡特琳娜', '瑟庄妮', '德莱厄斯', '塔姆'],
 '忍者': ['阿卡丽', '凯南', '慎', '劫'],
 '灵魂莲华明昼': ['提莫', '黛安娜', '千珏', '悠米'],
 '霸王': ['瑟提'],
 '三国猛将': ['泰达米尔', '卡特琳娜', '嘉文四世', '奈德丽', '盖伦', '蔚', '阿兹尔'],
 '龙魂': ['奥拉夫', '崔丝塔娜', '斯维因', '布兰德', '希瓦娜', '奥瑞利安·索尔', '布隆'],
 '山海绘卷': ['科加斯', '诺提勒斯', '妮蔻'],
 '主宰': ['莎弥拉']}

    job_chess = {'宗师': ['艾瑞莉娅', '慎', '永恩'],
 '刺客': ['卡特琳娜', '阿卡丽', '泰隆', '黛安娜', '派克'],
 '斗士': ['努努和威朗普', '科加斯', '茂凯', '希瓦娜', '塔姆', '蔚', '瑟提'],
 '决斗大师': ['泰达米尔', '贾克斯', '李青', '菲奥娜', '亚索', '卡莉丝塔'],
 '神盾使': ['嘉文四世', '伊莉丝', '凯南', '阿兹尔', '洛', '霞'],
 '魔法师': ['安妮', '崔斯特', '维迦', '布兰德', '璐璐', '奥瑞利安·索尔'],
 '秘术师': ['基兰', '迦娜', '慎', '悠米', '妮蔻'],
 '神射手': ['希维尔', '提莫', '崔丝塔娜', '奈德丽', '莎弥拉'],
 '重装战士': ['孙悟空', '盖伦', '诺提勒斯', '瑟庄妮', '布隆', '亚托克斯', '奥恩'],
 '枭雄': ['阿兹尔'],
 '神使': ['弗拉基米尔', '莫甘娜', '斯维因', '内瑟斯'],
 '战神': ['奥拉夫', '泰达米尔', '德莱厄斯', '劫', '莎弥拉', '派克'],
 '裁决使': ['凯尔', '千珏', '霞'],
 '铁匠': ['奥恩']}

    price_chess = {'1': ['崔斯特', '崔丝塔娜', '茂凯', '伊莉丝', '孙悟空', '布兰德', '内瑟斯', '奈德丽', '盖伦', '菲奥娜', '黛安娜', '亚索', '塔姆'],
 '2': ['安妮', '弗拉基米尔', '提莫', '贾克斯', '迦娜', '嘉文四世', '诺提勒斯', '璐璐', '布隆', '劫', '蔚', '洛', '派克'],
 '3': ['希维尔', '努努和威朗普', '艾瑞莉娅', '维迦', '卡特琳娜', '阿卡丽', '凯南', '希瓦娜', '德莱厄斯', '千珏', '悠米', '卡莉丝塔', '妮蔻'],
 '4': ['奥拉夫', '凯尔', '泰达米尔', '莫甘娜', '科加斯', '泰隆', '慎', '瑟庄妮', '奥瑞利安·索尔', '亚托克斯', '霞'],
 '5': ['基兰', '斯维因', '李青', '阿兹尔', '莎弥拉', '奥恩', '永恩', '瑟提']}

    chess_name_info = {'安妮': {'name': '安妮',
        'jobs': ['魔法师'],
        'races': ['福星'],
        'price': '2',
        'gui_name': '2-安妮',
        'gui_checkbox_key': 'checkbox_安妮',
        'gui_combo_num_key': 'combo_num_安妮'},
 '奥拉夫': {'name': '奥拉夫',
         'jobs': ['战神'],
         'races': ['龙魂'],
         'price': '4',
         'gui_name': '4-奥拉夫',
         'gui_checkbox_key': 'checkbox_奥拉夫',
         'gui_combo_num_key': 'combo_num_奥拉夫'},
 '崔斯特': {'name': '崔斯特',
         'jobs': ['魔法师'],
         'races': ['腥红之月'],
         'price': '1',
         'gui_name': '1-崔斯特',
         'gui_checkbox_key': 'checkbox_崔斯特',
         'gui_combo_num_key': 'combo_num_崔斯特'},
 '弗拉基米尔': {'name': '弗拉基米尔',
           'jobs': ['神使'],
           'races': ['腥红之月'],
           'price': '2',
           'gui_name': '2-弗拉基米尔',
           'gui_checkbox_key': 'checkbox_弗拉基米尔',
           'gui_combo_num_key': 'combo_num_弗拉基米尔'},
 '凯尔': {'name': '凯尔',
        'jobs': ['裁决使'],
        'races': ['天神'],
        'price': '4',
        'gui_name': '4-凯尔',
        'gui_checkbox_key': 'checkbox_凯尔',
        'gui_combo_num_key': 'combo_num_凯尔'},
 '希维尔': {'name': '希维尔',
         'jobs': ['神射手'],
         'races': ['腥红之月'],
         'price': '3',
         'gui_name': '3-希维尔',
         'gui_checkbox_key': 'checkbox_希维尔',
         'gui_combo_num_key': 'combo_num_希维尔'},
 '提莫': {'name': '提莫',
        'jobs': ['神射手'],
        'races': ['灵魂莲华明昼'],
        'price': '2',
        'gui_name': '2-提莫',
        'gui_checkbox_key': 'checkbox_提莫',
        'gui_combo_num_key': 'combo_num_提莫'},
 '崔丝塔娜': {'name': '崔丝塔娜',
          'jobs': ['神射手'],
          'races': ['龙魂'],
          'price': '1',
          'gui_name': '1-崔丝塔娜',
          'gui_checkbox_key': 'checkbox_崔丝塔娜',
          'gui_combo_num_key': 'combo_num_崔丝塔娜'},
 '努努和威朗普': {'name': '努努和威朗普',
            'jobs': ['斗士'],
            'races': ['永恒之森'],
            'price': '3',
            'gui_name': '3-努努和威朗普',
            'gui_checkbox_key': 'checkbox_努努和威朗普',
            'gui_combo_num_key': 'combo_num_努努和威朗普'},
 '泰达米尔': {'name': '泰达米尔',
          'jobs': ['决斗大师', '战神'],
          'races': ['三国猛将'],
          'price': '4',
          'gui_name': '4-泰达米尔',
          'gui_checkbox_key': 'checkbox_泰达米尔',
          'gui_combo_num_key': 'combo_num_泰达米尔'},
 '贾克斯': {'name': '贾克斯',
         'jobs': ['决斗大师'],
         'races': ['天神'],
         'price': '2',
         'gui_name': '2-贾克斯',
         'gui_checkbox_key': 'checkbox_贾克斯',
         'gui_combo_num_key': 'combo_num_贾克斯'},
 '莫甘娜': {'name': '莫甘娜',
         'jobs': ['神使'],
         'races': ['玉剑仙'],
         'price': '4',
         'gui_name': '4-莫甘娜',
         'gui_checkbox_key': 'checkbox_莫甘娜',
         'gui_combo_num_key': 'combo_num_莫甘娜'},
 '基兰': {'name': '基兰',
        'jobs': ['秘术师'],
        'races': ['腥红之月'],
        'price': '5',
        'gui_name': '5-基兰',
        'gui_checkbox_key': 'checkbox_基兰',
        'gui_combo_num_key': 'combo_num_基兰'},
 '科加斯': {'name': '科加斯',
         'jobs': ['斗士'],
         'races': ['山海绘卷'],
         'price': '4',
         'gui_name': '4-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '艾瑞莉娅': {'name': '艾瑞莉娅',
          'jobs': ['宗师'],
          'races': ['天神', '玉剑仙'],
          'price': '3',
          'gui_name': '3-艾瑞莉娅',
          'gui_checkbox_key': 'checkbox_艾瑞莉娅',
          'gui_combo_num_key': 'combo_num_艾瑞莉娅'},
 '迦娜': {'name': '迦娜',
        'jobs': ['秘术师'],
        'races': ['玉剑仙'],
        'price': '2',
        'gui_name': '2-迦娜',
        'gui_checkbox_key': 'checkbox_迦娜',
        'gui_combo_num_key': 'combo_num_迦娜'},
 '维迦': {'name': '维迦',
        'jobs': ['魔法师'],
        'races': ['永恒之森'],
        'price': '3',
        'gui_name': '3-维迦',
        'gui_checkbox_key': 'checkbox_维迦',
        'gui_combo_num_key': 'combo_num_维迦'},
 '斯维因': {'name': '斯维因',
         'jobs': ['神使'],
         'races': ['龙魂'],
         'price': '5',
         'gui_name': '5-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['刺客'],
          'races': ['福星', '三国猛将'],
          'price': '3',
          'gui_name': '3-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '茂凯': {'name': '茂凯',
        'jobs': ['斗士'],
        'races': ['永恒之森'],
        'price': '1',
        'gui_name': '1-茂凯',
        'gui_checkbox_key': 'checkbox_茂凯',
        'gui_combo_num_key': 'combo_num_茂凯'},
 '嘉文四世': {'name': '嘉文四世',
          'jobs': ['神盾使'],
          'races': ['三国猛将'],
          'price': '2',
          'gui_name': '2-嘉文四世',
          'gui_checkbox_key': 'checkbox_嘉文四世',
          'gui_combo_num_key': 'combo_num_嘉文四世'},
 '伊莉丝': {'name': '伊莉丝',
         'jobs': ['神盾使'],
         'races': ['腥红之月'],
         'price': '1',
         'gui_name': '1-伊莉丝',
         'gui_checkbox_key': 'checkbox_伊莉丝',
         'gui_combo_num_key': 'combo_num_伊莉丝'},
 '孙悟空': {'name': '孙悟空',
         'jobs': ['重装战士'],
         'races': ['天神'],
         'price': '1',
         'gui_name': '1-孙悟空',
         'gui_checkbox_key': 'checkbox_孙悟空',
         'gui_combo_num_key': 'combo_num_孙悟空'},
 '布兰德': {'name': '布兰德',
         'jobs': ['魔法师'],
         'races': ['龙魂'],
         'price': '1',
         'gui_name': '1-布兰德',
         'gui_checkbox_key': 'checkbox_布兰德',
         'gui_combo_num_key': 'combo_num_布兰德'},
 '李青': {'name': '李青',
        'jobs': ['决斗大师'],
        'races': ['天神'],
        'price': '5',
        'gui_name': '5-李青',
        'gui_checkbox_key': 'checkbox_李青',
        'gui_combo_num_key': 'combo_num_李青'},
 '内瑟斯': {'name': '内瑟斯',
         'jobs': ['神使'],
         'races': ['天神'],
         'price': '1',
         'gui_name': '1-内瑟斯',
         'gui_checkbox_key': 'checkbox_内瑟斯',
         'gui_combo_num_key': 'combo_num_内瑟斯'},
 '奈德丽': {'name': '奈德丽',
         'jobs': ['神射手'],
         'races': ['三国猛将'],
         'price': '1',
         'gui_name': '1-奈德丽',
         'gui_checkbox_key': 'checkbox_奈德丽',
         'gui_combo_num_key': 'combo_num_奈德丽'},
 '阿卡丽': {'name': '阿卡丽',
         'jobs': ['刺客'],
         'races': ['忍者'],
         'price': '3',
         'gui_name': '3-阿卡丽',
         'gui_checkbox_key': 'checkbox_阿卡丽',
         'gui_combo_num_key': 'combo_num_阿卡丽'},
 '凯南': {'name': '凯南',
        'jobs': ['神盾使'],
        'races': ['忍者'],
        'price': '3',
        'gui_name': '3-凯南',
        'gui_checkbox_key': 'checkbox_凯南',
        'gui_combo_num_key': 'combo_num_凯南'},
 '盖伦': {'name': '盖伦',
        'jobs': ['重装战士'],
        'races': ['三国猛将'],
        'price': '1',
        'gui_name': '1-盖伦',
        'gui_checkbox_key': 'checkbox_盖伦',
        'gui_combo_num_key': 'combo_num_盖伦'},
 '泰隆': {'name': '泰隆',
        'jobs': ['刺客'],
        'races': ['玉剑仙'],
        'price': '4',
        'gui_name': '4-泰隆',
        'gui_checkbox_key': 'checkbox_泰隆',
        'gui_combo_num_key': 'combo_num_泰隆'},
 '慎': {'name': '慎',
       'jobs': ['宗师', '秘术师'],
       'races': ['忍者'],
       'price': '4',
       'gui_name': '4-慎',
       'gui_checkbox_key': 'checkbox_慎',
       'gui_combo_num_key': 'combo_num_慎'},
 '希瓦娜': {'name': '希瓦娜',
         'jobs': ['斗士'],
         'races': ['龙魂'],
         'price': '3',
         'gui_name': '3-希瓦娜',
         'gui_checkbox_key': 'checkbox_希瓦娜',
         'gui_combo_num_key': 'combo_num_希瓦娜'},
 '诺提勒斯': {'name': '诺提勒斯',
          'jobs': ['重装战士'],
          'races': ['山海绘卷'],
          'price': '2',
          'gui_name': '2-诺提勒斯',
          'gui_checkbox_key': 'checkbox_诺提勒斯',
          'gui_combo_num_key': 'combo_num_诺提勒斯'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['重装战士'],
         'races': ['福星'],
         'price': '4',
         'gui_name': '4-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '菲奥娜': {'name': '菲奥娜',
         'jobs': ['决斗大师'],
         'races': ['玉剑仙'],
         'price': '1',
         'gui_name': '1-菲奥娜',
         'gui_checkbox_key': 'checkbox_菲奥娜',
         'gui_combo_num_key': 'combo_num_菲奥娜'},
 '璐璐': {'name': '璐璐',
        'jobs': ['魔法师'],
        'races': ['永恒之森'],
        'price': '2',
        'gui_name': '2-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['战神'],
          'races': ['福星'],
          'price': '3',
          'gui_name': '3-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '黛安娜': {'name': '黛安娜',
         'jobs': ['刺客'],
         'races': ['灵魂莲华明昼'],
         'price': '1',
         'gui_name': '1-黛安娜',
         'gui_checkbox_key': 'checkbox_黛安娜',
         'gui_combo_num_key': 'combo_num_黛安娜'},
 '奥瑞利安·索尔': {'name': '奥瑞利安·索尔',
             'jobs': ['魔法师'],
             'races': ['龙魂'],
             'price': '4',
             'gui_name': '4-奥瑞利安·索尔',
             'gui_checkbox_key': 'checkbox_奥瑞利安·索尔',
             'gui_combo_num_key': 'combo_num_奥瑞利安·索尔'},
 '亚索': {'name': '亚索',
        'jobs': ['决斗大师'],
        'races': ['浪人'],
        'price': '1',
        'gui_name': '1-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '布隆': {'name': '布隆',
        'jobs': ['重装战士'],
        'races': ['龙魂'],
        'price': '2',
        'gui_name': '2-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '千珏': {'name': '千珏',
        'jobs': ['裁决使'],
        'races': ['灵魂莲华明昼'],
        'price': '3',
        'gui_name': '3-千珏',
        'gui_checkbox_key': 'checkbox_千珏',
        'gui_combo_num_key': 'combo_num_千珏'},
 '塔姆': {'name': '塔姆',
        'jobs': ['斗士'],
        'races': ['福星'],
        'price': '1',
        'gui_name': '1-塔姆',
        'gui_checkbox_key': 'checkbox_塔姆',
        'gui_combo_num_key': 'combo_num_塔姆'},
 '劫': {'name': '劫',
       'jobs': ['战神'],
       'races': ['忍者'],
       'price': '2',
       'gui_name': '2-劫',
       'gui_checkbox_key': 'checkbox_劫',
       'gui_combo_num_key': 'combo_num_劫'},
 '蔚': {'name': '蔚',
       'jobs': ['斗士'],
       'races': ['三国猛将'],
       'price': '2',
       'gui_name': '2-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['重装战士'],
          'races': ['腥红之月'],
          'price': '4',
          'gui_name': '4-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '阿兹尔': {'name': '阿兹尔',
         'jobs': ['神盾使', '枭雄'],
         'races': ['三国猛将'],
         'price': '5',
         'gui_name': '5-阿兹尔',
         'gui_checkbox_key': 'checkbox_阿兹尔',
         'gui_combo_num_key': 'combo_num_阿兹尔'},
 '悠米': {'name': '悠米',
        'jobs': ['秘术师'],
        'races': ['灵魂莲华明昼'],
        'price': '3',
        'gui_name': '3-悠米',
        'gui_checkbox_key': 'checkbox_悠米',
        'gui_combo_num_key': 'combo_num_悠米'},
 '莎弥拉': {'name': '莎弥拉',
         'jobs': ['神射手', '战神'],
         'races': ['主宰'],
         'price': '5',
         'gui_name': '5-莎弥拉',
         'gui_checkbox_key': 'checkbox_莎弥拉',
         'gui_combo_num_key': 'combo_num_莎弥拉'},
 '卡莉丝塔': {'name': '卡莉丝塔',
          'jobs': ['决斗大师'],
          'races': ['腥红之月'],
          'price': '3',
          'gui_name': '3-卡莉丝塔',
          'gui_checkbox_key': 'checkbox_卡莉丝塔',
          'gui_combo_num_key': 'combo_num_卡莉丝塔'},
 '洛': {'name': '洛',
       'jobs': ['神盾使'],
       'races': ['永恒之森'],
       'price': '2',
       'gui_name': '2-洛',
       'gui_checkbox_key': 'checkbox_洛',
       'gui_combo_num_key': 'combo_num_洛'},
 '霞': {'name': '霞',
       'jobs': ['神盾使', '裁决使'],
       'races': ['永恒之森'],
       'price': '4',
       'gui_name': '4-霞',
       'gui_checkbox_key': 'checkbox_霞',
       'gui_combo_num_key': 'combo_num_霞'},
 '奥恩': {'name': '奥恩',
        'jobs': ['重装战士', '铁匠'],
        'races': ['永恒之森'],
        'price': '5',
        'gui_name': '5-奥恩',
        'gui_checkbox_key': 'checkbox_奥恩',
        'gui_combo_num_key': 'combo_num_奥恩'},
 '妮蔻': {'name': '妮蔻',
        'jobs': ['秘术师'],
        'races': ['山海绘卷'],
        'price': '3',
        'gui_name': '3-妮蔻',
        'gui_checkbox_key': 'checkbox_妮蔻',
        'gui_combo_num_key': 'combo_num_妮蔻'},
 '派克': {'name': '派克',
        'jobs': ['刺客', '战神'],
        'races': ['腥红之月'],
        'price': '2',
        'gui_name': '2-派克',
        'gui_checkbox_key': 'checkbox_派克',
        'gui_combo_num_key': 'combo_num_派克'},
 '永恩': {'name': '永恩',
        'jobs': ['宗师'],
        'races': ['浪人'],
        'price': '5',
        'gui_name': '5-永恩',
        'gui_checkbox_key': 'checkbox_永恩',
        'gui_combo_num_key': 'combo_num_永恩'},
 '瑟提': {'name': '瑟提',
        'jobs': ['斗士'],
        'races': ['霸王'],
        'price': '5',
        'gui_name': '5-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'}}
