"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's3-银河战争',
 '版本信息': '10.6',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '10.6-2020.S3',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.6-2020.S3/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.6-2020.S3/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.6-2020.S3/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.6-2020.S3/equip.js',
 'url_hex_data': None,
 '强化符文说明': '该赛季尚未引入强化符文系统'}

    all_chess_name_str = '安妮-崔斯特-赵信-凯尔-易-索拉卡-厄运小姐-艾希-科加斯-萨科-娑娜-卡萨丁-艾瑞莉娅-普朗克-卡尔玛-凯特琳-布里茨-墨菲特-嘉文四世-齐天大圣-兰博-波比-伊泽瑞尔-莫德凯撒-蕾欧娜-慎-拉克丝-阿狸-格雷福斯-菲兹-菲奥娜-吉格斯-璐璐-卡兹克-德莱厄斯-杰斯-辛德拉-奥瑞利安·索尔-佐伊-卡莎-亚索-维克兹-烬-金克丝-卢锡安-艾克-蔚-锤石-洛-霞-妮蔻'

    all_race_name_str = '星之守护者-银河魔装机神-星神-奥德赛-未来战士-虚空-太空海盗-源计划-暗星-女武神'

    all_job_name_str = '剑士-爆破专家-刺客-斗士-法师-圣盾使-狙神-秘术师-破法战士-强袭枪手-星舰龙神-佣兵-重装战士'

    race_chess = {'星之守护者': ['索拉卡', '波比', '阿狸', '辛德拉', '佐伊', '妮蔻'],
 '银河魔装机神': ['安妮', '兰博', '菲兹'],
 '星神': ['赵信', '艾希', '卡萨丁', '璐璐', '洛', '霞'],
 '奥德赛': ['易', '娑娜', '墨菲特', '吉格斯', '奥瑞利安·索尔', '亚索', '金克丝'],
 '未来战士': ['崔斯特', '凯特琳', '布里茨', '齐天大圣', '伊泽瑞尔', '慎', '锤石'],
 '虚空': ['科加斯', '卡兹克', '维克兹'],
 '太空海盗': ['普朗克', '格雷福斯', '德莱厄斯', '杰斯'],
 '源计划': ['艾瑞莉娅', '蕾欧娜', '菲奥娜', '卢锡安', '艾克', '蔚'],
 '暗星': ['萨科', '卡尔玛', '嘉文四世', '莫德凯撒', '拉克丝', '烬'],
 '女武神': ['凯尔', '厄运小姐', '卡莎']}

    job_chess = {'剑士': ['凯尔', '易', '艾瑞莉娅', '慎', '菲奥娜', '亚索', '霞'],
 '爆破专家': ['普朗克', '兰博', '吉格斯'],
 '刺客': ['萨科', '菲兹', '卡兹克', '卡莎', '艾克'],
 '斗士': ['科加斯', '布里茨', '墨菲特', '蔚'],
 '法师': ['安妮', '崔斯特', '拉克丝', '阿狸', '辛德拉', '佐伊', '维克兹'],
 '圣盾使': ['赵信', '嘉文四世', '洛', '妮蔻'],
 '狙神': ['艾希', '凯特琳', '烬'],
 '秘术师': ['索拉卡', '娑娜', '卡尔玛', '璐璐'],
 '破法战士': ['卡萨丁', '艾瑞莉娅', '德莱厄斯', '锤石'],
 '强袭枪手': ['厄运小姐', '伊泽瑞尔', '格雷福斯', '金克丝', '卢锡安'],
 '星舰龙神': ['奥瑞利安·索尔'],
 '佣兵': ['厄运小姐', '普朗克'],
 '重装战士': ['齐天大圣', '波比', '莫德凯撒', '蕾欧娜', '杰斯']}

    price_chess = {'1': ['崔斯特', '凯特琳', '墨菲特', '嘉文四世', '波比', '蕾欧娜', '格雷福斯', '菲奥娜', '吉格斯', '卡兹克', '佐伊', '霞'],
 '2': ['安妮', '赵信', '娑娜', '布里茨', '莫德凯撒', '慎', '阿狸', '德莱厄斯', '卡莎', '亚索', '卢锡安', '洛'],
 '3': ['易', '艾希', '萨科', '卡萨丁', '卡尔玛', '兰博', '伊泽瑞尔', '拉克丝', '杰斯', '辛德拉', '蔚', '妮蔻'],
 '4': ['凯尔', '索拉卡', '科加斯', '艾瑞莉娅', '齐天大圣', '菲兹', '维克兹', '烬', '金克丝'],
 '5': ['厄运小姐', '普朗克', '璐璐', '奥瑞利安·索尔', '艾克', '锤石']}

    chess_name_info = {'安妮': {'name': '安妮',
        'jobs': ['法师'],
        'races': ['银河魔装机神'],
        'price': '2',
        'gui_name': '2-安妮',
        'gui_checkbox_key': 'checkbox_安妮',
        'gui_combo_num_key': 'combo_num_安妮'},
 '崔斯特': {'name': '崔斯特',
         'jobs': ['法师'],
         'races': ['未来战士'],
         'price': '1',
         'gui_name': '1-崔斯特',
         'gui_checkbox_key': 'checkbox_崔斯特',
         'gui_combo_num_key': 'combo_num_崔斯特'},
 '赵信': {'name': '赵信',
        'jobs': ['圣盾使'],
        'races': ['星神'],
        'price': '2',
        'gui_name': '2-赵信',
        'gui_checkbox_key': 'checkbox_赵信',
        'gui_combo_num_key': 'combo_num_赵信'},
 '凯尔': {'name': '凯尔',
        'jobs': ['剑士'],
        'races': ['女武神'],
        'price': '4',
        'gui_name': '4-凯尔',
        'gui_checkbox_key': 'checkbox_凯尔',
        'gui_combo_num_key': 'combo_num_凯尔'},
 '易': {'name': '易',
       'jobs': ['剑士'],
       'races': ['奥德赛'],
       'price': '3',
       'gui_name': '3-易',
       'gui_checkbox_key': 'checkbox_易',
       'gui_combo_num_key': 'combo_num_易'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['秘术师'],
         'races': ['星之守护者'],
         'price': '4',
         'gui_name': '4-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '厄运小姐': {'name': '厄运小姐',
          'jobs': ['强袭枪手', '佣兵'],
          'races': ['女武神'],
          'price': '5',
          'gui_name': '5-厄运小姐',
          'gui_checkbox_key': 'checkbox_厄运小姐',
          'gui_combo_num_key': 'combo_num_厄运小姐'},
 '艾希': {'name': '艾希',
        'jobs': ['狙神'],
        'races': ['星神'],
        'price': '3',
        'gui_name': '3-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '科加斯': {'name': '科加斯',
         'jobs': ['斗士'],
         'races': ['虚空'],
         'price': '4',
         'gui_name': '4-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '萨科': {'name': '萨科',
        'jobs': ['刺客'],
        'races': ['暗星'],
        'price': '3',
        'gui_name': '3-萨科',
        'gui_checkbox_key': 'checkbox_萨科',
        'gui_combo_num_key': 'combo_num_萨科'},
 '娑娜': {'name': '娑娜',
        'jobs': ['秘术师'],
        'races': ['奥德赛'],
        'price': '2',
        'gui_name': '2-娑娜',
        'gui_checkbox_key': 'checkbox_娑娜',
        'gui_combo_num_key': 'combo_num_娑娜'},
 '卡萨丁': {'name': '卡萨丁',
         'jobs': ['破法战士'],
         'races': ['星神'],
         'price': '3',
         'gui_name': '3-卡萨丁',
         'gui_checkbox_key': 'checkbox_卡萨丁',
         'gui_combo_num_key': 'combo_num_卡萨丁'},
 '艾瑞莉娅': {'name': '艾瑞莉娅',
          'jobs': ['剑士', '破法战士'],
          'races': ['源计划'],
          'price': '4',
          'gui_name': '4-艾瑞莉娅',
          'gui_checkbox_key': 'checkbox_艾瑞莉娅',
          'gui_combo_num_key': 'combo_num_艾瑞莉娅'},
 '普朗克': {'name': '普朗克',
         'jobs': ['爆破专家', '佣兵'],
         'races': ['太空海盗'],
         'price': '5',
         'gui_name': '5-普朗克',
         'gui_checkbox_key': 'checkbox_普朗克',
         'gui_combo_num_key': 'combo_num_普朗克'},
 '卡尔玛': {'name': '卡尔玛',
         'jobs': ['秘术师'],
         'races': ['暗星'],
         'price': '3',
         'gui_name': '3-卡尔玛',
         'gui_checkbox_key': 'checkbox_卡尔玛',
         'gui_combo_num_key': 'combo_num_卡尔玛'},
 '凯特琳': {'name': '凯特琳',
         'jobs': ['狙神'],
         'races': ['未来战士'],
         'price': '1',
         'gui_name': '1-凯特琳',
         'gui_checkbox_key': 'checkbox_凯特琳',
         'gui_combo_num_key': 'combo_num_凯特琳'},
 '布里茨': {'name': '布里茨',
         'jobs': ['斗士'],
         'races': ['未来战士'],
         'price': '2',
         'gui_name': '2-布里茨',
         'gui_checkbox_key': 'checkbox_布里茨',
         'gui_combo_num_key': 'combo_num_布里茨'},
 '墨菲特': {'name': '墨菲特',
         'jobs': ['斗士'],
         'races': ['奥德赛'],
         'price': '1',
         'gui_name': '1-墨菲特',
         'gui_checkbox_key': 'checkbox_墨菲特',
         'gui_combo_num_key': 'combo_num_墨菲特'},
 '嘉文四世': {'name': '嘉文四世',
          'jobs': ['圣盾使'],
          'races': ['暗星'],
          'price': '1',
          'gui_name': '1-嘉文四世',
          'gui_checkbox_key': 'checkbox_嘉文四世',
          'gui_combo_num_key': 'combo_num_嘉文四世'},
 '齐天大圣': {'name': '齐天大圣',
          'jobs': ['重装战士'],
          'races': ['未来战士'],
          'price': '4',
          'gui_name': '4-齐天大圣',
          'gui_checkbox_key': 'checkbox_齐天大圣',
          'gui_combo_num_key': 'combo_num_齐天大圣'},
 '兰博': {'name': '兰博',
        'jobs': ['爆破专家'],
        'races': ['银河魔装机神'],
        'price': '3',
        'gui_name': '3-兰博',
        'gui_checkbox_key': 'checkbox_兰博',
        'gui_combo_num_key': 'combo_num_兰博'},
 '波比': {'name': '波比',
        'jobs': ['重装战士'],
        'races': ['星之守护者'],
        'price': '1',
        'gui_name': '1-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['强袭枪手'],
          'races': ['未来战士'],
          'price': '3',
          'gui_name': '3-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '莫德凯撒': {'name': '莫德凯撒',
          'jobs': ['重装战士'],
          'races': ['暗星'],
          'price': '2',
          'gui_name': '2-莫德凯撒',
          'gui_checkbox_key': 'checkbox_莫德凯撒',
          'gui_combo_num_key': 'combo_num_莫德凯撒'},
 '蕾欧娜': {'name': '蕾欧娜',
         'jobs': ['重装战士'],
         'races': ['源计划'],
         'price': '1',
         'gui_name': '1-蕾欧娜',
         'gui_checkbox_key': 'checkbox_蕾欧娜',
         'gui_combo_num_key': 'combo_num_蕾欧娜'},
 '慎': {'name': '慎',
       'jobs': ['剑士'],
       'races': ['未来战士'],
       'price': '2',
       'gui_name': '2-慎',
       'gui_checkbox_key': 'checkbox_慎',
       'gui_combo_num_key': 'combo_num_慎'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['法师'],
         'races': ['暗星'],
         'price': '3',
         'gui_name': '3-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '阿狸': {'name': '阿狸',
        'jobs': ['法师'],
        'races': ['星之守护者'],
        'price': '2',
        'gui_name': '2-阿狸',
        'gui_checkbox_key': 'checkbox_阿狸',
        'gui_combo_num_key': 'combo_num_阿狸'},
 '格雷福斯': {'name': '格雷福斯',
          'jobs': ['强袭枪手'],
          'races': ['太空海盗'],
          'price': '1',
          'gui_name': '1-格雷福斯',
          'gui_checkbox_key': 'checkbox_格雷福斯',
          'gui_combo_num_key': 'combo_num_格雷福斯'},
 '菲兹': {'name': '菲兹',
        'jobs': ['刺客'],
        'races': ['银河魔装机神'],
        'price': '4',
        'gui_name': '4-菲兹',
        'gui_checkbox_key': 'checkbox_菲兹',
        'gui_combo_num_key': 'combo_num_菲兹'},
 '菲奥娜': {'name': '菲奥娜',
         'jobs': ['剑士'],
         'races': ['源计划'],
         'price': '1',
         'gui_name': '1-菲奥娜',
         'gui_checkbox_key': 'checkbox_菲奥娜',
         'gui_combo_num_key': 'combo_num_菲奥娜'},
 '吉格斯': {'name': '吉格斯',
         'jobs': ['爆破专家'],
         'races': ['奥德赛'],
         'price': '1',
         'gui_name': '1-吉格斯',
         'gui_checkbox_key': 'checkbox_吉格斯',
         'gui_combo_num_key': 'combo_num_吉格斯'},
 '璐璐': {'name': '璐璐',
        'jobs': ['秘术师'],
        'races': ['星神'],
        'price': '5',
        'gui_name': '5-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '卡兹克': {'name': '卡兹克',
         'jobs': ['刺客'],
         'races': ['虚空'],
         'price': '1',
         'gui_name': '1-卡兹克',
         'gui_checkbox_key': 'checkbox_卡兹克',
         'gui_combo_num_key': 'combo_num_卡兹克'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['破法战士'],
          'races': ['太空海盗'],
          'price': '2',
          'gui_name': '2-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '杰斯': {'name': '杰斯',
        'jobs': ['重装战士'],
        'races': ['太空海盗'],
        'price': '3',
        'gui_name': '3-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '辛德拉': {'name': '辛德拉',
         'jobs': ['法师'],
         'races': ['星之守护者'],
         'price': '3',
         'gui_name': '3-辛德拉',
         'gui_checkbox_key': 'checkbox_辛德拉',
         'gui_combo_num_key': 'combo_num_辛德拉'},
 '奥瑞利安·索尔': {'name': '奥瑞利安·索尔',
             'jobs': ['星舰龙神'],
             'races': ['奥德赛'],
             'price': '5',
             'gui_name': '5-奥瑞利安·索尔',
             'gui_checkbox_key': 'checkbox_奥瑞利安·索尔',
             'gui_combo_num_key': 'combo_num_奥瑞利安·索尔'},
 '佐伊': {'name': '佐伊',
        'jobs': ['法师'],
        'races': ['星之守护者'],
        'price': '1',
        'gui_name': '1-佐伊',
        'gui_checkbox_key': 'checkbox_佐伊',
        'gui_combo_num_key': 'combo_num_佐伊'},
 '卡莎': {'name': '卡莎',
        'jobs': ['刺客'],
        'races': ['女武神'],
        'price': '2',
        'gui_name': '2-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'},
 '亚索': {'name': '亚索',
        'jobs': ['剑士'],
        'races': ['奥德赛'],
        'price': '2',
        'gui_name': '2-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '维克兹': {'name': '维克兹',
         'jobs': ['法师'],
         'races': ['虚空'],
         'price': '4',
         'gui_name': '4-维克兹',
         'gui_checkbox_key': 'checkbox_维克兹',
         'gui_combo_num_key': 'combo_num_维克兹'},
 '烬': {'name': '烬',
       'jobs': ['狙神'],
       'races': ['暗星'],
       'price': '4',
       'gui_name': '4-烬',
       'gui_checkbox_key': 'checkbox_烬',
       'gui_combo_num_key': 'combo_num_烬'},
 '金克丝': {'name': '金克丝',
         'jobs': ['强袭枪手'],
         'races': ['奥德赛'],
         'price': '4',
         'gui_name': '4-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '卢锡安': {'name': '卢锡安',
         'jobs': ['强袭枪手'],
         'races': ['源计划'],
         'price': '2',
         'gui_name': '2-卢锡安',
         'gui_checkbox_key': 'checkbox_卢锡安',
         'gui_combo_num_key': 'combo_num_卢锡安'},
 '艾克': {'name': '艾克',
        'jobs': ['刺客'],
        'races': ['源计划'],
        'price': '5',
        'gui_name': '5-艾克',
        'gui_checkbox_key': 'checkbox_艾克',
        'gui_combo_num_key': 'combo_num_艾克'},
 '蔚': {'name': '蔚',
       'jobs': ['斗士'],
       'races': ['源计划'],
       'price': '3',
       'gui_name': '3-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '锤石': {'name': '锤石',
        'jobs': ['破法战士'],
        'races': ['未来战士'],
        'price': '5',
        'gui_name': '5-锤石',
        'gui_checkbox_key': 'checkbox_锤石',
        'gui_combo_num_key': 'combo_num_锤石'},
 '洛': {'name': '洛',
       'jobs': ['圣盾使'],
       'races': ['星神'],
       'price': '2',
       'gui_name': '2-洛',
       'gui_checkbox_key': 'checkbox_洛',
       'gui_combo_num_key': 'combo_num_洛'},
 '霞': {'name': '霞',
       'jobs': ['剑士'],
       'races': ['星神'],
       'price': '1',
       'gui_name': '1-霞',
       'gui_checkbox_key': 'checkbox_霞',
       'gui_combo_num_key': 'combo_num_霞'},
 '妮蔻': {'name': '妮蔻',
        'jobs': ['圣盾使'],
        'races': ['星之守护者'],
        'price': '3',
        'gui_name': '3-妮蔻',
        'gui_checkbox_key': 'checkbox_妮蔻',
        'gui_combo_num_key': 'combo_num_妮蔻'}}
