"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's9-符文大陆传奇',
 '版本信息': '13.12',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '13.12-2023.S9',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.12-2023.S9/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.12-2023.S9/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.12-2023.S9/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.12-2023.S9/equip.js',
 'url_hex_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.12-2023.S9/hex.js'}

    all_chess_name_str = '加里奥-厄加特-凯尔-瑞兹-赛恩-索拉卡-提莫-崔丝塔娜-沃里克-艾希-科加斯-娑娜-卡萨丁-艾瑞莉娅-卡尔玛-塔里克-斯维因-卡特琳娜-茂凯-雷克顿-嘉文四世-奥莉安娜-卡西奥佩娅-黑默丁格-内瑟斯-波比-盖伦-玛尔扎哈-慎-拉克丝-阿狸-瑟庄妮-德莱厄斯-杰斯-丽桑卓-卡莎-亚索-维克兹-塔莉垭-阿克尚-卑尔维斯-烬-泽丽-金克丝-佛耶戈-赛娜-劫-克烈-艾克-蔚-亚托克斯-阿兹尔-莎弥拉-雷克塞-卡莉丝塔-厄斐琉斯-瑟提-格温-奎桑提-瑞兹-班德尔城-瑞兹-德玛西亚-瑞兹-弗雷尔卓德-瑞兹-艾欧尼亚-瑞兹-诺克萨斯-瑞兹-皮尔特沃夫-瑞兹-暗影岛-瑞兹-恕瑞玛-瑞兹-巨神峰-瑞兹-祖安-尖端炮台-海克斯霸龙-虚空鱼-峡谷先锋-纳什男爵'

    all_race_name_str = '暗裔-德玛西亚-弗雷尔卓德-艾欧尼亚-诺克萨斯-皮尔特沃夫-涤魂圣枪-暗影岛-恕瑞玛-巨神峰-虚空-约德尔人-祖安'

    all_job_name_str = '堡垒卫士-格斗家-挑战者-亡眼射手-女皇-枪手-神谕者-主宰-术士-潜行者-裁决战士-法师-司令-大发明家-流浪法师-召唤物'

    race_chess = {'暗裔': ['亚托克斯'],
 '德玛西亚': ['加里奥', '凯尔', '娑娜', '嘉文四世', '波比', '盖伦', '拉克丝'],
 '弗雷尔卓德': ['艾希', '瑟庄妮', '丽桑卓'],
 '艾欧尼亚': ['艾瑞莉娅', '卡尔玛', '慎', '阿狸', '亚索', '烬', '劫', '瑟提'],
 '诺克萨斯': ['赛恩', '斯维因', '卡特琳娜', '卡西奥佩娅', '德莱厄斯', '克烈', '莎弥拉'],
 '皮尔特沃夫': ['奥莉安娜', '黑默丁格', '杰斯', '艾克', '蔚'],
 '涤魂圣枪': ['赛娜'],
 '暗影岛': ['茂凯', '佛耶戈', '赛娜', '卡莉丝塔', '格温'],
 '恕瑞玛': ['雷克顿', '卡西奥佩娅', '内瑟斯', '塔莉垭', '阿克尚', '阿兹尔', '奎桑提'],
 '巨神峰': ['索拉卡', '塔里克', '厄斐琉斯'],
 '虚空': ['科加斯', '卡萨丁', '玛尔扎哈', '卡莎', '维克兹', '卑尔维斯', '雷克塞'],
 '约德尔人': ['提莫', '崔丝塔娜', '黑默丁格', '波比', '克烈'],
 '祖安': ['厄加特', '沃里克', '泽丽', '金克丝', '艾克']}

    job_chess = {'堡垒卫士': ['卡萨丁', '塔里克', '茂凯', '波比', '慎', '奎桑提'],
 '格斗家': ['赛恩', '科加斯', '雷克顿', '瑟庄妮', '蔚', '雷克塞'],
 '挑战者': ['沃里克', '艾瑞莉娅', '卡莎', '亚索', '莎弥拉', '卡莉丝塔'],
 '亡眼射手': ['厄加特', '艾希', '阿克尚', '烬', '厄斐琉斯'],
 '女皇': ['卑尔维斯'],
 '枪手': ['崔丝塔娜', '杰斯', '泽丽', '金克丝', '赛娜'],
 '神谕者': ['加里奥',
         '瑞兹',
         '索拉卡',
         '卡尔玛',
         '卡西奥佩娅',
         '慎',
         '丽桑卓',
         '瑞兹-班德尔城',
         '瑞兹-德玛西亚',
         '瑞兹-弗雷尔卓德',
         '瑞兹-艾欧尼亚',
         '瑞兹-诺克萨斯',
         '瑞兹-皮尔特沃夫',
         '瑞兹-暗影岛',
         '瑞兹-恕瑞玛',
         '瑞兹-巨神峰',
         '瑞兹-祖安'],
 '主宰': ['沃里克', '内瑟斯', '盖伦', '德莱厄斯', '亚托克斯', '瑟提'],
 '术士': ['提莫', '娑娜', '维克兹', '塔莉垭'],
 '潜行者': ['卡特琳娜', '佛耶戈', '劫', '艾克'],
 '裁决战士': ['凯尔', '劫', '克烈', '亚托克斯', '格温'],
 '法师': ['塔里克', '斯维因', '奥莉安娜', '玛尔扎哈', '拉克丝', '阿狸', '维克兹'],
 '司令': ['提莫', '斯维因', '嘉文四世', '阿兹尔'],
 '大发明家': ['黑默丁格'],
 '流浪法师': ['瑞兹',
          '瑞兹-班德尔城',
          '瑞兹-德玛西亚',
          '瑞兹-弗雷尔卓德',
          '瑞兹-艾欧尼亚',
          '瑞兹-诺克萨斯',
          '瑞兹-皮尔特沃夫',
          '瑞兹-暗影岛',
          '瑞兹-恕瑞玛',
          '瑞兹-巨神峰',
          '瑞兹-祖安'],
 '召唤物': ['尖端炮台', '海克斯霸龙', '虚空鱼', '峡谷先锋', '纳什男爵']}

    price_chess = {'0': ['尖端炮台', '海克斯霸龙', '虚空鱼', '峡谷先锋', '纳什男爵'],
 '1': ['凯尔', '崔丝塔娜', '科加斯', '艾瑞莉娅', '茂凯', '雷克顿', '奥莉安娜', '卡西奥佩娅', '波比', '玛尔扎哈', '烬', '佛耶戈', '莎弥拉'],
 '2': ['加里奥', '索拉卡', '提莫', '沃里克', '艾希', '卡萨丁', '斯维因', '塔莉垭', '金克丝', '劫', '克烈', '蔚', '瑟提'],
 '3': ['娑娜', '卡尔玛', '塔里克', '卡特琳娜', '盖伦', '德莱厄斯', '杰斯', '丽桑卓', '维克兹', '阿克尚', '艾克', '雷克塞', '卡莉丝塔'],
 '4': ['厄加特', '嘉文四世', '内瑟斯', '慎', '拉克丝', '瑟庄妮', '卡莎', '亚索', '泽丽', '阿兹尔', '厄斐琉斯', '格温'],
 '5': ['瑞兹',
       '赛恩',
       '黑默丁格',
       '阿狸',
       '卑尔维斯',
       '赛娜',
       '亚托克斯',
       '奎桑提',
       '瑞兹-班德尔城',
       '瑞兹-德玛西亚',
       '瑞兹-弗雷尔卓德',
       '瑞兹-艾欧尼亚',
       '瑞兹-诺克萨斯',
       '瑞兹-皮尔特沃夫',
       '瑞兹-暗影岛',
       '瑞兹-恕瑞玛',
       '瑞兹-巨神峰',
       '瑞兹-祖安']}

    chess_name_info = {'加里奥': {'name': '加里奥',
         'jobs': ['神谕者'],
         'races': ['德玛西亚'],
         'price': '2',
         'gui_name': '2-加里奥',
         'gui_checkbox_key': 'checkbox_加里奥',
         'gui_combo_num_key': 'combo_num_加里奥'},
 '厄加特': {'name': '厄加特',
         'jobs': ['亡眼射手'],
         'races': ['祖安'],
         'price': '4',
         'gui_name': '4-厄加特',
         'gui_checkbox_key': 'checkbox_厄加特',
         'gui_combo_num_key': 'combo_num_厄加特'},
 '凯尔': {'name': '凯尔',
        'jobs': ['裁决战士'],
        'races': ['德玛西亚'],
        'price': '1',
        'gui_name': '1-凯尔',
        'gui_checkbox_key': 'checkbox_凯尔',
        'gui_combo_num_key': 'combo_num_凯尔'},
 '瑞兹': {'name': '瑞兹',
        'jobs': ['神谕者', '流浪法师'],
        'races': [],
        'price': '5',
        'gui_name': '5-瑞兹',
        'gui_checkbox_key': 'checkbox_瑞兹',
        'gui_combo_num_key': 'combo_num_瑞兹'},
 '赛恩': {'name': '赛恩',
        'jobs': ['格斗家'],
        'races': ['诺克萨斯'],
        'price': '5',
        'gui_name': '5-赛恩',
        'gui_checkbox_key': 'checkbox_赛恩',
        'gui_combo_num_key': 'combo_num_赛恩'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['神谕者'],
         'races': ['巨神峰'],
         'price': '2',
         'gui_name': '2-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '提莫': {'name': '提莫',
        'jobs': ['术士', '司令'],
        'races': ['约德尔人'],
        'price': '2',
        'gui_name': '2-提莫',
        'gui_checkbox_key': 'checkbox_提莫',
        'gui_combo_num_key': 'combo_num_提莫'},
 '崔丝塔娜': {'name': '崔丝塔娜',
          'jobs': ['枪手'],
          'races': ['约德尔人'],
          'price': '1',
          'gui_name': '1-崔丝塔娜',
          'gui_checkbox_key': 'checkbox_崔丝塔娜',
          'gui_combo_num_key': 'combo_num_崔丝塔娜'},
 '沃里克': {'name': '沃里克',
         'jobs': ['挑战者', '主宰'],
         'races': ['祖安'],
         'price': '2',
         'gui_name': '2-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '艾希': {'name': '艾希',
        'jobs': ['亡眼射手'],
        'races': ['弗雷尔卓德'],
        'price': '2',
        'gui_name': '2-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '科加斯': {'name': '科加斯',
         'jobs': ['格斗家'],
         'races': ['虚空'],
         'price': '1',
         'gui_name': '1-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '娑娜': {'name': '娑娜',
        'jobs': ['术士'],
        'races': ['德玛西亚'],
        'price': '3',
        'gui_name': '3-娑娜',
        'gui_checkbox_key': 'checkbox_娑娜',
        'gui_combo_num_key': 'combo_num_娑娜'},
 '卡萨丁': {'name': '卡萨丁',
         'jobs': ['堡垒卫士'],
         'races': ['虚空'],
         'price': '2',
         'gui_name': '2-卡萨丁',
         'gui_checkbox_key': 'checkbox_卡萨丁',
         'gui_combo_num_key': 'combo_num_卡萨丁'},
 '艾瑞莉娅': {'name': '艾瑞莉娅',
          'jobs': ['挑战者'],
          'races': ['艾欧尼亚'],
          'price': '1',
          'gui_name': '1-艾瑞莉娅',
          'gui_checkbox_key': 'checkbox_艾瑞莉娅',
          'gui_combo_num_key': 'combo_num_艾瑞莉娅'},
 '卡尔玛': {'name': '卡尔玛',
         'jobs': ['神谕者'],
         'races': ['艾欧尼亚'],
         'price': '3',
         'gui_name': '3-卡尔玛',
         'gui_checkbox_key': 'checkbox_卡尔玛',
         'gui_combo_num_key': 'combo_num_卡尔玛'},
 '塔里克': {'name': '塔里克',
         'jobs': ['堡垒卫士', '法师'],
         'races': ['巨神峰'],
         'price': '3',
         'gui_name': '3-塔里克',
         'gui_checkbox_key': 'checkbox_塔里克',
         'gui_combo_num_key': 'combo_num_塔里克'},
 '斯维因': {'name': '斯维因',
         'jobs': ['法师', '司令'],
         'races': ['诺克萨斯'],
         'price': '2',
         'gui_name': '2-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['潜行者'],
          'races': ['诺克萨斯'],
          'price': '3',
          'gui_name': '3-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '茂凯': {'name': '茂凯',
        'jobs': ['堡垒卫士'],
        'races': ['暗影岛'],
        'price': '1',
        'gui_name': '1-茂凯',
        'gui_checkbox_key': 'checkbox_茂凯',
        'gui_combo_num_key': 'combo_num_茂凯'},
 '雷克顿': {'name': '雷克顿',
         'jobs': ['格斗家'],
         'races': ['恕瑞玛'],
         'price': '1',
         'gui_name': '1-雷克顿',
         'gui_checkbox_key': 'checkbox_雷克顿',
         'gui_combo_num_key': 'combo_num_雷克顿'},
 '嘉文四世': {'name': '嘉文四世',
          'jobs': ['司令'],
          'races': ['德玛西亚'],
          'price': '4',
          'gui_name': '4-嘉文四世',
          'gui_checkbox_key': 'checkbox_嘉文四世',
          'gui_combo_num_key': 'combo_num_嘉文四世'},
 '奥莉安娜': {'name': '奥莉安娜',
          'jobs': ['法师'],
          'races': ['皮尔特沃夫'],
          'price': '1',
          'gui_name': '1-奥莉安娜',
          'gui_checkbox_key': 'checkbox_奥莉安娜',
          'gui_combo_num_key': 'combo_num_奥莉安娜'},
 '卡西奥佩娅': {'name': '卡西奥佩娅',
           'jobs': ['神谕者'],
           'races': ['诺克萨斯', '恕瑞玛'],
           'price': '1',
           'gui_name': '1-卡西奥佩娅',
           'gui_checkbox_key': 'checkbox_卡西奥佩娅',
           'gui_combo_num_key': 'combo_num_卡西奥佩娅'},
 '黑默丁格': {'name': '黑默丁格',
          'jobs': ['大发明家'],
          'races': ['皮尔特沃夫', '约德尔人'],
          'price': '5',
          'gui_name': '5-黑默丁格',
          'gui_checkbox_key': 'checkbox_黑默丁格',
          'gui_combo_num_key': 'combo_num_黑默丁格'},
 '内瑟斯': {'name': '内瑟斯',
         'jobs': ['主宰'],
         'races': ['恕瑞玛'],
         'price': '4',
         'gui_name': '4-内瑟斯',
         'gui_checkbox_key': 'checkbox_内瑟斯',
         'gui_combo_num_key': 'combo_num_内瑟斯'},
 '波比': {'name': '波比',
        'jobs': ['堡垒卫士'],
        'races': ['德玛西亚', '约德尔人'],
        'price': '1',
        'gui_name': '1-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '盖伦': {'name': '盖伦',
        'jobs': ['主宰'],
        'races': ['德玛西亚'],
        'price': '3',
        'gui_name': '3-盖伦',
        'gui_checkbox_key': 'checkbox_盖伦',
        'gui_combo_num_key': 'combo_num_盖伦'},
 '玛尔扎哈': {'name': '玛尔扎哈',
          'jobs': ['法师'],
          'races': ['虚空'],
          'price': '1',
          'gui_name': '1-玛尔扎哈',
          'gui_checkbox_key': 'checkbox_玛尔扎哈',
          'gui_combo_num_key': 'combo_num_玛尔扎哈'},
 '慎': {'name': '慎',
       'jobs': ['堡垒卫士', '神谕者'],
       'races': ['艾欧尼亚'],
       'price': '4',
       'gui_name': '4-慎',
       'gui_checkbox_key': 'checkbox_慎',
       'gui_combo_num_key': 'combo_num_慎'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['法师'],
         'races': ['德玛西亚'],
         'price': '4',
         'gui_name': '4-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '阿狸': {'name': '阿狸',
        'jobs': ['法师'],
        'races': ['艾欧尼亚'],
        'price': '5',
        'gui_name': '5-阿狸',
        'gui_checkbox_key': 'checkbox_阿狸',
        'gui_combo_num_key': 'combo_num_阿狸'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['格斗家'],
         'races': ['弗雷尔卓德'],
         'price': '4',
         'gui_name': '4-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['主宰'],
          'races': ['诺克萨斯'],
          'price': '3',
          'gui_name': '3-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '杰斯': {'name': '杰斯',
        'jobs': ['枪手'],
        'races': ['皮尔特沃夫'],
        'price': '3',
        'gui_name': '3-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '丽桑卓': {'name': '丽桑卓',
         'jobs': ['神谕者'],
         'races': ['弗雷尔卓德'],
         'price': '3',
         'gui_name': '3-丽桑卓',
         'gui_checkbox_key': 'checkbox_丽桑卓',
         'gui_combo_num_key': 'combo_num_丽桑卓'},
 '卡莎': {'name': '卡莎',
        'jobs': ['挑战者'],
        'races': ['虚空'],
        'price': '4',
        'gui_name': '4-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'},
 '亚索': {'name': '亚索',
        'jobs': ['挑战者'],
        'races': ['艾欧尼亚'],
        'price': '4',
        'gui_name': '4-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '维克兹': {'name': '维克兹',
         'jobs': ['术士', '法师'],
         'races': ['虚空'],
         'price': '3',
         'gui_name': '3-维克兹',
         'gui_checkbox_key': 'checkbox_维克兹',
         'gui_combo_num_key': 'combo_num_维克兹'},
 '塔莉垭': {'name': '塔莉垭',
         'jobs': ['术士'],
         'races': ['恕瑞玛'],
         'price': '2',
         'gui_name': '2-塔莉垭',
         'gui_checkbox_key': 'checkbox_塔莉垭',
         'gui_combo_num_key': 'combo_num_塔莉垭'},
 '阿克尚': {'name': '阿克尚',
         'jobs': ['亡眼射手'],
         'races': ['恕瑞玛'],
         'price': '3',
         'gui_name': '3-阿克尚',
         'gui_checkbox_key': 'checkbox_阿克尚',
         'gui_combo_num_key': 'combo_num_阿克尚'},
 '卑尔维斯': {'name': '卑尔维斯',
          'jobs': ['女皇'],
          'races': ['虚空'],
          'price': '5',
          'gui_name': '5-卑尔维斯',
          'gui_checkbox_key': 'checkbox_卑尔维斯',
          'gui_combo_num_key': 'combo_num_卑尔维斯'},
 '烬': {'name': '烬',
       'jobs': ['亡眼射手'],
       'races': ['艾欧尼亚'],
       'price': '1',
       'gui_name': '1-烬',
       'gui_checkbox_key': 'checkbox_烬',
       'gui_combo_num_key': 'combo_num_烬'},
 '泽丽': {'name': '泽丽',
        'jobs': ['枪手'],
        'races': ['祖安'],
        'price': '4',
        'gui_name': '4-泽丽',
        'gui_checkbox_key': 'checkbox_泽丽',
        'gui_combo_num_key': 'combo_num_泽丽'},
 '金克丝': {'name': '金克丝',
         'jobs': ['枪手'],
         'races': ['祖安'],
         'price': '2',
         'gui_name': '2-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '佛耶戈': {'name': '佛耶戈',
         'jobs': ['潜行者'],
         'races': ['暗影岛'],
         'price': '1',
         'gui_name': '1-佛耶戈',
         'gui_checkbox_key': 'checkbox_佛耶戈',
         'gui_combo_num_key': 'combo_num_佛耶戈'},
 '赛娜': {'name': '赛娜',
        'jobs': ['枪手'],
        'races': ['涤魂圣枪', '暗影岛'],
        'price': '5',
        'gui_name': '5-赛娜',
        'gui_checkbox_key': 'checkbox_赛娜',
        'gui_combo_num_key': 'combo_num_赛娜'},
 '劫': {'name': '劫',
       'jobs': ['潜行者', '裁决战士'],
       'races': ['艾欧尼亚'],
       'price': '2',
       'gui_name': '2-劫',
       'gui_checkbox_key': 'checkbox_劫',
       'gui_combo_num_key': 'combo_num_劫'},
 '克烈': {'name': '克烈',
        'jobs': ['裁决战士'],
        'races': ['诺克萨斯', '约德尔人'],
        'price': '2',
        'gui_name': '2-克烈',
        'gui_checkbox_key': 'checkbox_克烈',
        'gui_combo_num_key': 'combo_num_克烈'},
 '艾克': {'name': '艾克',
        'jobs': ['潜行者'],
        'races': ['皮尔特沃夫', '祖安'],
        'price': '3',
        'gui_name': '3-艾克',
        'gui_checkbox_key': 'checkbox_艾克',
        'gui_combo_num_key': 'combo_num_艾克'},
 '蔚': {'name': '蔚',
       'jobs': ['格斗家'],
       'races': ['皮尔特沃夫'],
       'price': '2',
       'gui_name': '2-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['主宰', '裁决战士'],
          'races': ['暗裔'],
          'price': '5',
          'gui_name': '5-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '阿兹尔': {'name': '阿兹尔',
         'jobs': ['司令'],
         'races': ['恕瑞玛'],
         'price': '4',
         'gui_name': '4-阿兹尔',
         'gui_checkbox_key': 'checkbox_阿兹尔',
         'gui_combo_num_key': 'combo_num_阿兹尔'},
 '莎弥拉': {'name': '莎弥拉',
         'jobs': ['挑战者'],
         'races': ['诺克萨斯'],
         'price': '1',
         'gui_name': '1-莎弥拉',
         'gui_checkbox_key': 'checkbox_莎弥拉',
         'gui_combo_num_key': 'combo_num_莎弥拉'},
 '雷克塞': {'name': '雷克塞',
         'jobs': ['格斗家'],
         'races': ['虚空'],
         'price': '3',
         'gui_name': '3-雷克塞',
         'gui_checkbox_key': 'checkbox_雷克塞',
         'gui_combo_num_key': 'combo_num_雷克塞'},
 '卡莉丝塔': {'name': '卡莉丝塔',
          'jobs': ['挑战者'],
          'races': ['暗影岛'],
          'price': '3',
          'gui_name': '3-卡莉丝塔',
          'gui_checkbox_key': 'checkbox_卡莉丝塔',
          'gui_combo_num_key': 'combo_num_卡莉丝塔'},
 '厄斐琉斯': {'name': '厄斐琉斯',
          'jobs': ['亡眼射手'],
          'races': ['巨神峰'],
          'price': '4',
          'gui_name': '4-厄斐琉斯',
          'gui_checkbox_key': 'checkbox_厄斐琉斯',
          'gui_combo_num_key': 'combo_num_厄斐琉斯'},
 '瑟提': {'name': '瑟提',
        'jobs': ['主宰'],
        'races': ['艾欧尼亚'],
        'price': '2',
        'gui_name': '2-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'},
 '格温': {'name': '格温',
        'jobs': ['裁决战士'],
        'races': ['暗影岛'],
        'price': '4',
        'gui_name': '4-格温',
        'gui_checkbox_key': 'checkbox_格温',
        'gui_combo_num_key': 'combo_num_格温'},
 '奎桑提': {'name': '奎桑提',
         'jobs': ['堡垒卫士'],
         'races': ['恕瑞玛'],
         'price': '5',
         'gui_name': '5-奎桑提',
         'gui_checkbox_key': 'checkbox_奎桑提',
         'gui_combo_num_key': 'combo_num_奎桑提'},
 '瑞兹-班德尔城': {'name': '瑞兹-班德尔城',
             'jobs': ['神谕者', '流浪法师'],
             'races': [],
             'price': '5',
             'gui_name': '5-瑞兹-班德尔城',
             'gui_checkbox_key': 'checkbox_瑞兹-班德尔城',
             'gui_combo_num_key': 'combo_num_瑞兹-班德尔城'},
 '瑞兹-德玛西亚': {'name': '瑞兹-德玛西亚',
             'jobs': ['神谕者', '流浪法师'],
             'races': [],
             'price': '5',
             'gui_name': '5-瑞兹-德玛西亚',
             'gui_checkbox_key': 'checkbox_瑞兹-德玛西亚',
             'gui_combo_num_key': 'combo_num_瑞兹-德玛西亚'},
 '瑞兹-弗雷尔卓德': {'name': '瑞兹-弗雷尔卓德',
              'jobs': ['神谕者', '流浪法师'],
              'races': [],
              'price': '5',
              'gui_name': '5-瑞兹-弗雷尔卓德',
              'gui_checkbox_key': 'checkbox_瑞兹-弗雷尔卓德',
              'gui_combo_num_key': 'combo_num_瑞兹-弗雷尔卓德'},
 '瑞兹-艾欧尼亚': {'name': '瑞兹-艾欧尼亚',
             'jobs': ['神谕者', '流浪法师'],
             'races': [],
             'price': '5',
             'gui_name': '5-瑞兹-艾欧尼亚',
             'gui_checkbox_key': 'checkbox_瑞兹-艾欧尼亚',
             'gui_combo_num_key': 'combo_num_瑞兹-艾欧尼亚'},
 '瑞兹-诺克萨斯': {'name': '瑞兹-诺克萨斯',
             'jobs': ['神谕者', '流浪法师'],
             'races': [],
             'price': '5',
             'gui_name': '5-瑞兹-诺克萨斯',
             'gui_checkbox_key': 'checkbox_瑞兹-诺克萨斯',
             'gui_combo_num_key': 'combo_num_瑞兹-诺克萨斯'},
 '瑞兹-皮尔特沃夫': {'name': '瑞兹-皮尔特沃夫',
              'jobs': ['神谕者', '流浪法师'],
              'races': [],
              'price': '5',
              'gui_name': '5-瑞兹-皮尔特沃夫',
              'gui_checkbox_key': 'checkbox_瑞兹-皮尔特沃夫',
              'gui_combo_num_key': 'combo_num_瑞兹-皮尔特沃夫'},
 '瑞兹-暗影岛': {'name': '瑞兹-暗影岛',
            'jobs': ['神谕者', '流浪法师'],
            'races': [],
            'price': '5',
            'gui_name': '5-瑞兹-暗影岛',
            'gui_checkbox_key': 'checkbox_瑞兹-暗影岛',
            'gui_combo_num_key': 'combo_num_瑞兹-暗影岛'},
 '瑞兹-恕瑞玛': {'name': '瑞兹-恕瑞玛',
            'jobs': ['神谕者', '流浪法师'],
            'races': [],
            'price': '5',
            'gui_name': '5-瑞兹-恕瑞玛',
            'gui_checkbox_key': 'checkbox_瑞兹-恕瑞玛',
            'gui_combo_num_key': 'combo_num_瑞兹-恕瑞玛'},
 '瑞兹-巨神峰': {'name': '瑞兹-巨神峰',
            'jobs': ['神谕者', '流浪法师'],
            'races': [],
            'price': '5',
            'gui_name': '5-瑞兹-巨神峰',
            'gui_checkbox_key': 'checkbox_瑞兹-巨神峰',
            'gui_combo_num_key': 'combo_num_瑞兹-巨神峰'},
 '瑞兹-祖安': {'name': '瑞兹-祖安',
           'jobs': ['神谕者', '流浪法师'],
           'races': [],
           'price': '5',
           'gui_name': '5-瑞兹-祖安',
           'gui_checkbox_key': 'checkbox_瑞兹-祖安',
           'gui_combo_num_key': 'combo_num_瑞兹-祖安'},
 '尖端炮台': {'name': '尖端炮台',
          'jobs': ['召唤物'],
          'races': [],
          'price': '0',
          'gui_name': '0-尖端炮台',
          'gui_checkbox_key': 'checkbox_尖端炮台',
          'gui_combo_num_key': 'combo_num_尖端炮台'},
 '海克斯霸龙': {'name': '海克斯霸龙',
           'jobs': ['召唤物'],
           'races': [],
           'price': '0',
           'gui_name': '0-海克斯霸龙',
           'gui_checkbox_key': 'checkbox_海克斯霸龙',
           'gui_combo_num_key': 'combo_num_海克斯霸龙'},
 '虚空鱼': {'name': '虚空鱼',
         'jobs': ['召唤物'],
         'races': [],
         'price': '0',
         'gui_name': '0-虚空鱼',
         'gui_checkbox_key': 'checkbox_虚空鱼',
         'gui_combo_num_key': 'combo_num_虚空鱼'},
 '峡谷先锋': {'name': '峡谷先锋',
          'jobs': ['召唤物'],
          'races': [],
          'price': '0',
          'gui_name': '0-峡谷先锋',
          'gui_checkbox_key': 'checkbox_峡谷先锋',
          'gui_combo_num_key': 'combo_num_峡谷先锋'},
 '纳什男爵': {'name': '纳什男爵',
          'jobs': ['召唤物'],
          'races': [],
          'price': '0',
          'gui_name': '0-纳什男爵',
          'gui_checkbox_key': 'checkbox_纳什男爵',
          'gui_combo_num_key': 'combo_num_纳什男爵'}}
