"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's9.5-志在天际',
 '版本信息': '13.18',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '13.18-2023.S9',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.18-2023.S9/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.18-2023.S9/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.18-2023.S9/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.18-2023.S9/equip.js',
 'url_hex_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/13.18-2023.S9/hex.js'}

    all_chess_name_str = '加里奥-凯尔-瑞兹-赛恩-索拉卡-沃里克-艾希-科加斯-娑娜-卡萨丁-艾瑞莉娅-卡尔玛-塔里克-斯维因-卡特琳娜-雷克顿-嘉文四世-奥莉安娜-卡西奥佩娅-黑默丁格-内瑟斯-波比-玛尔扎哈-慎-阿狸-瑟庄妮-德莱厄斯-杰斯-卡莎-维克兹-塔莉垭-卑尔维斯-烬-金克丝-艾克-蔚-亚托克斯-阿兹尔-莎弥拉-雷克塞-厄斐琉斯-格雷福斯-俄洛伊-米利欧-纳亚菲利-奇亚娜-崔斯特-厄运小姐-诺提勒斯-妮蔻-奎因-菲奥娜-莫德凯撒-尼菈-希尔科-霞-普朗克-瑞兹-以绪塔尔-瑞兹-比尔吉沃特-瑟提-奎桑提-瑞兹-班德尔城-瑞兹-德玛西亚-瑞兹-弗雷尔卓德-瑞兹-艾欧尼亚-瑞兹-诺克萨斯-瑞兹-皮尔特沃夫-瑞兹-暗影岛-瑞兹-恕瑞玛-瑞兹-巨神峰-瑞兹-祖安-尖端炮台-海克斯霸龙-虚空鱼-峡谷先锋-纳什男爵'

    all_race_name_str = '流浪法师-暗裔-德玛西亚-弗雷尔卓德-艾欧尼亚-诺克萨斯-皮尔特沃夫-恕瑞玛-巨神峰-虚空-祖安-比尔吉沃特-以绪塔尔'

    all_job_name_str = '堡垒卫士-格斗家-挑战者-女皇-枪手-神谕者-主宰-术士-潜行者-裁决战士-法师-司令-大发明家-召唤物-海洋之灾-征服者'

    race_chess = {'流浪法师': ['瑞兹',
          '瑞兹-以绪塔尔',
          '瑞兹-比尔吉沃特',
          '瑞兹-班德尔城',
          '瑞兹-德玛西亚',
          '瑞兹-弗雷尔卓德',
          '瑞兹-艾欧尼亚',
          '瑞兹-诺克萨斯',
          '瑞兹-皮尔特沃夫',
          '瑞兹-暗影岛',
          '瑞兹-恕瑞玛',
          '瑞兹-巨神峰',
          '瑞兹-祖安'],
 '暗裔': ['亚托克斯', '纳亚菲利'],
 '德玛西亚': ['加里奥', '凯尔', '娑娜', '嘉文四世', '波比', '奎因', '菲奥娜'],
 '弗雷尔卓德': ['艾希', '瑟庄妮'],
 '艾欧尼亚': ['艾瑞莉娅', '卡尔玛', '慎', '阿狸', '烬', '霞', '瑟提'],
 '诺克萨斯': ['赛恩', '斯维因', '卡特琳娜', '卡西奥佩娅', '德莱厄斯', '莎弥拉', '莫德凯撒'],
 '皮尔特沃夫': ['奥莉安娜', '黑默丁格', '杰斯', '艾克', '蔚'],
 '恕瑞玛': ['雷克顿', '卡西奥佩娅', '内瑟斯', '塔莉垭', '阿兹尔', '纳亚菲利', '奎桑提'],
 '巨神峰': ['索拉卡', '塔里克', '厄斐琉斯'],
 '虚空': ['科加斯', '卡萨丁', '玛尔扎哈', '卡莎', '维克兹', '卑尔维斯', '雷克塞'],
 '祖安': ['沃里克', '金克丝', '艾克', '希尔科'],
 '比尔吉沃特': ['格雷福斯', '俄洛伊', '崔斯特', '厄运小姐', '诺提勒斯', '尼菈', '普朗克'],
 '以绪塔尔': ['米利欧', '奇亚娜', '妮蔻']}

    job_chess = {'堡垒卫士': ['卡萨丁', '塔里克', '波比', '慎', '俄洛伊', '妮蔻', '奎桑提'],
 '格斗家': ['赛恩', '科加斯', '雷克顿', '瑟庄妮', '蔚', '雷克塞'],
 '挑战者': ['沃里克', '艾瑞莉娅', '卡莎', '莎弥拉', '纳亚菲利', '菲奥娜'],
 '女皇': ['卑尔维斯'],
 '枪手': ['杰斯', '金克丝', '厄斐琉斯', '格雷福斯', '普朗克'],
 '神谕者': ['加里奥',
         '瑞兹',
         '索拉卡',
         '卡尔玛',
         '卡西奥佩娅',
         '慎',
         '米利欧',
         '瑞兹-以绪塔尔',
         '瑞兹-比尔吉沃特',
         '瑞兹-班德尔城',
         '瑞兹-德玛西亚',
         '瑞兹-弗雷尔卓德',
         '瑞兹-艾欧尼亚',
         '瑞兹-诺克萨斯',
         '瑞兹-皮尔特沃夫',
         '瑞兹-暗影岛',
         '瑞兹-恕瑞玛',
         '瑞兹-巨神峰',
         '瑞兹-祖安'],
 '主宰': ['沃里克', '内瑟斯', '德莱厄斯', '亚托克斯', '诺提勒斯', '瑟提'],
 '术士': ['娑娜', '维克兹', '塔莉垭', '崔斯特'],
 '潜行者': ['卡特琳娜', '艾克', '格雷福斯', '奇亚娜'],
 '裁决战士': ['凯尔', '亚托克斯', '雷克塞', '奇亚娜', '奎因', '莫德凯撒'],
 '法师': ['塔里克', '斯维因', '奥莉安娜', '玛尔扎哈', '阿狸', '维克兹', '希尔科'],
 '司令': ['斯维因', '嘉文四世', '阿兹尔', '厄运小姐'],
 '大发明家': ['黑默丁格'],
 '召唤物': ['尖端炮台', '海克斯霸龙', '虚空鱼', '峡谷先锋', '纳什男爵'],
 '海洋之灾': ['普朗克'],
 '征服者': ['艾希', '德莱厄斯', '烬', '尼菈', '霞']}

    price_chess = {'0': ['尖端炮台', '海克斯霸龙', '虚空鱼', '峡谷先锋', '纳什男爵'],
 '1': ['凯尔', '科加斯', '艾瑞莉娅', '雷克顿', '奥莉安娜', '卡西奥佩娅', '波比', '玛尔扎哈', '烬', '莎弥拉', '格雷福斯', '俄洛伊', '米利欧'],
 '2': ['加里奥', '索拉卡', '沃里克', '艾希', '卡萨丁', '斯维因', '塔莉垭', '金克丝', '蔚', '纳亚菲利', '奇亚娜', '崔斯特', '瑟提'],
 '3': ['娑娜', '卡尔玛', '塔里克', '卡特琳娜', '德莱厄斯', '杰斯', '维克兹', '艾克', '雷克塞', '厄运小姐', '诺提勒斯', '妮蔻', '奎因'],
 '4': ['嘉文四世', '内瑟斯', '慎', '瑟庄妮', '卡莎', '阿兹尔', '厄斐琉斯', '菲奥娜', '莫德凯撒', '尼菈', '希尔科', '霞'],
 '5': ['瑞兹',
       '赛恩',
       '黑默丁格',
       '阿狸',
       '卑尔维斯',
       '亚托克斯',
       '普朗克',
       '瑞兹-以绪塔尔',
       '瑞兹-比尔吉沃特',
       '奎桑提',
       '瑞兹-班德尔城',
       '瑞兹-德玛西亚',
       '瑞兹-弗雷尔卓德',
       '瑞兹-艾欧尼亚',
       '瑞兹-诺克萨斯',
       '瑞兹-皮尔特沃夫',
       '瑞兹-暗影岛',
       '瑞兹-恕瑞玛',
       '瑞兹-巨神峰',
       '瑞兹-祖安']}

    chess_name_info = {'加里奥': {'name': '加里奥',
         'jobs': ['神谕者'],
         'races': ['德玛西亚'],
         'price': '2',
         'gui_name': '2-加里奥',
         'gui_checkbox_key': 'checkbox_加里奥',
         'gui_combo_num_key': 'combo_num_加里奥'},
 '凯尔': {'name': '凯尔',
        'jobs': ['裁决战士'],
        'races': ['德玛西亚'],
        'price': '1',
        'gui_name': '1-凯尔',
        'gui_checkbox_key': 'checkbox_凯尔',
        'gui_combo_num_key': 'combo_num_凯尔'},
 '瑞兹': {'name': '瑞兹',
        'jobs': ['神谕者'],
        'races': ['流浪法师'],
        'price': '5',
        'gui_name': '5-瑞兹',
        'gui_checkbox_key': 'checkbox_瑞兹',
        'gui_combo_num_key': 'combo_num_瑞兹'},
 '赛恩': {'name': '赛恩',
        'jobs': ['格斗家'],
        'races': ['诺克萨斯'],
        'price': '5',
        'gui_name': '5-赛恩',
        'gui_checkbox_key': 'checkbox_赛恩',
        'gui_combo_num_key': 'combo_num_赛恩'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['神谕者'],
         'races': ['巨神峰'],
         'price': '2',
         'gui_name': '2-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '沃里克': {'name': '沃里克',
         'jobs': ['挑战者', '主宰'],
         'races': ['祖安'],
         'price': '2',
         'gui_name': '2-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '艾希': {'name': '艾希',
        'jobs': ['征服者'],
        'races': ['弗雷尔卓德'],
        'price': '2',
        'gui_name': '2-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '科加斯': {'name': '科加斯',
         'jobs': ['格斗家'],
         'races': ['虚空'],
         'price': '1',
         'gui_name': '1-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '娑娜': {'name': '娑娜',
        'jobs': ['术士'],
        'races': ['德玛西亚'],
        'price': '3',
        'gui_name': '3-娑娜',
        'gui_checkbox_key': 'checkbox_娑娜',
        'gui_combo_num_key': 'combo_num_娑娜'},
 '卡萨丁': {'name': '卡萨丁',
         'jobs': ['堡垒卫士'],
         'races': ['虚空'],
         'price': '2',
         'gui_name': '2-卡萨丁',
         'gui_checkbox_key': 'checkbox_卡萨丁',
         'gui_combo_num_key': 'combo_num_卡萨丁'},
 '艾瑞莉娅': {'name': '艾瑞莉娅',
          'jobs': ['挑战者'],
          'races': ['艾欧尼亚'],
          'price': '1',
          'gui_name': '1-艾瑞莉娅',
          'gui_checkbox_key': 'checkbox_艾瑞莉娅',
          'gui_combo_num_key': 'combo_num_艾瑞莉娅'},
 '卡尔玛': {'name': '卡尔玛',
         'jobs': ['神谕者'],
         'races': ['艾欧尼亚'],
         'price': '3',
         'gui_name': '3-卡尔玛',
         'gui_checkbox_key': 'checkbox_卡尔玛',
         'gui_combo_num_key': 'combo_num_卡尔玛'},
 '塔里克': {'name': '塔里克',
         'jobs': ['堡垒卫士', '法师'],
         'races': ['巨神峰'],
         'price': '3',
         'gui_name': '3-塔里克',
         'gui_checkbox_key': 'checkbox_塔里克',
         'gui_combo_num_key': 'combo_num_塔里克'},
 '斯维因': {'name': '斯维因',
         'jobs': ['法师', '司令'],
         'races': ['诺克萨斯'],
         'price': '2',
         'gui_name': '2-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['潜行者'],
          'races': ['诺克萨斯'],
          'price': '3',
          'gui_name': '3-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '雷克顿': {'name': '雷克顿',
         'jobs': ['格斗家'],
         'races': ['恕瑞玛'],
         'price': '1',
         'gui_name': '1-雷克顿',
         'gui_checkbox_key': 'checkbox_雷克顿',
         'gui_combo_num_key': 'combo_num_雷克顿'},
 '嘉文四世': {'name': '嘉文四世',
          'jobs': ['司令'],
          'races': ['德玛西亚'],
          'price': '4',
          'gui_name': '4-嘉文四世',
          'gui_checkbox_key': 'checkbox_嘉文四世',
          'gui_combo_num_key': 'combo_num_嘉文四世'},
 '奥莉安娜': {'name': '奥莉安娜',
          'jobs': ['法师'],
          'races': ['皮尔特沃夫'],
          'price': '1',
          'gui_name': '1-奥莉安娜',
          'gui_checkbox_key': 'checkbox_奥莉安娜',
          'gui_combo_num_key': 'combo_num_奥莉安娜'},
 '卡西奥佩娅': {'name': '卡西奥佩娅',
           'jobs': ['神谕者'],
           'races': ['诺克萨斯', '恕瑞玛'],
           'price': '1',
           'gui_name': '1-卡西奥佩娅',
           'gui_checkbox_key': 'checkbox_卡西奥佩娅',
           'gui_combo_num_key': 'combo_num_卡西奥佩娅'},
 '黑默丁格': {'name': '黑默丁格',
          'jobs': ['大发明家'],
          'races': ['皮尔特沃夫'],
          'price': '5',
          'gui_name': '5-黑默丁格',
          'gui_checkbox_key': 'checkbox_黑默丁格',
          'gui_combo_num_key': 'combo_num_黑默丁格'},
 '内瑟斯': {'name': '内瑟斯',
         'jobs': ['主宰'],
         'races': ['恕瑞玛'],
         'price': '4',
         'gui_name': '4-内瑟斯',
         'gui_checkbox_key': 'checkbox_内瑟斯',
         'gui_combo_num_key': 'combo_num_内瑟斯'},
 '波比': {'name': '波比',
        'jobs': ['堡垒卫士'],
        'races': ['德玛西亚'],
        'price': '1',
        'gui_name': '1-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '玛尔扎哈': {'name': '玛尔扎哈',
          'jobs': ['法师'],
          'races': ['虚空'],
          'price': '1',
          'gui_name': '1-玛尔扎哈',
          'gui_checkbox_key': 'checkbox_玛尔扎哈',
          'gui_combo_num_key': 'combo_num_玛尔扎哈'},
 '慎': {'name': '慎',
       'jobs': ['堡垒卫士', '神谕者'],
       'races': ['艾欧尼亚'],
       'price': '4',
       'gui_name': '4-慎',
       'gui_checkbox_key': 'checkbox_慎',
       'gui_combo_num_key': 'combo_num_慎'},
 '阿狸': {'name': '阿狸',
        'jobs': ['法师'],
        'races': ['艾欧尼亚'],
        'price': '5',
        'gui_name': '5-阿狸',
        'gui_checkbox_key': 'checkbox_阿狸',
        'gui_combo_num_key': 'combo_num_阿狸'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['格斗家'],
         'races': ['弗雷尔卓德'],
         'price': '4',
         'gui_name': '4-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['主宰', '征服者'],
          'races': ['诺克萨斯'],
          'price': '3',
          'gui_name': '3-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '杰斯': {'name': '杰斯',
        'jobs': ['枪手'],
        'races': ['皮尔特沃夫'],
        'price': '3',
        'gui_name': '3-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '卡莎': {'name': '卡莎',
        'jobs': ['挑战者'],
        'races': ['虚空'],
        'price': '4',
        'gui_name': '4-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'},
 '维克兹': {'name': '维克兹',
         'jobs': ['术士', '法师'],
         'races': ['虚空'],
         'price': '3',
         'gui_name': '3-维克兹',
         'gui_checkbox_key': 'checkbox_维克兹',
         'gui_combo_num_key': 'combo_num_维克兹'},
 '塔莉垭': {'name': '塔莉垭',
         'jobs': ['术士'],
         'races': ['恕瑞玛'],
         'price': '2',
         'gui_name': '2-塔莉垭',
         'gui_checkbox_key': 'checkbox_塔莉垭',
         'gui_combo_num_key': 'combo_num_塔莉垭'},
 '卑尔维斯': {'name': '卑尔维斯',
          'jobs': ['女皇'],
          'races': ['虚空'],
          'price': '5',
          'gui_name': '5-卑尔维斯',
          'gui_checkbox_key': 'checkbox_卑尔维斯',
          'gui_combo_num_key': 'combo_num_卑尔维斯'},
 '烬': {'name': '烬',
       'jobs': ['征服者'],
       'races': ['艾欧尼亚'],
       'price': '1',
       'gui_name': '1-烬',
       'gui_checkbox_key': 'checkbox_烬',
       'gui_combo_num_key': 'combo_num_烬'},
 '金克丝': {'name': '金克丝',
         'jobs': ['枪手'],
         'races': ['祖安'],
         'price': '2',
         'gui_name': '2-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '艾克': {'name': '艾克',
        'jobs': ['潜行者'],
        'races': ['皮尔特沃夫', '祖安'],
        'price': '3',
        'gui_name': '3-艾克',
        'gui_checkbox_key': 'checkbox_艾克',
        'gui_combo_num_key': 'combo_num_艾克'},
 '蔚': {'name': '蔚',
       'jobs': ['格斗家'],
       'races': ['皮尔特沃夫'],
       'price': '2',
       'gui_name': '2-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['主宰', '裁决战士'],
          'races': ['暗裔'],
          'price': '5',
          'gui_name': '5-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '阿兹尔': {'name': '阿兹尔',
         'jobs': ['司令'],
         'races': ['恕瑞玛'],
         'price': '4',
         'gui_name': '4-阿兹尔',
         'gui_checkbox_key': 'checkbox_阿兹尔',
         'gui_combo_num_key': 'combo_num_阿兹尔'},
 '莎弥拉': {'name': '莎弥拉',
         'jobs': ['挑战者'],
         'races': ['诺克萨斯'],
         'price': '1',
         'gui_name': '1-莎弥拉',
         'gui_checkbox_key': 'checkbox_莎弥拉',
         'gui_combo_num_key': 'combo_num_莎弥拉'},
 '雷克塞': {'name': '雷克塞',
         'jobs': ['格斗家', '裁决战士'],
         'races': ['虚空'],
         'price': '3',
         'gui_name': '3-雷克塞',
         'gui_checkbox_key': 'checkbox_雷克塞',
         'gui_combo_num_key': 'combo_num_雷克塞'},
 '厄斐琉斯': {'name': '厄斐琉斯',
          'jobs': ['枪手'],
          'races': ['巨神峰'],
          'price': '4',
          'gui_name': '4-厄斐琉斯',
          'gui_checkbox_key': 'checkbox_厄斐琉斯',
          'gui_combo_num_key': 'combo_num_厄斐琉斯'},
 '格雷福斯': {'name': '格雷福斯',
          'jobs': ['枪手', '潜行者'],
          'races': ['比尔吉沃特'],
          'price': '1',
          'gui_name': '1-格雷福斯',
          'gui_checkbox_key': 'checkbox_格雷福斯',
          'gui_combo_num_key': 'combo_num_格雷福斯'},
 '俄洛伊': {'name': '俄洛伊',
         'jobs': ['堡垒卫士'],
         'races': ['比尔吉沃特'],
         'price': '1',
         'gui_name': '1-俄洛伊',
         'gui_checkbox_key': 'checkbox_俄洛伊',
         'gui_combo_num_key': 'combo_num_俄洛伊'},
 '米利欧': {'name': '米利欧',
         'jobs': ['神谕者'],
         'races': ['以绪塔尔'],
         'price': '1',
         'gui_name': '1-米利欧',
         'gui_checkbox_key': 'checkbox_米利欧',
         'gui_combo_num_key': 'combo_num_米利欧'},
 '纳亚菲利': {'name': '纳亚菲利',
          'jobs': ['挑战者'],
          'races': ['暗裔', '恕瑞玛'],
          'price': '2',
          'gui_name': '2-纳亚菲利',
          'gui_checkbox_key': 'checkbox_纳亚菲利',
          'gui_combo_num_key': 'combo_num_纳亚菲利'},
 '奇亚娜': {'name': '奇亚娜',
         'jobs': ['潜行者', '裁决战士'],
         'races': ['以绪塔尔'],
         'price': '2',
         'gui_name': '2-奇亚娜',
         'gui_checkbox_key': 'checkbox_奇亚娜',
         'gui_combo_num_key': 'combo_num_奇亚娜'},
 '崔斯特': {'name': '崔斯特',
         'jobs': ['术士'],
         'races': ['比尔吉沃特'],
         'price': '2',
         'gui_name': '2-崔斯特',
         'gui_checkbox_key': 'checkbox_崔斯特',
         'gui_combo_num_key': 'combo_num_崔斯特'},
 '厄运小姐': {'name': '厄运小姐',
          'jobs': ['司令'],
          'races': ['比尔吉沃特'],
          'price': '3',
          'gui_name': '3-厄运小姐',
          'gui_checkbox_key': 'checkbox_厄运小姐',
          'gui_combo_num_key': 'combo_num_厄运小姐'},
 '诺提勒斯': {'name': '诺提勒斯',
          'jobs': ['主宰'],
          'races': ['比尔吉沃特'],
          'price': '3',
          'gui_name': '3-诺提勒斯',
          'gui_checkbox_key': 'checkbox_诺提勒斯',
          'gui_combo_num_key': 'combo_num_诺提勒斯'},
 '妮蔻': {'name': '妮蔻',
        'jobs': ['堡垒卫士'],
        'races': ['以绪塔尔'],
        'price': '3',
        'gui_name': '3-妮蔻',
        'gui_checkbox_key': 'checkbox_妮蔻',
        'gui_combo_num_key': 'combo_num_妮蔻'},
 '奎因': {'name': '奎因',
        'jobs': ['裁决战士'],
        'races': ['德玛西亚'],
        'price': '3',
        'gui_name': '3-奎因',
        'gui_checkbox_key': 'checkbox_奎因',
        'gui_combo_num_key': 'combo_num_奎因'},
 '菲奥娜': {'name': '菲奥娜',
         'jobs': ['挑战者'],
         'races': ['德玛西亚'],
         'price': '4',
         'gui_name': '4-菲奥娜',
         'gui_checkbox_key': 'checkbox_菲奥娜',
         'gui_combo_num_key': 'combo_num_菲奥娜'},
 '莫德凯撒': {'name': '莫德凯撒',
          'jobs': ['裁决战士'],
          'races': ['诺克萨斯'],
          'price': '4',
          'gui_name': '4-莫德凯撒',
          'gui_checkbox_key': 'checkbox_莫德凯撒',
          'gui_combo_num_key': 'combo_num_莫德凯撒'},
 '尼菈': {'name': '尼菈',
        'jobs': ['征服者'],
        'races': ['比尔吉沃特'],
        'price': '4',
        'gui_name': '4-尼菈',
        'gui_checkbox_key': 'checkbox_尼菈',
        'gui_combo_num_key': 'combo_num_尼菈'},
 '希尔科': {'name': '希尔科',
         'jobs': ['法师'],
         'races': ['祖安'],
         'price': '4',
         'gui_name': '4-希尔科',
         'gui_checkbox_key': 'checkbox_希尔科',
         'gui_combo_num_key': 'combo_num_希尔科'},
 '霞': {'name': '霞',
       'jobs': ['征服者'],
       'races': ['艾欧尼亚'],
       'price': '4',
       'gui_name': '4-霞',
       'gui_checkbox_key': 'checkbox_霞',
       'gui_combo_num_key': 'combo_num_霞'},
 '普朗克': {'name': '普朗克',
         'jobs': ['枪手', '海洋之灾'],
         'races': ['比尔吉沃特'],
         'price': '5',
         'gui_name': '5-普朗克',
         'gui_checkbox_key': 'checkbox_普朗克',
         'gui_combo_num_key': 'combo_num_普朗克'},
 '瑞兹-以绪塔尔': {'name': '瑞兹-以绪塔尔',
             'jobs': ['神谕者'],
             'races': ['流浪法师'],
             'price': '5',
             'gui_name': '5-瑞兹-以绪塔尔',
             'gui_checkbox_key': 'checkbox_瑞兹-以绪塔尔',
             'gui_combo_num_key': 'combo_num_瑞兹-以绪塔尔'},
 '瑞兹-比尔吉沃特': {'name': '瑞兹-比尔吉沃特',
              'jobs': ['神谕者'],
              'races': ['流浪法师'],
              'price': '5',
              'gui_name': '5-瑞兹-比尔吉沃特',
              'gui_checkbox_key': 'checkbox_瑞兹-比尔吉沃特',
              'gui_combo_num_key': 'combo_num_瑞兹-比尔吉沃特'},
 '瑟提': {'name': '瑟提',
        'jobs': ['主宰'],
        'races': ['艾欧尼亚'],
        'price': '2',
        'gui_name': '2-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'},
 '奎桑提': {'name': '奎桑提',
         'jobs': ['堡垒卫士'],
         'races': ['恕瑞玛'],
         'price': '5',
         'gui_name': '5-奎桑提',
         'gui_checkbox_key': 'checkbox_奎桑提',
         'gui_combo_num_key': 'combo_num_奎桑提'},
 '瑞兹-班德尔城': {'name': '瑞兹-班德尔城',
             'jobs': ['神谕者'],
             'races': ['流浪法师'],
             'price': '5',
             'gui_name': '5-瑞兹-班德尔城',
             'gui_checkbox_key': 'checkbox_瑞兹-班德尔城',
             'gui_combo_num_key': 'combo_num_瑞兹-班德尔城'},
 '瑞兹-德玛西亚': {'name': '瑞兹-德玛西亚',
             'jobs': ['神谕者'],
             'races': ['流浪法师'],
             'price': '5',
             'gui_name': '5-瑞兹-德玛西亚',
             'gui_checkbox_key': 'checkbox_瑞兹-德玛西亚',
             'gui_combo_num_key': 'combo_num_瑞兹-德玛西亚'},
 '瑞兹-弗雷尔卓德': {'name': '瑞兹-弗雷尔卓德',
              'jobs': ['神谕者'],
              'races': ['流浪法师'],
              'price': '5',
              'gui_name': '5-瑞兹-弗雷尔卓德',
              'gui_checkbox_key': 'checkbox_瑞兹-弗雷尔卓德',
              'gui_combo_num_key': 'combo_num_瑞兹-弗雷尔卓德'},
 '瑞兹-艾欧尼亚': {'name': '瑞兹-艾欧尼亚',
             'jobs': ['神谕者'],
             'races': ['流浪法师'],
             'price': '5',
             'gui_name': '5-瑞兹-艾欧尼亚',
             'gui_checkbox_key': 'checkbox_瑞兹-艾欧尼亚',
             'gui_combo_num_key': 'combo_num_瑞兹-艾欧尼亚'},
 '瑞兹-诺克萨斯': {'name': '瑞兹-诺克萨斯',
             'jobs': ['神谕者'],
             'races': ['流浪法师'],
             'price': '5',
             'gui_name': '5-瑞兹-诺克萨斯',
             'gui_checkbox_key': 'checkbox_瑞兹-诺克萨斯',
             'gui_combo_num_key': 'combo_num_瑞兹-诺克萨斯'},
 '瑞兹-皮尔特沃夫': {'name': '瑞兹-皮尔特沃夫',
              'jobs': ['神谕者'],
              'races': ['流浪法师'],
              'price': '5',
              'gui_name': '5-瑞兹-皮尔特沃夫',
              'gui_checkbox_key': 'checkbox_瑞兹-皮尔特沃夫',
              'gui_combo_num_key': 'combo_num_瑞兹-皮尔特沃夫'},
 '瑞兹-暗影岛': {'name': '瑞兹-暗影岛',
            'jobs': ['神谕者'],
            'races': ['流浪法师'],
            'price': '5',
            'gui_name': '5-瑞兹-暗影岛',
            'gui_checkbox_key': 'checkbox_瑞兹-暗影岛',
            'gui_combo_num_key': 'combo_num_瑞兹-暗影岛'},
 '瑞兹-恕瑞玛': {'name': '瑞兹-恕瑞玛',
            'jobs': ['神谕者'],
            'races': ['流浪法师'],
            'price': '5',
            'gui_name': '5-瑞兹-恕瑞玛',
            'gui_checkbox_key': 'checkbox_瑞兹-恕瑞玛',
            'gui_combo_num_key': 'combo_num_瑞兹-恕瑞玛'},
 '瑞兹-巨神峰': {'name': '瑞兹-巨神峰',
            'jobs': ['神谕者'],
            'races': ['流浪法师'],
            'price': '5',
            'gui_name': '5-瑞兹-巨神峰',
            'gui_checkbox_key': 'checkbox_瑞兹-巨神峰',
            'gui_combo_num_key': 'combo_num_瑞兹-巨神峰'},
 '瑞兹-祖安': {'name': '瑞兹-祖安',
           'jobs': ['神谕者'],
           'races': ['流浪法师'],
           'price': '5',
           'gui_name': '5-瑞兹-祖安',
           'gui_checkbox_key': 'checkbox_瑞兹-祖安',
           'gui_combo_num_key': 'combo_num_瑞兹-祖安'},
 '尖端炮台': {'name': '尖端炮台',
          'jobs': ['召唤物'],
          'races': [],
          'price': '0',
          'gui_name': '0-尖端炮台',
          'gui_checkbox_key': 'checkbox_尖端炮台',
          'gui_combo_num_key': 'combo_num_尖端炮台'},
 '海克斯霸龙': {'name': '海克斯霸龙',
           'jobs': ['召唤物'],
           'races': [],
           'price': '0',
           'gui_name': '0-海克斯霸龙',
           'gui_checkbox_key': 'checkbox_海克斯霸龙',
           'gui_combo_num_key': 'combo_num_海克斯霸龙'},
 '虚空鱼': {'name': '虚空鱼',
         'jobs': ['召唤物'],
         'races': [],
         'price': '0',
         'gui_name': '0-虚空鱼',
         'gui_checkbox_key': 'checkbox_虚空鱼',
         'gui_combo_num_key': 'combo_num_虚空鱼'},
 '峡谷先锋': {'name': '峡谷先锋',
          'jobs': ['召唤物'],
          'races': [],
          'price': '0',
          'gui_name': '0-峡谷先锋',
          'gui_checkbox_key': 'checkbox_峡谷先锋',
          'gui_combo_num_key': 'combo_num_峡谷先锋'},
 '纳什男爵': {'name': '纳什男爵',
          'jobs': ['召唤物'],
          'races': [],
          'price': '0',
          'gui_name': '0-纳什男爵',
          'gui_checkbox_key': 'checkbox_纳什男爵',
          'gui_combo_num_key': 'combo_num_纳什男爵'}}
