"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's2-元素崛起',
 '版本信息': '9.22',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '9.22-2019.S2',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.22-2019.S2/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.22-2019.S2/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.22-2019.S2/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/9.22-2019.S2/equip.js',
 'url_hex_data': None,
 '强化符文说明': '该赛季尚未引入强化符文系统'}

    all_chess_name_str = '安妮-奥拉夫-乐芙兰-弗拉基米尔-易-赛恩-希维尔-索拉卡-沃里克-艾希-贾克斯-辛吉德-图奇-蒙多医生-迦娜-塔里克-维迦-墨菲特-魔腾-茂凯-雷克顿-布兰德-薇恩-斯卡纳-内瑟斯-伊泽瑞尔-约里克-玛尔扎哈-克格莫-拉克丝-沃利贝尔-韦鲁斯-诺提勒斯-卡兹克-黛安娜-辛德拉-婕拉-亚索-塔莉垭-布隆-千珏-劫-奇亚娜-亚托克斯-娜美-阿兹尔-锤石-雷克塞-艾翁-奥恩-妮蔻-拉克丝-水晶-拉克丝-雷霆-拉克丝-极地-拉克丝-地狱火-拉克丝-光-拉克丝-钢铁-拉克丝-海洋-拉克丝-影-拉克丝-云霄-拉克丝-森林-奇亚娜-地狱火-奇亚娜-山脉-奇亚娜-海洋-奇亚娜-云霄'

    all_race_name_str = '山脉-水晶-光-剧毒-海洋-沙漠-雷霆-极地-地狱火-钢铁-影-云霄-森林'

    all_job_name_str = '德鲁伊-炼金师-刺客-大元素使-狂战士-剑士-召唤使-魔法师-秘术-掠食者-游侠-123'

    race_chess = {'山脉': ['墨菲特', '拉克丝', '塔莉垭', '奇亚娜-山脉'],
 '水晶': ['艾希', '塔里克', '斯卡纳', '拉克丝', '拉克丝-水晶'],
 '光': ['索拉卡', '贾克斯', '薇恩', '内瑟斯', '约里克', '拉克丝', '亚托克斯', '拉克丝-光'],
 '剧毒': ['辛吉德', '图奇', '蒙多医生', '克格莫', '拉克丝'],
 '海洋': ['弗拉基米尔', '拉克丝', '诺提勒斯', '辛德拉', '娜美', '锤石', '拉克丝-海洋', '奇亚娜-海洋'],
 '沙漠': ['希维尔', '雷克顿', '拉克丝', '卡兹克', '阿兹尔'],
 '雷霆': ['拉克丝', '沃利贝尔', '劫', '奥恩', '拉克丝-雷霆'],
 '极地': ['奥拉夫', '沃里克', '伊泽瑞尔', '拉克丝', '沃利贝尔', '布隆', '拉克丝-极地'],
 '地狱火': ['安妮', '布兰德', '拉克丝', '韦鲁斯', '黛安娜', '婕拉', '千珏', '奇亚娜', '拉克丝-地狱火', '奇亚娜-地狱火'],
 '钢铁': ['魔腾', '拉克丝', '雷克塞', '拉克丝-钢铁'],
 '影': ['易', '赛恩', '维迦', '玛尔扎哈', '拉克丝', '千珏', '拉克丝-影'],
 '云霄': ['迦娜', '拉克丝', '亚索', '拉克丝-云霄', '奇亚娜-云霄'],
 '森林': ['乐芙兰', '茂凯', '拉克丝', '艾翁', '妮蔻', '拉克丝-森林']}

    job_chess = {'德鲁伊': ['茂凯', '艾翁', '妮蔻'],
 '炼金师': ['辛吉德'],
 '刺客': ['乐芙兰', '魔腾', '卡兹克', '黛安娜', '劫', '奇亚娜', '奇亚娜-地狱火', '奇亚娜-山脉', '奇亚娜-海洋', '奇亚娜-云霄'],
 '大元素使': ['拉克丝',
          '拉克丝-水晶',
          '拉克丝-雷霆',
          '拉克丝-极地',
          '拉克丝-地狱火',
          '拉克丝-光',
          '拉克丝-钢铁',
          '拉克丝-海洋',
          '拉克丝-影',
          '拉克丝-云霄',
          '拉克丝-森林'],
 '狂战士': ['奥拉夫', '赛恩', '贾克斯', '蒙多医生', '雷克顿', '沃利贝尔'],
 '剑士': ['易', '希维尔', '亚索', '亚托克斯'],
 '召唤使': ['安妮', '约里克', '玛尔扎哈', '婕拉', '劫', '阿兹尔'],
 '魔法师': ['弗拉基米尔', '维迦', '布兰德', '辛德拉', '塔莉垭'],
 '秘术': ['易', '索拉卡', '迦娜', '娜美'],
 '掠食者': ['沃里克', '斯卡纳', '克格莫', '雷克塞'],
 '游侠': ['艾希', '图奇', '薇恩', '伊泽瑞尔', '韦鲁斯', '千珏'],
 '123': []}

    price_chess = {'1': ['弗拉基米尔', '沃里克', '茂凯', '雷克顿', '薇恩', '内瑟斯', '克格莫', '黛安娜', '婕拉', '塔莉垭', '艾翁', '奥恩'],
 '2': ['乐芙兰', '贾克斯', '斯卡纳', '玛尔扎哈', '沃利贝尔', '韦鲁斯', '辛德拉', '亚索', '布隆', '锤石', '雷克塞', '妮蔻'],
 '3': ['赛恩',
       '希维尔',
       '索拉卡',
       '蒙多医生',
       '维迦',
       '魔腾',
       '伊泽瑞尔',
       '诺提勒斯',
       '千珏',
       '奇亚娜',
       '亚托克斯',
       '阿兹尔',
       '奇亚娜-地狱火',
       '奇亚娜-山脉',
       '奇亚娜-海洋',
       '奇亚娜-云霄'],
 '4': ['安妮', '奥拉夫', '艾希', '图奇', '迦娜', '墨菲特', '布兰德', '约里克', '卡兹克'],
 '5': ['易', '辛吉德', '塔里克', '劫', '娜美'],
 '7': ['拉克丝',
       '拉克丝-水晶',
       '拉克丝-雷霆',
       '拉克丝-极地',
       '拉克丝-地狱火',
       '拉克丝-光',
       '拉克丝-钢铁',
       '拉克丝-海洋',
       '拉克丝-影',
       '拉克丝-云霄',
       '拉克丝-森林']}

    chess_name_info = {'安妮': {'name': '安妮',
        'jobs': ['召唤使'],
        'races': ['地狱火'],
        'price': '4',
        'gui_name': '4-安妮',
        'gui_checkbox_key': 'checkbox_安妮',
        'gui_combo_num_key': 'combo_num_安妮'},
 '奥拉夫': {'name': '奥拉夫',
         'jobs': ['狂战士'],
         'races': ['极地'],
         'price': '4',
         'gui_name': '4-奥拉夫',
         'gui_checkbox_key': 'checkbox_奥拉夫',
         'gui_combo_num_key': 'combo_num_奥拉夫'},
 '乐芙兰': {'name': '乐芙兰',
         'jobs': ['刺客'],
         'races': ['森林'],
         'price': '2',
         'gui_name': '2-乐芙兰',
         'gui_checkbox_key': 'checkbox_乐芙兰',
         'gui_combo_num_key': 'combo_num_乐芙兰'},
 '弗拉基米尔': {'name': '弗拉基米尔',
           'jobs': ['魔法师'],
           'races': ['海洋'],
           'price': '1',
           'gui_name': '1-弗拉基米尔',
           'gui_checkbox_key': 'checkbox_弗拉基米尔',
           'gui_combo_num_key': 'combo_num_弗拉基米尔'},
 '易': {'name': '易',
       'jobs': ['剑士', '秘术'],
       'races': ['影'],
       'price': '5',
       'gui_name': '5-易',
       'gui_checkbox_key': 'checkbox_易',
       'gui_combo_num_key': 'combo_num_易'},
 '赛恩': {'name': '赛恩',
        'jobs': ['狂战士'],
        'races': ['影'],
        'price': '3',
        'gui_name': '3-赛恩',
        'gui_checkbox_key': 'checkbox_赛恩',
        'gui_combo_num_key': 'combo_num_赛恩'},
 '希维尔': {'name': '希维尔',
         'jobs': ['剑士'],
         'races': ['沙漠'],
         'price': '3',
         'gui_name': '3-希维尔',
         'gui_checkbox_key': 'checkbox_希维尔',
         'gui_combo_num_key': 'combo_num_希维尔'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['秘术'],
         'races': ['光'],
         'price': '3',
         'gui_name': '3-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '沃里克': {'name': '沃里克',
         'jobs': ['掠食者'],
         'races': ['极地'],
         'price': '1',
         'gui_name': '1-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '艾希': {'name': '艾希',
        'jobs': ['游侠'],
        'races': ['水晶'],
        'price': '4',
        'gui_name': '4-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '贾克斯': {'name': '贾克斯',
         'jobs': ['狂战士'],
         'races': ['光'],
         'price': '2',
         'gui_name': '2-贾克斯',
         'gui_checkbox_key': 'checkbox_贾克斯',
         'gui_combo_num_key': 'combo_num_贾克斯'},
 '辛吉德': {'name': '辛吉德',
         'jobs': ['炼金师'],
         'races': ['剧毒'],
         'price': '5',
         'gui_name': '5-辛吉德',
         'gui_checkbox_key': 'checkbox_辛吉德',
         'gui_combo_num_key': 'combo_num_辛吉德'},
 '图奇': {'name': '图奇',
        'jobs': ['游侠'],
        'races': ['剧毒'],
        'price': '4',
        'gui_name': '4-图奇',
        'gui_checkbox_key': 'checkbox_图奇',
        'gui_combo_num_key': 'combo_num_图奇'},
 '蒙多医生': {'name': '蒙多医生',
          'jobs': ['狂战士'],
          'races': ['剧毒'],
          'price': '3',
          'gui_name': '3-蒙多医生',
          'gui_checkbox_key': 'checkbox_蒙多医生',
          'gui_combo_num_key': 'combo_num_蒙多医生'},
 '迦娜': {'name': '迦娜',
        'jobs': ['秘术'],
        'races': ['云霄'],
        'price': '4',
        'gui_name': '4-迦娜',
        'gui_checkbox_key': 'checkbox_迦娜',
        'gui_combo_num_key': 'combo_num_迦娜'},
 '塔里克': {'name': '塔里克',
         'jobs': [],
         'races': ['水晶'],
         'price': '5',
         'gui_name': '5-塔里克',
         'gui_checkbox_key': 'checkbox_塔里克',
         'gui_combo_num_key': 'combo_num_塔里克'},
 '维迦': {'name': '维迦',
        'jobs': ['魔法师'],
        'races': ['影'],
        'price': '3',
        'gui_name': '3-维迦',
        'gui_checkbox_key': 'checkbox_维迦',
        'gui_combo_num_key': 'combo_num_维迦'},
 '墨菲特': {'name': '墨菲特',
         'jobs': [],
         'races': ['山脉'],
         'price': '4',
         'gui_name': '4-墨菲特',
         'gui_checkbox_key': 'checkbox_墨菲特',
         'gui_combo_num_key': 'combo_num_墨菲特'},
 '魔腾': {'name': '魔腾',
        'jobs': ['刺客'],
        'races': ['钢铁'],
        'price': '3',
        'gui_name': '3-魔腾',
        'gui_checkbox_key': 'checkbox_魔腾',
        'gui_combo_num_key': 'combo_num_魔腾'},
 '茂凯': {'name': '茂凯',
        'jobs': ['德鲁伊'],
        'races': ['森林'],
        'price': '1',
        'gui_name': '1-茂凯',
        'gui_checkbox_key': 'checkbox_茂凯',
        'gui_combo_num_key': 'combo_num_茂凯'},
 '雷克顿': {'name': '雷克顿',
         'jobs': ['狂战士'],
         'races': ['沙漠'],
         'price': '1',
         'gui_name': '1-雷克顿',
         'gui_checkbox_key': 'checkbox_雷克顿',
         'gui_combo_num_key': 'combo_num_雷克顿'},
 '布兰德': {'name': '布兰德',
         'jobs': ['魔法师'],
         'races': ['地狱火'],
         'price': '4',
         'gui_name': '4-布兰德',
         'gui_checkbox_key': 'checkbox_布兰德',
         'gui_combo_num_key': 'combo_num_布兰德'},
 '薇恩': {'name': '薇恩',
        'jobs': ['游侠'],
        'races': ['光'],
        'price': '1',
        'gui_name': '1-薇恩',
        'gui_checkbox_key': 'checkbox_薇恩',
        'gui_combo_num_key': 'combo_num_薇恩'},
 '斯卡纳': {'name': '斯卡纳',
         'jobs': ['掠食者'],
         'races': ['水晶'],
         'price': '2',
         'gui_name': '2-斯卡纳',
         'gui_checkbox_key': 'checkbox_斯卡纳',
         'gui_combo_num_key': 'combo_num_斯卡纳'},
 '内瑟斯': {'name': '内瑟斯',
         'jobs': [],
         'races': ['光'],
         'price': '1',
         'gui_name': '1-内瑟斯',
         'gui_checkbox_key': 'checkbox_内瑟斯',
         'gui_combo_num_key': 'combo_num_内瑟斯'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['游侠'],
          'races': ['极地'],
          'price': '3',
          'gui_name': '3-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '约里克': {'name': '约里克',
         'jobs': ['召唤使'],
         'races': ['光'],
         'price': '4',
         'gui_name': '4-约里克',
         'gui_checkbox_key': 'checkbox_约里克',
         'gui_combo_num_key': 'combo_num_约里克'},
 '玛尔扎哈': {'name': '玛尔扎哈',
          'jobs': ['召唤使'],
          'races': ['影'],
          'price': '2',
          'gui_name': '2-玛尔扎哈',
          'gui_checkbox_key': 'checkbox_玛尔扎哈',
          'gui_combo_num_key': 'combo_num_玛尔扎哈'},
 '克格莫': {'name': '克格莫',
         'jobs': ['掠食者'],
         'races': ['剧毒'],
         'price': '1',
         'gui_name': '1-克格莫',
         'gui_checkbox_key': 'checkbox_克格莫',
         'gui_combo_num_key': 'combo_num_克格莫'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['大元素使'],
         'races': ['山脉', '水晶', '光', '剧毒', '海洋', '沙漠', '雷霆', '极地', '地狱火', '钢铁', '影', '云霄', '森林'],
         'price': '7',
         'gui_name': '7-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '沃利贝尔': {'name': '沃利贝尔',
          'jobs': ['狂战士'],
          'races': ['雷霆', '极地'],
          'price': '2',
          'gui_name': '2-沃利贝尔',
          'gui_checkbox_key': 'checkbox_沃利贝尔',
          'gui_combo_num_key': 'combo_num_沃利贝尔'},
 '韦鲁斯': {'name': '韦鲁斯',
         'jobs': ['游侠'],
         'races': ['地狱火'],
         'price': '2',
         'gui_name': '2-韦鲁斯',
         'gui_checkbox_key': 'checkbox_韦鲁斯',
         'gui_combo_num_key': 'combo_num_韦鲁斯'},
 '诺提勒斯': {'name': '诺提勒斯',
          'jobs': [],
          'races': ['海洋'],
          'price': '3',
          'gui_name': '3-诺提勒斯',
          'gui_checkbox_key': 'checkbox_诺提勒斯',
          'gui_combo_num_key': 'combo_num_诺提勒斯'},
 '卡兹克': {'name': '卡兹克',
         'jobs': ['刺客'],
         'races': ['沙漠'],
         'price': '4',
         'gui_name': '4-卡兹克',
         'gui_checkbox_key': 'checkbox_卡兹克',
         'gui_combo_num_key': 'combo_num_卡兹克'},
 '黛安娜': {'name': '黛安娜',
         'jobs': ['刺客'],
         'races': ['地狱火'],
         'price': '1',
         'gui_name': '1-黛安娜',
         'gui_checkbox_key': 'checkbox_黛安娜',
         'gui_combo_num_key': 'combo_num_黛安娜'},
 '辛德拉': {'name': '辛德拉',
         'jobs': ['魔法师'],
         'races': ['海洋'],
         'price': '2',
         'gui_name': '2-辛德拉',
         'gui_checkbox_key': 'checkbox_辛德拉',
         'gui_combo_num_key': 'combo_num_辛德拉'},
 '婕拉': {'name': '婕拉',
        'jobs': ['召唤使'],
        'races': ['地狱火'],
        'price': '1',
        'gui_name': '1-婕拉',
        'gui_checkbox_key': 'checkbox_婕拉',
        'gui_combo_num_key': 'combo_num_婕拉'},
 '亚索': {'name': '亚索',
        'jobs': ['剑士'],
        'races': ['云霄'],
        'price': '2',
        'gui_name': '2-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '塔莉垭': {'name': '塔莉垭',
         'jobs': ['魔法师'],
         'races': ['山脉'],
         'price': '1',
         'gui_name': '1-塔莉垭',
         'gui_checkbox_key': 'checkbox_塔莉垭',
         'gui_combo_num_key': 'combo_num_塔莉垭'},
 '布隆': {'name': '布隆',
        'jobs': [],
        'races': ['极地'],
        'price': '2',
        'gui_name': '2-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '千珏': {'name': '千珏',
        'jobs': ['游侠'],
        'races': ['地狱火', '影'],
        'price': '3',
        'gui_name': '3-千珏',
        'gui_checkbox_key': 'checkbox_千珏',
        'gui_combo_num_key': 'combo_num_千珏'},
 '劫': {'name': '劫',
       'jobs': ['刺客', '召唤使'],
       'races': ['雷霆'],
       'price': '5',
       'gui_name': '5-劫',
       'gui_checkbox_key': 'checkbox_劫',
       'gui_combo_num_key': 'combo_num_劫'},
 '奇亚娜': {'name': '奇亚娜',
         'jobs': ['刺客'],
         'races': ['地狱火'],
         'price': '3',
         'gui_name': '3-奇亚娜',
         'gui_checkbox_key': 'checkbox_奇亚娜',
         'gui_combo_num_key': 'combo_num_奇亚娜'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['剑士'],
          'races': ['光'],
          'price': '3',
          'gui_name': '3-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '娜美': {'name': '娜美',
        'jobs': ['秘术'],
        'races': ['海洋'],
        'price': '5',
        'gui_name': '5-娜美',
        'gui_checkbox_key': 'checkbox_娜美',
        'gui_combo_num_key': 'combo_num_娜美'},
 '阿兹尔': {'name': '阿兹尔',
         'jobs': ['召唤使'],
         'races': ['沙漠'],
         'price': '3',
         'gui_name': '3-阿兹尔',
         'gui_checkbox_key': 'checkbox_阿兹尔',
         'gui_combo_num_key': 'combo_num_阿兹尔'},
 '锤石': {'name': '锤石',
        'jobs': [],
        'races': ['海洋'],
        'price': '2',
        'gui_name': '2-锤石',
        'gui_checkbox_key': 'checkbox_锤石',
        'gui_combo_num_key': 'combo_num_锤石'},
 '雷克塞': {'name': '雷克塞',
         'jobs': ['掠食者'],
         'races': ['钢铁'],
         'price': '2',
         'gui_name': '2-雷克塞',
         'gui_checkbox_key': 'checkbox_雷克塞',
         'gui_combo_num_key': 'combo_num_雷克塞'},
 '艾翁': {'name': '艾翁',
        'jobs': ['德鲁伊'],
        'races': ['森林'],
        'price': '1',
        'gui_name': '1-艾翁',
        'gui_checkbox_key': 'checkbox_艾翁',
        'gui_combo_num_key': 'combo_num_艾翁'},
 '奥恩': {'name': '奥恩',
        'jobs': [],
        'races': ['雷霆'],
        'price': '1',
        'gui_name': '1-奥恩',
        'gui_checkbox_key': 'checkbox_奥恩',
        'gui_combo_num_key': 'combo_num_奥恩'},
 '妮蔻': {'name': '妮蔻',
        'jobs': ['德鲁伊'],
        'races': ['森林'],
        'price': '2',
        'gui_name': '2-妮蔻',
        'gui_checkbox_key': 'checkbox_妮蔻',
        'gui_combo_num_key': 'combo_num_妮蔻'},
 '拉克丝-水晶': {'name': '拉克丝-水晶',
            'jobs': ['大元素使'],
            'races': ['水晶'],
            'price': '7',
            'gui_name': '7-拉克丝-水晶',
            'gui_checkbox_key': 'checkbox_拉克丝-水晶',
            'gui_combo_num_key': 'combo_num_拉克丝-水晶'},
 '拉克丝-雷霆': {'name': '拉克丝-雷霆',
            'jobs': ['大元素使'],
            'races': ['雷霆'],
            'price': '7',
            'gui_name': '7-拉克丝-雷霆',
            'gui_checkbox_key': 'checkbox_拉克丝-雷霆',
            'gui_combo_num_key': 'combo_num_拉克丝-雷霆'},
 '拉克丝-极地': {'name': '拉克丝-极地',
            'jobs': ['大元素使'],
            'races': ['极地'],
            'price': '7',
            'gui_name': '7-拉克丝-极地',
            'gui_checkbox_key': 'checkbox_拉克丝-极地',
            'gui_combo_num_key': 'combo_num_拉克丝-极地'},
 '拉克丝-地狱火': {'name': '拉克丝-地狱火',
             'jobs': ['大元素使'],
             'races': ['地狱火'],
             'price': '7',
             'gui_name': '7-拉克丝-地狱火',
             'gui_checkbox_key': 'checkbox_拉克丝-地狱火',
             'gui_combo_num_key': 'combo_num_拉克丝-地狱火'},
 '拉克丝-光': {'name': '拉克丝-光',
           'jobs': ['大元素使'],
           'races': ['光'],
           'price': '7',
           'gui_name': '7-拉克丝-光',
           'gui_checkbox_key': 'checkbox_拉克丝-光',
           'gui_combo_num_key': 'combo_num_拉克丝-光'},
 '拉克丝-钢铁': {'name': '拉克丝-钢铁',
            'jobs': ['大元素使'],
            'races': ['钢铁'],
            'price': '7',
            'gui_name': '7-拉克丝-钢铁',
            'gui_checkbox_key': 'checkbox_拉克丝-钢铁',
            'gui_combo_num_key': 'combo_num_拉克丝-钢铁'},
 '拉克丝-海洋': {'name': '拉克丝-海洋',
            'jobs': ['大元素使'],
            'races': ['海洋'],
            'price': '7',
            'gui_name': '7-拉克丝-海洋',
            'gui_checkbox_key': 'checkbox_拉克丝-海洋',
            'gui_combo_num_key': 'combo_num_拉克丝-海洋'},
 '拉克丝-影': {'name': '拉克丝-影',
           'jobs': ['大元素使'],
           'races': ['影'],
           'price': '7',
           'gui_name': '7-拉克丝-影',
           'gui_checkbox_key': 'checkbox_拉克丝-影',
           'gui_combo_num_key': 'combo_num_拉克丝-影'},
 '拉克丝-云霄': {'name': '拉克丝-云霄',
            'jobs': ['大元素使'],
            'races': ['云霄'],
            'price': '7',
            'gui_name': '7-拉克丝-云霄',
            'gui_checkbox_key': 'checkbox_拉克丝-云霄',
            'gui_combo_num_key': 'combo_num_拉克丝-云霄'},
 '拉克丝-森林': {'name': '拉克丝-森林',
            'jobs': ['大元素使'],
            'races': ['森林'],
            'price': '7',
            'gui_name': '7-拉克丝-森林',
            'gui_checkbox_key': 'checkbox_拉克丝-森林',
            'gui_combo_num_key': 'combo_num_拉克丝-森林'},
 '奇亚娜-地狱火': {'name': '奇亚娜-地狱火',
             'jobs': ['刺客'],
             'races': ['地狱火'],
             'price': '3',
             'gui_name': '3-奇亚娜-地狱火',
             'gui_checkbox_key': 'checkbox_奇亚娜-地狱火',
             'gui_combo_num_key': 'combo_num_奇亚娜-地狱火'},
 '奇亚娜-山脉': {'name': '奇亚娜-山脉',
            'jobs': ['刺客'],
            'races': ['山脉'],
            'price': '3',
            'gui_name': '3-奇亚娜-山脉',
            'gui_checkbox_key': 'checkbox_奇亚娜-山脉',
            'gui_combo_num_key': 'combo_num_奇亚娜-山脉'},
 '奇亚娜-海洋': {'name': '奇亚娜-海洋',
            'jobs': ['刺客'],
            'races': ['海洋'],
            'price': '3',
            'gui_name': '3-奇亚娜-海洋',
            'gui_checkbox_key': 'checkbox_奇亚娜-海洋',
            'gui_combo_num_key': 'combo_num_奇亚娜-海洋'},
 '奇亚娜-云霄': {'name': '奇亚娜-云霄',
            'jobs': ['刺客'],
            'races': ['云霄'],
            'price': '3',
            'gui_name': '3-奇亚娜-云霄',
            'gui_checkbox_key': 'checkbox_奇亚娜-云霄',
            'gui_combo_num_key': 'combo_num_奇亚娜-云霄'}}
