"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's4-命运之轮',
 '版本信息': '10.19',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '10.19-2020.S4',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.19-2020.S4/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.19-2020.S4/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.19-2020.S4/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/10.19-2020.S4/equip.js',
 'url_hex_data': None,
 '强化符文说明': '该赛季尚未引入强化符文系统'}

    all_chess_name_str = '安妮-崔斯特-赵信-提莫-沃里克-努努-艾希-贾克斯-莫甘娜-基兰-伊芙琳-艾瑞莉娅-迦娜-维迦-卡特琳娜-茂凯-嘉文四世-伊莉丝-孙悟空-李青-薇恩-卡西奥佩娅-奈德丽-伊泽瑞尔-阿卡丽-凯南-盖伦-泰隆-锐雯-慎-拉克丝-阿狸-瑟庄妮-菲奥娜-璐璐-赫卡里姆-丽桑卓-黛安娜-凯隐-亚索-烬-千珏-金克丝-塔姆-劫-蔚-亚托克斯-娜美-阿兹尔-悠米-锤石-卡莉丝塔-塞拉斯-厄斐琉斯-派克-永恩-瑟提-莉莉娅'

    all_race_name_str = '腥红之月-天神-灵魂莲华夜幽-永恒之森-玉剑仙-浪人-福星-月神-忍者-灵魂莲华明昼-霸王-三国猛将-天煞'

    all_job_name_str = '宗师-刺客-斗士-耀光使-决斗大师-猎人-神盾使-魔法师-秘术师-夜影-神射手-重装战士-枭雄'

    race_chess = {'腥红之月': ['崔斯特', '基兰', '伊芙琳', '伊莉丝', '烬', '亚托克斯', '卡莉丝塔', '派克'],
 '天神': ['沃里克', '贾克斯', '艾瑞莉娅', '孙悟空', '李青', '拉克丝'],
 '灵魂莲华夜幽': ['薇恩', '卡西奥佩娅', '锐雯', '锤石', '莉莉娅'],
 '永恒之森': ['努努', '艾希', '维迦', '茂凯', '伊泽瑞尔', '璐璐', '赫卡里姆'],
 '玉剑仙': ['莫甘娜', '艾瑞莉娅', '迦娜', '泰隆', '菲奥娜', '娜美'],
 '浪人': ['亚索', '永恩'],
 '福星': ['安妮', '卡特琳娜', '瑟庄妮', '金克丝', '塔姆'],
 '月神': ['丽桑卓', '黛安娜', '塞拉斯', '厄斐琉斯'],
 '忍者': ['阿卡丽', '凯南', '慎', '劫'],
 '灵魂莲华明昼': ['提莫', '阿狸', '千珏', '悠米'],
 '霸王': ['瑟提'],
 '三国猛将': ['赵信', '卡特琳娜', '嘉文四世', '奈德丽', '盖伦', '蔚', '阿兹尔'],
 '天煞': ['凯隐']}

    job_chess = {'宗师': ['艾瑞莉娅', '慎', '永恩'],
 '刺客': ['卡特琳娜', '阿卡丽', '泰隆', '黛安娜', '派克'],
 '斗士': ['沃里克', '努努', '茂凯', '塔姆', '蔚', '塞拉斯', '瑟提'],
 '耀光使': ['莫甘娜', '伊泽瑞尔', '拉克丝', '丽桑卓'],
 '决斗大师': ['赵信', '贾克斯', '李青', '菲奥娜', '亚索', '卡莉丝塔'],
 '猎人': ['沃里克', '艾希', '千珏', '厄斐琉斯'],
 '神盾使': ['嘉文四世', '伊莉丝', '凯南', '锐雯', '阿兹尔'],
 '魔法师': ['安妮', '崔斯特', '维迦', '阿狸', '璐璐', '娜美', '莉莉娅'],
 '秘术师': ['基兰', '迦娜', '卡西奥佩娅', '慎', '悠米'],
 '夜影': ['伊芙琳', '凯隐', '劫'],
 '神射手': ['提莫', '薇恩', '奈德丽', '烬', '金克丝'],
 '重装战士': ['孙悟空', '盖伦', '瑟庄妮', '赫卡里姆', '亚托克斯', '锤石'],
 '枭雄': ['阿兹尔']}

    price_chess = {'1': ['崔斯特', '茂凯', '伊莉丝', '孙悟空', '薇恩', '奈德丽', '盖伦', '菲奥娜', '丽桑卓', '黛安娜', '亚索', '塔姆', '娜美'],
 '2': ['安妮', '提莫', '贾克斯', '迦娜', '嘉文四世', '璐璐', '赫卡里姆', '劫', '蔚', '锤石', '塞拉斯', '厄斐琉斯', '派克'],
 '3': ['赵信', '努努', '伊芙琳', '艾瑞莉娅', '维迦', '卡特琳娜', '阿卡丽', '凯南', '拉克丝', '千珏', '金克丝', '悠米', '卡莉丝塔'],
 '4': ['沃里克', '艾希', '莫甘娜', '卡西奥佩娅', '泰隆', '锐雯', '慎', '阿狸', '瑟庄妮', '烬', '亚托克斯'],
 '5': ['基兰', '李青', '伊泽瑞尔', '凯隐', '阿兹尔', '永恩', '瑟提', '莉莉娅']}

    chess_name_info = {'安妮': {'name': '安妮',
        'jobs': ['魔法师'],
        'races': ['福星'],
        'price': '2',
        'gui_name': '2-安妮',
        'gui_checkbox_key': 'checkbox_安妮',
        'gui_combo_num_key': 'combo_num_安妮'},
 '崔斯特': {'name': '崔斯特',
         'jobs': ['魔法师'],
         'races': ['腥红之月'],
         'price': '1',
         'gui_name': '1-崔斯特',
         'gui_checkbox_key': 'checkbox_崔斯特',
         'gui_combo_num_key': 'combo_num_崔斯特'},
 '赵信': {'name': '赵信',
        'jobs': ['决斗大师'],
        'races': ['三国猛将'],
        'price': '3',
        'gui_name': '3-赵信',
        'gui_checkbox_key': 'checkbox_赵信',
        'gui_combo_num_key': 'combo_num_赵信'},
 '提莫': {'name': '提莫',
        'jobs': ['神射手'],
        'races': ['灵魂莲华明昼'],
        'price': '2',
        'gui_name': '2-提莫',
        'gui_checkbox_key': 'checkbox_提莫',
        'gui_combo_num_key': 'combo_num_提莫'},
 '沃里克': {'name': '沃里克',
         'jobs': ['斗士', '猎人'],
         'races': ['天神'],
         'price': '4',
         'gui_name': '4-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '努努': {'name': '努努',
        'jobs': ['斗士'],
        'races': ['永恒之森'],
        'price': '3',
        'gui_name': '3-努努',
        'gui_checkbox_key': 'checkbox_努努',
        'gui_combo_num_key': 'combo_num_努努'},
 '艾希': {'name': '艾希',
        'jobs': ['猎人'],
        'races': ['永恒之森'],
        'price': '4',
        'gui_name': '4-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '贾克斯': {'name': '贾克斯',
         'jobs': ['决斗大师'],
         'races': ['天神'],
         'price': '2',
         'gui_name': '2-贾克斯',
         'gui_checkbox_key': 'checkbox_贾克斯',
         'gui_combo_num_key': 'combo_num_贾克斯'},
 '莫甘娜': {'name': '莫甘娜',
         'jobs': ['耀光使'],
         'races': ['玉剑仙'],
         'price': '4',
         'gui_name': '4-莫甘娜',
         'gui_checkbox_key': 'checkbox_莫甘娜',
         'gui_combo_num_key': 'combo_num_莫甘娜'},
 '基兰': {'name': '基兰',
        'jobs': ['秘术师'],
        'races': ['腥红之月'],
        'price': '5',
        'gui_name': '5-基兰',
        'gui_checkbox_key': 'checkbox_基兰',
        'gui_combo_num_key': 'combo_num_基兰'},
 '伊芙琳': {'name': '伊芙琳',
         'jobs': ['夜影'],
         'races': ['腥红之月'],
         'price': '3',
         'gui_name': '3-伊芙琳',
         'gui_checkbox_key': 'checkbox_伊芙琳',
         'gui_combo_num_key': 'combo_num_伊芙琳'},
 '艾瑞莉娅': {'name': '艾瑞莉娅',
          'jobs': ['宗师'],
          'races': ['天神', '玉剑仙'],
          'price': '3',
          'gui_name': '3-艾瑞莉娅',
          'gui_checkbox_key': 'checkbox_艾瑞莉娅',
          'gui_combo_num_key': 'combo_num_艾瑞莉娅'},
 '迦娜': {'name': '迦娜',
        'jobs': ['秘术师'],
        'races': ['玉剑仙'],
        'price': '2',
        'gui_name': '2-迦娜',
        'gui_checkbox_key': 'checkbox_迦娜',
        'gui_combo_num_key': 'combo_num_迦娜'},
 '维迦': {'name': '维迦',
        'jobs': ['魔法师'],
        'races': ['永恒之森'],
        'price': '3',
        'gui_name': '3-维迦',
        'gui_checkbox_key': 'checkbox_维迦',
        'gui_combo_num_key': 'combo_num_维迦'},
 '卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['刺客'],
          'races': ['福星', '三国猛将'],
          'price': '3',
          'gui_name': '3-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '茂凯': {'name': '茂凯',
        'jobs': ['斗士'],
        'races': ['永恒之森'],
        'price': '1',
        'gui_name': '1-茂凯',
        'gui_checkbox_key': 'checkbox_茂凯',
        'gui_combo_num_key': 'combo_num_茂凯'},
 '嘉文四世': {'name': '嘉文四世',
          'jobs': ['神盾使'],
          'races': ['三国猛将'],
          'price': '2',
          'gui_name': '2-嘉文四世',
          'gui_checkbox_key': 'checkbox_嘉文四世',
          'gui_combo_num_key': 'combo_num_嘉文四世'},
 '伊莉丝': {'name': '伊莉丝',
         'jobs': ['神盾使'],
         'races': ['腥红之月'],
         'price': '1',
         'gui_name': '1-伊莉丝',
         'gui_checkbox_key': 'checkbox_伊莉丝',
         'gui_combo_num_key': 'combo_num_伊莉丝'},
 '孙悟空': {'name': '孙悟空',
         'jobs': ['重装战士'],
         'races': ['天神'],
         'price': '1',
         'gui_name': '1-孙悟空',
         'gui_checkbox_key': 'checkbox_孙悟空',
         'gui_combo_num_key': 'combo_num_孙悟空'},
 '李青': {'name': '李青',
        'jobs': ['决斗大师'],
        'races': ['天神'],
        'price': '5',
        'gui_name': '5-李青',
        'gui_checkbox_key': 'checkbox_李青',
        'gui_combo_num_key': 'combo_num_李青'},
 '薇恩': {'name': '薇恩',
        'jobs': ['神射手'],
        'races': ['灵魂莲华夜幽'],
        'price': '1',
        'gui_name': '1-薇恩',
        'gui_checkbox_key': 'checkbox_薇恩',
        'gui_combo_num_key': 'combo_num_薇恩'},
 '卡西奥佩娅': {'name': '卡西奥佩娅',
           'jobs': ['秘术师'],
           'races': ['灵魂莲华夜幽'],
           'price': '4',
           'gui_name': '4-卡西奥佩娅',
           'gui_checkbox_key': 'checkbox_卡西奥佩娅',
           'gui_combo_num_key': 'combo_num_卡西奥佩娅'},
 '奈德丽': {'name': '奈德丽',
         'jobs': ['神射手'],
         'races': ['三国猛将'],
         'price': '1',
         'gui_name': '1-奈德丽',
         'gui_checkbox_key': 'checkbox_奈德丽',
         'gui_combo_num_key': 'combo_num_奈德丽'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['耀光使'],
          'races': ['永恒之森'],
          'price': '5',
          'gui_name': '5-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '阿卡丽': {'name': '阿卡丽',
         'jobs': ['刺客'],
         'races': ['忍者'],
         'price': '3',
         'gui_name': '3-阿卡丽',
         'gui_checkbox_key': 'checkbox_阿卡丽',
         'gui_combo_num_key': 'combo_num_阿卡丽'},
 '凯南': {'name': '凯南',
        'jobs': ['神盾使'],
        'races': ['忍者'],
        'price': '3',
        'gui_name': '3-凯南',
        'gui_checkbox_key': 'checkbox_凯南',
        'gui_combo_num_key': 'combo_num_凯南'},
 '盖伦': {'name': '盖伦',
        'jobs': ['重装战士'],
        'races': ['三国猛将'],
        'price': '1',
        'gui_name': '1-盖伦',
        'gui_checkbox_key': 'checkbox_盖伦',
        'gui_combo_num_key': 'combo_num_盖伦'},
 '泰隆': {'name': '泰隆',
        'jobs': ['刺客'],
        'races': ['玉剑仙'],
        'price': '4',
        'gui_name': '4-泰隆',
        'gui_checkbox_key': 'checkbox_泰隆',
        'gui_combo_num_key': 'combo_num_泰隆'},
 '锐雯': {'name': '锐雯',
        'jobs': ['神盾使'],
        'races': ['灵魂莲华夜幽'],
        'price': '4',
        'gui_name': '4-锐雯',
        'gui_checkbox_key': 'checkbox_锐雯',
        'gui_combo_num_key': 'combo_num_锐雯'},
 '慎': {'name': '慎',
       'jobs': ['宗师', '秘术师'],
       'races': ['忍者'],
       'price': '4',
       'gui_name': '4-慎',
       'gui_checkbox_key': 'checkbox_慎',
       'gui_combo_num_key': 'combo_num_慎'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['耀光使'],
         'races': ['天神'],
         'price': '3',
         'gui_name': '3-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '阿狸': {'name': '阿狸',
        'jobs': ['魔法师'],
        'races': ['灵魂莲华明昼'],
        'price': '4',
        'gui_name': '4-阿狸',
        'gui_checkbox_key': 'checkbox_阿狸',
        'gui_combo_num_key': 'combo_num_阿狸'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['重装战士'],
         'races': ['福星'],
         'price': '4',
         'gui_name': '4-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '菲奥娜': {'name': '菲奥娜',
         'jobs': ['决斗大师'],
         'races': ['玉剑仙'],
         'price': '1',
         'gui_name': '1-菲奥娜',
         'gui_checkbox_key': 'checkbox_菲奥娜',
         'gui_combo_num_key': 'combo_num_菲奥娜'},
 '璐璐': {'name': '璐璐',
        'jobs': ['魔法师'],
        'races': ['永恒之森'],
        'price': '2',
        'gui_name': '2-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '赫卡里姆': {'name': '赫卡里姆',
          'jobs': ['重装战士'],
          'races': ['永恒之森'],
          'price': '2',
          'gui_name': '2-赫卡里姆',
          'gui_checkbox_key': 'checkbox_赫卡里姆',
          'gui_combo_num_key': 'combo_num_赫卡里姆'},
 '丽桑卓': {'name': '丽桑卓',
         'jobs': ['耀光使'],
         'races': ['月神'],
         'price': '1',
         'gui_name': '1-丽桑卓',
         'gui_checkbox_key': 'checkbox_丽桑卓',
         'gui_combo_num_key': 'combo_num_丽桑卓'},
 '黛安娜': {'name': '黛安娜',
         'jobs': ['刺客'],
         'races': ['月神'],
         'price': '1',
         'gui_name': '1-黛安娜',
         'gui_checkbox_key': 'checkbox_黛安娜',
         'gui_combo_num_key': 'combo_num_黛安娜'},
 '凯隐': {'name': '凯隐',
        'jobs': ['夜影'],
        'races': ['天煞'],
        'price': '5',
        'gui_name': '5-凯隐',
        'gui_checkbox_key': 'checkbox_凯隐',
        'gui_combo_num_key': 'combo_num_凯隐'},
 '亚索': {'name': '亚索',
        'jobs': ['决斗大师'],
        'races': ['浪人'],
        'price': '1',
        'gui_name': '1-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '烬': {'name': '烬',
       'jobs': ['神射手'],
       'races': ['腥红之月'],
       'price': '4',
       'gui_name': '4-烬',
       'gui_checkbox_key': 'checkbox_烬',
       'gui_combo_num_key': 'combo_num_烬'},
 '千珏': {'name': '千珏',
        'jobs': ['猎人'],
        'races': ['灵魂莲华明昼'],
        'price': '3',
        'gui_name': '3-千珏',
        'gui_checkbox_key': 'checkbox_千珏',
        'gui_combo_num_key': 'combo_num_千珏'},
 '金克丝': {'name': '金克丝',
         'jobs': ['神射手'],
         'races': ['福星'],
         'price': '3',
         'gui_name': '3-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '塔姆': {'name': '塔姆',
        'jobs': ['斗士'],
        'races': ['福星'],
        'price': '1',
        'gui_name': '1-塔姆',
        'gui_checkbox_key': 'checkbox_塔姆',
        'gui_combo_num_key': 'combo_num_塔姆'},
 '劫': {'name': '劫',
       'jobs': ['夜影'],
       'races': ['忍者'],
       'price': '2',
       'gui_name': '2-劫',
       'gui_checkbox_key': 'checkbox_劫',
       'gui_combo_num_key': 'combo_num_劫'},
 '蔚': {'name': '蔚',
       'jobs': ['斗士'],
       'races': ['三国猛将'],
       'price': '2',
       'gui_name': '2-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['重装战士'],
          'races': ['腥红之月'],
          'price': '4',
          'gui_name': '4-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '娜美': {'name': '娜美',
        'jobs': ['魔法师'],
        'races': ['玉剑仙'],
        'price': '1',
        'gui_name': '1-娜美',
        'gui_checkbox_key': 'checkbox_娜美',
        'gui_combo_num_key': 'combo_num_娜美'},
 '阿兹尔': {'name': '阿兹尔',
         'jobs': ['神盾使', '枭雄'],
         'races': ['三国猛将'],
         'price': '5',
         'gui_name': '5-阿兹尔',
         'gui_checkbox_key': 'checkbox_阿兹尔',
         'gui_combo_num_key': 'combo_num_阿兹尔'},
 '悠米': {'name': '悠米',
        'jobs': ['秘术师'],
        'races': ['灵魂莲华明昼'],
        'price': '3',
        'gui_name': '3-悠米',
        'gui_checkbox_key': 'checkbox_悠米',
        'gui_combo_num_key': 'combo_num_悠米'},
 '锤石': {'name': '锤石',
        'jobs': ['重装战士'],
        'races': ['灵魂莲华夜幽'],
        'price': '2',
        'gui_name': '2-锤石',
        'gui_checkbox_key': 'checkbox_锤石',
        'gui_combo_num_key': 'combo_num_锤石'},
 '卡莉丝塔': {'name': '卡莉丝塔',
          'jobs': ['决斗大师'],
          'races': ['腥红之月'],
          'price': '3',
          'gui_name': '3-卡莉丝塔',
          'gui_checkbox_key': 'checkbox_卡莉丝塔',
          'gui_combo_num_key': 'combo_num_卡莉丝塔'},
 '塞拉斯': {'name': '塞拉斯',
         'jobs': ['斗士'],
         'races': ['月神'],
         'price': '2',
         'gui_name': '2-塞拉斯',
         'gui_checkbox_key': 'checkbox_塞拉斯',
         'gui_combo_num_key': 'combo_num_塞拉斯'},
 '厄斐琉斯': {'name': '厄斐琉斯',
          'jobs': ['猎人'],
          'races': ['月神'],
          'price': '2',
          'gui_name': '2-厄斐琉斯',
          'gui_checkbox_key': 'checkbox_厄斐琉斯',
          'gui_combo_num_key': 'combo_num_厄斐琉斯'},
 '派克': {'name': '派克',
        'jobs': ['刺客'],
        'races': ['腥红之月'],
        'price': '2',
        'gui_name': '2-派克',
        'gui_checkbox_key': 'checkbox_派克',
        'gui_combo_num_key': 'combo_num_派克'},
 '永恩': {'name': '永恩',
        'jobs': ['宗师'],
        'races': ['浪人'],
        'price': '5',
        'gui_name': '5-永恩',
        'gui_checkbox_key': 'checkbox_永恩',
        'gui_combo_num_key': 'combo_num_永恩'},
 '瑟提': {'name': '瑟提',
        'jobs': ['斗士'],
        'races': ['霸王'],
        'price': '5',
        'gui_name': '5-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'},
 '莉莉娅': {'name': '莉莉娅',
         'jobs': ['魔法师'],
         'races': ['灵魂莲华夜幽'],
         'price': '5',
         'gui_name': '5-莉莉娅',
         'gui_checkbox_key': 'checkbox_莉莉娅',
         'gui_combo_num_key': 'combo_num_莉莉娅'}}
