"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's6-双城之战',
 '版本信息': '11.22',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '11.22-2021.S6',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.22-2021.S6/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.22-2021.S6/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.22-2021.S6/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.22-2021.S6/equip.js',
 'url_hex_data': None,
 '强化符文说明': 'S1-S5.5 尚未引入强化符文；S6 的腾讯历史强化符文文件未公开保留'}

    all_chess_name_str = '加里奥-崔斯特-厄加特-赛恩-崔丝塔娜-沃里克-厄运小姐-基兰-辛吉德-图奇-科加斯-萨科-蒙多医生-卡萨丁-迦娜-普朗克-塔里克-维迦-特朗德尔-斯维因-凯特琳-布里茨-卡特琳娜-奥莉安娜-黑默丁格-波比-伊泽瑞尔-阿卡丽-盖伦-蕾欧娜-玛尔扎哈-泰隆-克格莫-拉克丝-格雷福斯-维克托-菲奥娜-吉格斯-璐璐-德莱厄斯-杰斯-丽桑卓-奎因-婕拉-卡莎-萨勒芬妮-扎克-卡蜜尔-布隆-烬-金克丝-塔姆-艾克-蔚-悠米-莎弥拉-俄洛伊-薇古丝-永恩'

    all_race_name_str = '战斗学院-炼金科技-精密发条-执法官-变异战士-帝国-赏金猎人-极客-社交名流-辛迪加-约德尔人-姐妹-食神-猫猫-约德尔大王'

    all_job_name_str = '黑魔法师-刺客-格斗家-保镖-巨像-挑战者-白魔法师-发明家-圣盾使-学者-狙神-枪手-未来守护者'

    race_chess = {'战斗学院': ['卡特琳娜', '盖伦', '蕾欧娜', '拉克丝', '格雷福斯', '悠米', '永恩'],
 '炼金科技': ['厄加特', '沃里克', '辛吉德', '图奇', '蒙多医生', '维克托', '丽桑卓', '扎克'],
 '精密发条': ['基兰', '奥莉安娜', '卡蜜尔', '烬'],
 '执法官': ['凯特琳', '菲奥娜', '杰斯', '蔚'],
 '变异战士': ['科加斯', '蒙多医生', '卡萨丁', '玛尔扎哈', '克格莫', '卡莎'],
 '帝国': ['赛恩', '斯维因', '泰隆', '莎弥拉'],
 '赏金猎人': ['厄运小姐', '普朗克', '奎因', '塔姆', '俄洛伊'],
 '极客': ['迦娜', '特朗德尔', '布里茨', '伊泽瑞尔', '吉格斯', '金克丝', '艾克'],
 '社交名流': ['加里奥', '塔里克', '萨勒芬妮'],
 '辛迪加': ['崔斯特', '萨科', '阿卡丽', '德莱厄斯', '婕拉', '布隆'],
 '约德尔人': ['崔丝塔娜', '黑默丁格', '波比', '吉格斯', '璐璐', '薇古丝'],
 '姐妹': ['金克丝', '蔚'],
 '食神': ['塔姆'],
 '猫猫': ['悠米'],
 '约德尔大王': ['维迦']}

    job_chess = {'黑魔法师': ['崔斯特', '斯维因', '玛尔扎哈', '拉克丝', '维克托', '吉格斯', '薇古丝'],
 '刺客': ['图奇', '萨科', '卡特琳娜', '阿卡丽', '泰隆', '艾克'],
 '格斗家': ['科加斯', '蒙多医生', '特朗德尔', '扎克', '塔姆', '蔚', '俄洛伊'],
 '保镖': ['加里奥', '布里茨', '波比', '蕾欧娜', '德莱厄斯', '布隆'],
 '巨像': ['加里奥', '赛恩', '科加斯'],
 '挑战者': ['沃里克', '菲奥娜', '奎因', '卡莎', '卡蜜尔', '莎弥拉', '永恩'],
 '白魔法师': ['迦娜', '塔里克', '奥莉安娜', '璐璐'],
 '发明家': ['基兰', '辛吉德', '黑默丁格', '伊泽瑞尔', '杰斯', '萨勒芬妮'],
 '圣盾使': ['赛恩', '卡萨丁', '布里茨', '盖伦'],
 '学者': ['迦娜', '黑默丁格', '丽桑卓', '婕拉', '悠米'],
 '狙神': ['崔丝塔娜', '厄运小姐', '凯特琳', '克格莫', '烬'],
 '枪手': ['厄加特', '普朗克', '克格莫', '格雷福斯', '金克丝'],
 '未来守护者': ['杰斯']}

    price_chess = {'1': ['崔斯特', '辛吉德', '图奇', '卡萨丁', '凯特琳', '波比', '伊泽瑞尔', '盖伦', '格雷福斯', '吉格斯', '德莱厄斯', '卡蜜尔', '俄洛伊'],
 '2': ['崔丝塔娜', '沃里克', '基兰', '特朗德尔', '斯维因', '布里茨', '卡特琳娜', '泰隆', '克格莫', '璐璐', '奎因', '婕拉', '蔚'],
 '3': ['厄运小姐', '科加斯', '萨科', '普朗克', '塔里克', '黑默丁格', '蕾欧娜', '玛尔扎哈', '丽桑卓', '扎克', '艾克', '莎弥拉', '薇古丝'],
 '4': ['厄加特', '赛恩', '蒙多医生', '迦娜', '奥莉安娜', '拉克丝', '菲奥娜', '萨勒芬妮', '布隆', '烬', '永恩'],
 '5': ['加里奥', '维迦', '阿卡丽', '维克托', '杰斯', '卡莎', '金克丝', '塔姆', '悠米']}

    chess_name_info = {'加里奥': {'name': '加里奥',
         'jobs': ['保镖', '巨像'],
         'races': ['社交名流'],
         'price': '5',
         'gui_name': '5-加里奥',
         'gui_checkbox_key': 'checkbox_加里奥',
         'gui_combo_num_key': 'combo_num_加里奥'},
 '崔斯特': {'name': '崔斯特',
         'jobs': ['黑魔法师'],
         'races': ['辛迪加'],
         'price': '1',
         'gui_name': '1-崔斯特',
         'gui_checkbox_key': 'checkbox_崔斯特',
         'gui_combo_num_key': 'combo_num_崔斯特'},
 '厄加特': {'name': '厄加特',
         'jobs': ['枪手'],
         'races': ['炼金科技'],
         'price': '4',
         'gui_name': '4-厄加特',
         'gui_checkbox_key': 'checkbox_厄加特',
         'gui_combo_num_key': 'combo_num_厄加特'},
 '赛恩': {'name': '赛恩',
        'jobs': ['巨像', '圣盾使'],
        'races': ['帝国'],
        'price': '4',
        'gui_name': '4-赛恩',
        'gui_checkbox_key': 'checkbox_赛恩',
        'gui_combo_num_key': 'combo_num_赛恩'},
 '崔丝塔娜': {'name': '崔丝塔娜',
          'jobs': ['狙神'],
          'races': ['约德尔人'],
          'price': '2',
          'gui_name': '2-崔丝塔娜',
          'gui_checkbox_key': 'checkbox_崔丝塔娜',
          'gui_combo_num_key': 'combo_num_崔丝塔娜'},
 '沃里克': {'name': '沃里克',
         'jobs': ['挑战者'],
         'races': ['炼金科技'],
         'price': '2',
         'gui_name': '2-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '厄运小姐': {'name': '厄运小姐',
          'jobs': ['狙神'],
          'races': ['赏金猎人'],
          'price': '3',
          'gui_name': '3-厄运小姐',
          'gui_checkbox_key': 'checkbox_厄运小姐',
          'gui_combo_num_key': 'combo_num_厄运小姐'},
 '基兰': {'name': '基兰',
        'jobs': ['发明家'],
        'races': ['精密发条'],
        'price': '2',
        'gui_name': '2-基兰',
        'gui_checkbox_key': 'checkbox_基兰',
        'gui_combo_num_key': 'combo_num_基兰'},
 '辛吉德': {'name': '辛吉德',
         'jobs': ['发明家'],
         'races': ['炼金科技'],
         'price': '1',
         'gui_name': '1-辛吉德',
         'gui_checkbox_key': 'checkbox_辛吉德',
         'gui_combo_num_key': 'combo_num_辛吉德'},
 '图奇': {'name': '图奇',
        'jobs': ['刺客'],
        'races': ['炼金科技'],
        'price': '1',
        'gui_name': '1-图奇',
        'gui_checkbox_key': 'checkbox_图奇',
        'gui_combo_num_key': 'combo_num_图奇'},
 '科加斯': {'name': '科加斯',
         'jobs': ['格斗家', '巨像'],
         'races': ['变异战士'],
         'price': '3',
         'gui_name': '3-科加斯',
         'gui_checkbox_key': 'checkbox_科加斯',
         'gui_combo_num_key': 'combo_num_科加斯'},
 '萨科': {'name': '萨科',
        'jobs': ['刺客'],
        'races': ['辛迪加'],
        'price': '3',
        'gui_name': '3-萨科',
        'gui_checkbox_key': 'checkbox_萨科',
        'gui_combo_num_key': 'combo_num_萨科'},
 '蒙多医生': {'name': '蒙多医生',
          'jobs': ['格斗家'],
          'races': ['炼金科技', '变异战士'],
          'price': '4',
          'gui_name': '4-蒙多医生',
          'gui_checkbox_key': 'checkbox_蒙多医生',
          'gui_combo_num_key': 'combo_num_蒙多医生'},
 '卡萨丁': {'name': '卡萨丁',
         'jobs': ['圣盾使'],
         'races': ['变异战士'],
         'price': '1',
         'gui_name': '1-卡萨丁',
         'gui_checkbox_key': 'checkbox_卡萨丁',
         'gui_combo_num_key': 'combo_num_卡萨丁'},
 '迦娜': {'name': '迦娜',
        'jobs': ['白魔法师', '学者'],
        'races': ['极客'],
        'price': '4',
        'gui_name': '4-迦娜',
        'gui_checkbox_key': 'checkbox_迦娜',
        'gui_combo_num_key': 'combo_num_迦娜'},
 '普朗克': {'name': '普朗克',
         'jobs': ['枪手'],
         'races': ['赏金猎人'],
         'price': '3',
         'gui_name': '3-普朗克',
         'gui_checkbox_key': 'checkbox_普朗克',
         'gui_combo_num_key': 'combo_num_普朗克'},
 '塔里克': {'name': '塔里克',
         'jobs': ['白魔法师'],
         'races': ['社交名流'],
         'price': '3',
         'gui_name': '3-塔里克',
         'gui_checkbox_key': 'checkbox_塔里克',
         'gui_combo_num_key': 'combo_num_塔里克'},
 '维迦': {'name': '维迦',
        'jobs': [],
        'races': ['约德尔大王'],
        'price': '5',
        'gui_name': '5-维迦',
        'gui_checkbox_key': 'checkbox_维迦',
        'gui_combo_num_key': 'combo_num_维迦'},
 '特朗德尔': {'name': '特朗德尔',
          'jobs': ['格斗家'],
          'races': ['极客'],
          'price': '2',
          'gui_name': '2-特朗德尔',
          'gui_checkbox_key': 'checkbox_特朗德尔',
          'gui_combo_num_key': 'combo_num_特朗德尔'},
 '斯维因': {'name': '斯维因',
         'jobs': ['黑魔法师'],
         'races': ['帝国'],
         'price': '2',
         'gui_name': '2-斯维因',
         'gui_checkbox_key': 'checkbox_斯维因',
         'gui_combo_num_key': 'combo_num_斯维因'},
 '凯特琳': {'name': '凯特琳',
         'jobs': ['狙神'],
         'races': ['执法官'],
         'price': '1',
         'gui_name': '1-凯特琳',
         'gui_checkbox_key': 'checkbox_凯特琳',
         'gui_combo_num_key': 'combo_num_凯特琳'},
 '布里茨': {'name': '布里茨',
         'jobs': ['保镖', '圣盾使'],
         'races': ['极客'],
         'price': '2',
         'gui_name': '2-布里茨',
         'gui_checkbox_key': 'checkbox_布里茨',
         'gui_combo_num_key': 'combo_num_布里茨'},
 '卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['刺客'],
          'races': ['战斗学院'],
          'price': '2',
          'gui_name': '2-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '奥莉安娜': {'name': '奥莉安娜',
          'jobs': ['白魔法师'],
          'races': ['精密发条'],
          'price': '4',
          'gui_name': '4-奥莉安娜',
          'gui_checkbox_key': 'checkbox_奥莉安娜',
          'gui_combo_num_key': 'combo_num_奥莉安娜'},
 '黑默丁格': {'name': '黑默丁格',
          'jobs': ['发明家', '学者'],
          'races': ['约德尔人'],
          'price': '3',
          'gui_name': '3-黑默丁格',
          'gui_checkbox_key': 'checkbox_黑默丁格',
          'gui_combo_num_key': 'combo_num_黑默丁格'},
 '波比': {'name': '波比',
        'jobs': ['保镖'],
        'races': ['约德尔人'],
        'price': '1',
        'gui_name': '1-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '伊泽瑞尔': {'name': '伊泽瑞尔',
          'jobs': ['发明家'],
          'races': ['极客'],
          'price': '1',
          'gui_name': '1-伊泽瑞尔',
          'gui_checkbox_key': 'checkbox_伊泽瑞尔',
          'gui_combo_num_key': 'combo_num_伊泽瑞尔'},
 '阿卡丽': {'name': '阿卡丽',
         'jobs': ['刺客'],
         'races': ['辛迪加'],
         'price': '5',
         'gui_name': '5-阿卡丽',
         'gui_checkbox_key': 'checkbox_阿卡丽',
         'gui_combo_num_key': 'combo_num_阿卡丽'},
 '盖伦': {'name': '盖伦',
        'jobs': ['圣盾使'],
        'races': ['战斗学院'],
        'price': '1',
        'gui_name': '1-盖伦',
        'gui_checkbox_key': 'checkbox_盖伦',
        'gui_combo_num_key': 'combo_num_盖伦'},
 '蕾欧娜': {'name': '蕾欧娜',
         'jobs': ['保镖'],
         'races': ['战斗学院'],
         'price': '3',
         'gui_name': '3-蕾欧娜',
         'gui_checkbox_key': 'checkbox_蕾欧娜',
         'gui_combo_num_key': 'combo_num_蕾欧娜'},
 '玛尔扎哈': {'name': '玛尔扎哈',
          'jobs': ['黑魔法师'],
          'races': ['变异战士'],
          'price': '3',
          'gui_name': '3-玛尔扎哈',
          'gui_checkbox_key': 'checkbox_玛尔扎哈',
          'gui_combo_num_key': 'combo_num_玛尔扎哈'},
 '泰隆': {'name': '泰隆',
        'jobs': ['刺客'],
        'races': ['帝国'],
        'price': '2',
        'gui_name': '2-泰隆',
        'gui_checkbox_key': 'checkbox_泰隆',
        'gui_combo_num_key': 'combo_num_泰隆'},
 '克格莫': {'name': '克格莫',
         'jobs': ['狙神', '枪手'],
         'races': ['变异战士'],
         'price': '2',
         'gui_name': '2-克格莫',
         'gui_checkbox_key': 'checkbox_克格莫',
         'gui_combo_num_key': 'combo_num_克格莫'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['黑魔法师'],
         'races': ['战斗学院'],
         'price': '4',
         'gui_name': '4-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '格雷福斯': {'name': '格雷福斯',
          'jobs': ['枪手'],
          'races': ['战斗学院'],
          'price': '1',
          'gui_name': '1-格雷福斯',
          'gui_checkbox_key': 'checkbox_格雷福斯',
          'gui_combo_num_key': 'combo_num_格雷福斯'},
 '维克托': {'name': '维克托',
         'jobs': ['黑魔法师'],
         'races': ['炼金科技'],
         'price': '5',
         'gui_name': '5-维克托',
         'gui_checkbox_key': 'checkbox_维克托',
         'gui_combo_num_key': 'combo_num_维克托'},
 '菲奥娜': {'name': '菲奥娜',
         'jobs': ['挑战者'],
         'races': ['执法官'],
         'price': '4',
         'gui_name': '4-菲奥娜',
         'gui_checkbox_key': 'checkbox_菲奥娜',
         'gui_combo_num_key': 'combo_num_菲奥娜'},
 '吉格斯': {'name': '吉格斯',
         'jobs': ['黑魔法师'],
         'races': ['极客', '约德尔人'],
         'price': '1',
         'gui_name': '1-吉格斯',
         'gui_checkbox_key': 'checkbox_吉格斯',
         'gui_combo_num_key': 'combo_num_吉格斯'},
 '璐璐': {'name': '璐璐',
        'jobs': ['白魔法师'],
        'races': ['约德尔人'],
        'price': '2',
        'gui_name': '2-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['保镖'],
          'races': ['辛迪加'],
          'price': '1',
          'gui_name': '1-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '杰斯': {'name': '杰斯',
        'jobs': ['发明家', '未来守护者'],
        'races': ['执法官'],
        'price': '5',
        'gui_name': '5-杰斯',
        'gui_checkbox_key': 'checkbox_杰斯',
        'gui_combo_num_key': 'combo_num_杰斯'},
 '丽桑卓': {'name': '丽桑卓',
         'jobs': ['学者'],
         'races': ['炼金科技'],
         'price': '3',
         'gui_name': '3-丽桑卓',
         'gui_checkbox_key': 'checkbox_丽桑卓',
         'gui_combo_num_key': 'combo_num_丽桑卓'},
 '奎因': {'name': '奎因',
        'jobs': ['挑战者'],
        'races': ['赏金猎人'],
        'price': '2',
        'gui_name': '2-奎因',
        'gui_checkbox_key': 'checkbox_奎因',
        'gui_combo_num_key': 'combo_num_奎因'},
 '婕拉': {'name': '婕拉',
        'jobs': ['学者'],
        'races': ['辛迪加'],
        'price': '2',
        'gui_name': '2-婕拉',
        'gui_checkbox_key': 'checkbox_婕拉',
        'gui_combo_num_key': 'combo_num_婕拉'},
 '卡莎': {'name': '卡莎',
        'jobs': ['挑战者'],
        'races': ['变异战士'],
        'price': '5',
        'gui_name': '5-卡莎',
        'gui_checkbox_key': 'checkbox_卡莎',
        'gui_combo_num_key': 'combo_num_卡莎'},
 '萨勒芬妮': {'name': '萨勒芬妮',
          'jobs': ['发明家'],
          'races': ['社交名流'],
          'price': '4',
          'gui_name': '4-萨勒芬妮',
          'gui_checkbox_key': 'checkbox_萨勒芬妮',
          'gui_combo_num_key': 'combo_num_萨勒芬妮'},
 '扎克': {'name': '扎克',
        'jobs': ['格斗家'],
        'races': ['炼金科技'],
        'price': '3',
        'gui_name': '3-扎克',
        'gui_checkbox_key': 'checkbox_扎克',
        'gui_combo_num_key': 'combo_num_扎克'},
 '卡蜜尔': {'name': '卡蜜尔',
         'jobs': ['挑战者'],
         'races': ['精密发条'],
         'price': '1',
         'gui_name': '1-卡蜜尔',
         'gui_checkbox_key': 'checkbox_卡蜜尔',
         'gui_combo_num_key': 'combo_num_卡蜜尔'},
 '布隆': {'name': '布隆',
        'jobs': ['保镖'],
        'races': ['辛迪加'],
        'price': '4',
        'gui_name': '4-布隆',
        'gui_checkbox_key': 'checkbox_布隆',
        'gui_combo_num_key': 'combo_num_布隆'},
 '烬': {'name': '烬',
       'jobs': ['狙神'],
       'races': ['精密发条'],
       'price': '4',
       'gui_name': '4-烬',
       'gui_checkbox_key': 'checkbox_烬',
       'gui_combo_num_key': 'combo_num_烬'},
 '金克丝': {'name': '金克丝',
         'jobs': ['枪手'],
         'races': ['极客', '姐妹'],
         'price': '5',
         'gui_name': '5-金克丝',
         'gui_checkbox_key': 'checkbox_金克丝',
         'gui_combo_num_key': 'combo_num_金克丝'},
 '塔姆': {'name': '塔姆',
        'jobs': ['格斗家'],
        'races': ['赏金猎人', '食神'],
        'price': '5',
        'gui_name': '5-塔姆',
        'gui_checkbox_key': 'checkbox_塔姆',
        'gui_combo_num_key': 'combo_num_塔姆'},
 '艾克': {'name': '艾克',
        'jobs': ['刺客'],
        'races': ['极客'],
        'price': '3',
        'gui_name': '3-艾克',
        'gui_checkbox_key': 'checkbox_艾克',
        'gui_combo_num_key': 'combo_num_艾克'},
 '蔚': {'name': '蔚',
       'jobs': ['格斗家'],
       'races': ['执法官', '姐妹'],
       'price': '2',
       'gui_name': '2-蔚',
       'gui_checkbox_key': 'checkbox_蔚',
       'gui_combo_num_key': 'combo_num_蔚'},
 '悠米': {'name': '悠米',
        'jobs': ['学者'],
        'races': ['战斗学院', '猫猫'],
        'price': '5',
        'gui_name': '5-悠米',
        'gui_checkbox_key': 'checkbox_悠米',
        'gui_combo_num_key': 'combo_num_悠米'},
 '莎弥拉': {'name': '莎弥拉',
         'jobs': ['挑战者'],
         'races': ['帝国'],
         'price': '3',
         'gui_name': '3-莎弥拉',
         'gui_checkbox_key': 'checkbox_莎弥拉',
         'gui_combo_num_key': 'combo_num_莎弥拉'},
 '俄洛伊': {'name': '俄洛伊',
         'jobs': ['格斗家'],
         'races': ['赏金猎人'],
         'price': '1',
         'gui_name': '1-俄洛伊',
         'gui_checkbox_key': 'checkbox_俄洛伊',
         'gui_combo_num_key': 'combo_num_俄洛伊'},
 '薇古丝': {'name': '薇古丝',
         'jobs': ['黑魔法师'],
         'races': ['约德尔人'],
         'price': '3',
         'gui_name': '3-薇古丝',
         'gui_checkbox_key': 'checkbox_薇古丝',
         'gui_combo_num_key': 'combo_num_薇古丝'},
 '永恩': {'name': '永恩',
        'jobs': ['挑战者'],
        'races': ['战斗学院'],
        'price': '4',
        'gui_name': '4-永恩',
        'gui_checkbox_key': 'checkbox_永恩',
        'gui_combo_num_key': 'combo_num_永恩'}}
