"""Generated, immutable convenience view of this season archive."""

class TFTData:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    version_config = {'赛季名称': 's5-光明与黑暗',
 '版本信息': '11.9',
 '爬取日期': '2026-09-17',
 '归档说明': '从腾讯官方历史版本接口恢复',
 '数据路径': '11.9-2021.S5',
 'url_chess_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.9-2021.S5/chess.js',
 'url_race_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.9-2021.S5/race.js',
 'url_job_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.9-2021.S5/job.js',
 'url_equip_data': 'https://game.gtimg.cn/images/lol/act/img/tft/js/11.9-2021.S5/equip.js',
 'url_hex_data': None,
 '强化符文说明': '该赛季尚未引入强化符文系统'}

    all_chess_name_str = '乐芙兰-弗拉基米尔-凯尔-瑞兹-索拉卡-提莫-沃里克-努努和威朗普-艾希-贾克斯-莫甘娜-卡尔玛-塔里克-特朗德尔-卡特琳娜-魔腾-莫德凯撒-布兰德-李青-薇恩-黑默丁格-波比-奈德丽-乌迪尔-古拉加斯-潘森-凯南-盖伦-蕾欧娜-锐雯-拉克丝-沃利贝尔-韦鲁斯-诺提勒斯-维克托-瑟庄妮-吉格斯-璐璐-德莱文-赫卡里姆-卡兹克-德莱厄斯-丽桑卓-黛安娜-辛德拉-婕拉-亚索-维克兹-千珏-佛耶戈-克烈-亚托克斯-锤石-艾翁-卡莉丝塔-厄斐琉斯-芮尔-瑟提'

    all_race_name_str = '破败军团-黑夜使者-魔女-小恶魔-屠龙勇士-丧尸-圣光卫士-黎明使者-神佑之森-龙族-铁甲卫士-永猎双子-复生亡魂'

    all_job_name_str = '刺客-游侠-斗士-征服者-复苏者-神谕者-骑士-法师-神盾战士-秘术师-重骑兵-大魔王-神王-驯龙大师'

    race_chess = {'破败军团': ['瑞兹', '沃里克', '卡特琳娜', '薇恩', '维克托', '德莱文', '赫卡里姆', '佛耶戈', '锤石'],
 '黑夜使者': ['弗拉基米尔', '莫甘娜', '李青', '瑟庄妮', '德莱厄斯', '黛安娜', '亚索', '厄斐琉斯'],
 '魔女': ['乐芙兰', '莫甘娜', '丽桑卓'],
 '小恶魔': ['提莫', '波比', '凯南', '吉格斯', '璐璐', '克烈'],
 '屠龙勇士': ['特朗德尔', '莫德凯撒', '潘森', '黛安娜'],
 '丧尸': ['瑞兹', '努努和威朗普', '布兰德', '卡莉丝塔'],
 '圣光卫士': ['凯尔', '蕾欧娜', '拉克丝', '韦鲁斯', '辛德拉', '维克兹', '亚托克斯', '芮尔'],
 '黎明使者': ['索拉卡', '卡尔玛', '奈德丽', '古拉加斯', '盖伦', '锐雯', '卡兹克'],
 '神佑之森': ['凯尔', '艾希', '塔里克'],
 '龙族': ['艾希', '黑默丁格', '乌迪尔', '婕拉', '瑟提'],
 '铁甲卫士': ['贾克斯', '诺提勒斯', '芮尔'],
 '永猎双子': ['千珏'],
 '复生亡魂': ['魔腾', '沃利贝尔', '艾翁']}

    job_chess = {'刺客': ['乐芙兰', '卡特琳娜', '魔腾', '卡兹克', '黛安娜', '佛耶戈'],
 '游侠': ['艾希', '薇恩', '韦鲁斯', '千珏', '厄斐琉斯'],
 '斗士': ['沃里克', '努努和威朗普', '古拉加斯', '沃利贝尔', '瑟提'],
 '征服者': ['凯尔', '莫德凯撒', '锐雯', '德莱文', '亚索', '亚托克斯', '卡莉丝塔'],
 '复苏者': ['弗拉基米尔', '索拉卡', '黑默丁格', '丽桑卓', '艾翁'],
 '神谕者': ['提莫', '卡尔玛', '辛德拉', '艾翁'],
 '骑士': ['塔里克', '波比', '盖伦', '蕾欧娜', '诺提勒斯', '德莱厄斯', '锤石'],
 '法师': ['布兰德', '维克托', '吉格斯', '婕拉', '维克兹'],
 '神盾战士': ['贾克斯', '特朗德尔', '李青', '奈德丽', '乌迪尔', '潘森', '凯南', '佛耶戈'],
 '秘术师': ['瑞兹', '莫甘娜', '拉克丝', '璐璐', '千珏'],
 '重骑兵': ['瑟庄妮', '赫卡里姆', '克烈', '芮尔'],
 '大魔王': ['提莫'],
 '神王': ['盖伦', '德莱厄斯'],
 '驯龙大师': ['黑默丁格']}

    price_chess = {'1': ['弗拉基米尔', '沃里克', '薇恩', '波比', '乌迪尔', '古拉加斯', '蕾欧娜', '吉格斯', '卡兹克', '丽桑卓', '克烈', '亚托克斯', '卡莉丝塔'],
 '2': ['乐芙兰', '索拉卡', '特朗德尔', '布兰德', '凯南', '韦鲁斯', '诺提勒斯', '维克托', '瑟庄妮', '赫卡里姆', '辛德拉', '锤石', '瑟提'],
 '3': ['努努和威朗普', '艾希', '莫甘娜', '卡特琳娜', '魔腾', '李青', '奈德丽', '潘森', '锐雯', '拉克丝', '璐璐', '婕拉', '亚索'],
 '4': ['瑞兹', '贾克斯', '卡尔玛', '塔里克', '莫德凯撒', '德莱文', '黛安娜', '维克兹', '艾翁', '厄斐琉斯', '芮尔'],
 '5': ['凯尔', '黑默丁格', '盖伦', '沃利贝尔', '德莱厄斯', '千珏', '佛耶戈'],
 '6': ['提莫']}

    chess_name_info = {'乐芙兰': {'name': '乐芙兰',
         'jobs': ['刺客'],
         'races': ['魔女'],
         'price': '2',
         'gui_name': '2-乐芙兰',
         'gui_checkbox_key': 'checkbox_乐芙兰',
         'gui_combo_num_key': 'combo_num_乐芙兰'},
 '弗拉基米尔': {'name': '弗拉基米尔',
           'jobs': ['复苏者'],
           'races': ['黑夜使者'],
           'price': '1',
           'gui_name': '1-弗拉基米尔',
           'gui_checkbox_key': 'checkbox_弗拉基米尔',
           'gui_combo_num_key': 'combo_num_弗拉基米尔'},
 '凯尔': {'name': '凯尔',
        'jobs': ['征服者'],
        'races': ['圣光卫士', '神佑之森'],
        'price': '5',
        'gui_name': '5-凯尔',
        'gui_checkbox_key': 'checkbox_凯尔',
        'gui_combo_num_key': 'combo_num_凯尔'},
 '瑞兹': {'name': '瑞兹',
        'jobs': ['秘术师'],
        'races': ['破败军团', '丧尸'],
        'price': '4',
        'gui_name': '4-瑞兹',
        'gui_checkbox_key': 'checkbox_瑞兹',
        'gui_combo_num_key': 'combo_num_瑞兹'},
 '索拉卡': {'name': '索拉卡',
         'jobs': ['复苏者'],
         'races': ['黎明使者'],
         'price': '2',
         'gui_name': '2-索拉卡',
         'gui_checkbox_key': 'checkbox_索拉卡',
         'gui_combo_num_key': 'combo_num_索拉卡'},
 '提莫': {'name': '提莫',
        'jobs': ['神谕者', '大魔王'],
        'races': ['小恶魔'],
        'price': '6',
        'gui_name': '6-提莫',
        'gui_checkbox_key': 'checkbox_提莫',
        'gui_combo_num_key': 'combo_num_提莫'},
 '沃里克': {'name': '沃里克',
         'jobs': ['斗士'],
         'races': ['破败军团'],
         'price': '1',
         'gui_name': '1-沃里克',
         'gui_checkbox_key': 'checkbox_沃里克',
         'gui_combo_num_key': 'combo_num_沃里克'},
 '努努和威朗普': {'name': '努努和威朗普',
            'jobs': ['斗士'],
            'races': ['丧尸'],
            'price': '3',
            'gui_name': '3-努努和威朗普',
            'gui_checkbox_key': 'checkbox_努努和威朗普',
            'gui_combo_num_key': 'combo_num_努努和威朗普'},
 '艾希': {'name': '艾希',
        'jobs': ['游侠'],
        'races': ['神佑之森', '龙族'],
        'price': '3',
        'gui_name': '3-艾希',
        'gui_checkbox_key': 'checkbox_艾希',
        'gui_combo_num_key': 'combo_num_艾希'},
 '贾克斯': {'name': '贾克斯',
         'jobs': ['神盾战士'],
         'races': ['铁甲卫士'],
         'price': '4',
         'gui_name': '4-贾克斯',
         'gui_checkbox_key': 'checkbox_贾克斯',
         'gui_combo_num_key': 'combo_num_贾克斯'},
 '莫甘娜': {'name': '莫甘娜',
         'jobs': ['秘术师'],
         'races': ['黑夜使者', '魔女'],
         'price': '3',
         'gui_name': '3-莫甘娜',
         'gui_checkbox_key': 'checkbox_莫甘娜',
         'gui_combo_num_key': 'combo_num_莫甘娜'},
 '卡尔玛': {'name': '卡尔玛',
         'jobs': ['神谕者'],
         'races': ['黎明使者'],
         'price': '4',
         'gui_name': '4-卡尔玛',
         'gui_checkbox_key': 'checkbox_卡尔玛',
         'gui_combo_num_key': 'combo_num_卡尔玛'},
 '塔里克': {'name': '塔里克',
         'jobs': ['骑士'],
         'races': ['神佑之森'],
         'price': '4',
         'gui_name': '4-塔里克',
         'gui_checkbox_key': 'checkbox_塔里克',
         'gui_combo_num_key': 'combo_num_塔里克'},
 '特朗德尔': {'name': '特朗德尔',
          'jobs': ['神盾战士'],
          'races': ['屠龙勇士'],
          'price': '2',
          'gui_name': '2-特朗德尔',
          'gui_checkbox_key': 'checkbox_特朗德尔',
          'gui_combo_num_key': 'combo_num_特朗德尔'},
 '卡特琳娜': {'name': '卡特琳娜',
          'jobs': ['刺客'],
          'races': ['破败军团'],
          'price': '3',
          'gui_name': '3-卡特琳娜',
          'gui_checkbox_key': 'checkbox_卡特琳娜',
          'gui_combo_num_key': 'combo_num_卡特琳娜'},
 '魔腾': {'name': '魔腾',
        'jobs': ['刺客'],
        'races': ['复生亡魂'],
        'price': '3',
        'gui_name': '3-魔腾',
        'gui_checkbox_key': 'checkbox_魔腾',
        'gui_combo_num_key': 'combo_num_魔腾'},
 '莫德凯撒': {'name': '莫德凯撒',
          'jobs': ['征服者'],
          'races': ['屠龙勇士'],
          'price': '4',
          'gui_name': '4-莫德凯撒',
          'gui_checkbox_key': 'checkbox_莫德凯撒',
          'gui_combo_num_key': 'combo_num_莫德凯撒'},
 '布兰德': {'name': '布兰德',
         'jobs': ['法师'],
         'races': ['丧尸'],
         'price': '2',
         'gui_name': '2-布兰德',
         'gui_checkbox_key': 'checkbox_布兰德',
         'gui_combo_num_key': 'combo_num_布兰德'},
 '李青': {'name': '李青',
        'jobs': ['神盾战士'],
        'races': ['黑夜使者'],
        'price': '3',
        'gui_name': '3-李青',
        'gui_checkbox_key': 'checkbox_李青',
        'gui_combo_num_key': 'combo_num_李青'},
 '薇恩': {'name': '薇恩',
        'jobs': ['游侠'],
        'races': ['破败军团'],
        'price': '1',
        'gui_name': '1-薇恩',
        'gui_checkbox_key': 'checkbox_薇恩',
        'gui_combo_num_key': 'combo_num_薇恩'},
 '黑默丁格': {'name': '黑默丁格',
          'jobs': ['复苏者', '驯龙大师'],
          'races': ['龙族'],
          'price': '5',
          'gui_name': '5-黑默丁格',
          'gui_checkbox_key': 'checkbox_黑默丁格',
          'gui_combo_num_key': 'combo_num_黑默丁格'},
 '波比': {'name': '波比',
        'jobs': ['骑士'],
        'races': ['小恶魔'],
        'price': '1',
        'gui_name': '1-波比',
        'gui_checkbox_key': 'checkbox_波比',
        'gui_combo_num_key': 'combo_num_波比'},
 '奈德丽': {'name': '奈德丽',
         'jobs': ['神盾战士'],
         'races': ['黎明使者'],
         'price': '3',
         'gui_name': '3-奈德丽',
         'gui_checkbox_key': 'checkbox_奈德丽',
         'gui_combo_num_key': 'combo_num_奈德丽'},
 '乌迪尔': {'name': '乌迪尔',
         'jobs': ['神盾战士'],
         'races': ['龙族'],
         'price': '1',
         'gui_name': '1-乌迪尔',
         'gui_checkbox_key': 'checkbox_乌迪尔',
         'gui_combo_num_key': 'combo_num_乌迪尔'},
 '古拉加斯': {'name': '古拉加斯',
          'jobs': ['斗士'],
          'races': ['黎明使者'],
          'price': '1',
          'gui_name': '1-古拉加斯',
          'gui_checkbox_key': 'checkbox_古拉加斯',
          'gui_combo_num_key': 'combo_num_古拉加斯'},
 '潘森': {'name': '潘森',
        'jobs': ['神盾战士'],
        'races': ['屠龙勇士'],
        'price': '3',
        'gui_name': '3-潘森',
        'gui_checkbox_key': 'checkbox_潘森',
        'gui_combo_num_key': 'combo_num_潘森'},
 '凯南': {'name': '凯南',
        'jobs': ['神盾战士'],
        'races': ['小恶魔'],
        'price': '2',
        'gui_name': '2-凯南',
        'gui_checkbox_key': 'checkbox_凯南',
        'gui_combo_num_key': 'combo_num_凯南'},
 '盖伦': {'name': '盖伦',
        'jobs': ['骑士', '神王'],
        'races': ['黎明使者'],
        'price': '5',
        'gui_name': '5-盖伦',
        'gui_checkbox_key': 'checkbox_盖伦',
        'gui_combo_num_key': 'combo_num_盖伦'},
 '蕾欧娜': {'name': '蕾欧娜',
         'jobs': ['骑士'],
         'races': ['圣光卫士'],
         'price': '1',
         'gui_name': '1-蕾欧娜',
         'gui_checkbox_key': 'checkbox_蕾欧娜',
         'gui_combo_num_key': 'combo_num_蕾欧娜'},
 '锐雯': {'name': '锐雯',
        'jobs': ['征服者'],
        'races': ['黎明使者'],
        'price': '3',
        'gui_name': '3-锐雯',
        'gui_checkbox_key': 'checkbox_锐雯',
        'gui_combo_num_key': 'combo_num_锐雯'},
 '拉克丝': {'name': '拉克丝',
         'jobs': ['秘术师'],
         'races': ['圣光卫士'],
         'price': '3',
         'gui_name': '3-拉克丝',
         'gui_checkbox_key': 'checkbox_拉克丝',
         'gui_combo_num_key': 'combo_num_拉克丝'},
 '沃利贝尔': {'name': '沃利贝尔',
          'jobs': ['斗士'],
          'races': ['复生亡魂'],
          'price': '5',
          'gui_name': '5-沃利贝尔',
          'gui_checkbox_key': 'checkbox_沃利贝尔',
          'gui_combo_num_key': 'combo_num_沃利贝尔'},
 '韦鲁斯': {'name': '韦鲁斯',
         'jobs': ['游侠'],
         'races': ['圣光卫士'],
         'price': '2',
         'gui_name': '2-韦鲁斯',
         'gui_checkbox_key': 'checkbox_韦鲁斯',
         'gui_combo_num_key': 'combo_num_韦鲁斯'},
 '诺提勒斯': {'name': '诺提勒斯',
          'jobs': ['骑士'],
          'races': ['铁甲卫士'],
          'price': '2',
          'gui_name': '2-诺提勒斯',
          'gui_checkbox_key': 'checkbox_诺提勒斯',
          'gui_combo_num_key': 'combo_num_诺提勒斯'},
 '维克托': {'name': '维克托',
         'jobs': ['法师'],
         'races': ['破败军团'],
         'price': '2',
         'gui_name': '2-维克托',
         'gui_checkbox_key': 'checkbox_维克托',
         'gui_combo_num_key': 'combo_num_维克托'},
 '瑟庄妮': {'name': '瑟庄妮',
         'jobs': ['重骑兵'],
         'races': ['黑夜使者'],
         'price': '2',
         'gui_name': '2-瑟庄妮',
         'gui_checkbox_key': 'checkbox_瑟庄妮',
         'gui_combo_num_key': 'combo_num_瑟庄妮'},
 '吉格斯': {'name': '吉格斯',
         'jobs': ['法师'],
         'races': ['小恶魔'],
         'price': '1',
         'gui_name': '1-吉格斯',
         'gui_checkbox_key': 'checkbox_吉格斯',
         'gui_combo_num_key': 'combo_num_吉格斯'},
 '璐璐': {'name': '璐璐',
        'jobs': ['秘术师'],
        'races': ['小恶魔'],
        'price': '3',
        'gui_name': '3-璐璐',
        'gui_checkbox_key': 'checkbox_璐璐',
        'gui_combo_num_key': 'combo_num_璐璐'},
 '德莱文': {'name': '德莱文',
         'jobs': ['征服者'],
         'races': ['破败军团'],
         'price': '4',
         'gui_name': '4-德莱文',
         'gui_checkbox_key': 'checkbox_德莱文',
         'gui_combo_num_key': 'combo_num_德莱文'},
 '赫卡里姆': {'name': '赫卡里姆',
          'jobs': ['重骑兵'],
          'races': ['破败军团'],
          'price': '2',
          'gui_name': '2-赫卡里姆',
          'gui_checkbox_key': 'checkbox_赫卡里姆',
          'gui_combo_num_key': 'combo_num_赫卡里姆'},
 '卡兹克': {'name': '卡兹克',
         'jobs': ['刺客'],
         'races': ['黎明使者'],
         'price': '1',
         'gui_name': '1-卡兹克',
         'gui_checkbox_key': 'checkbox_卡兹克',
         'gui_combo_num_key': 'combo_num_卡兹克'},
 '德莱厄斯': {'name': '德莱厄斯',
          'jobs': ['骑士', '神王'],
          'races': ['黑夜使者'],
          'price': '5',
          'gui_name': '5-德莱厄斯',
          'gui_checkbox_key': 'checkbox_德莱厄斯',
          'gui_combo_num_key': 'combo_num_德莱厄斯'},
 '丽桑卓': {'name': '丽桑卓',
         'jobs': ['复苏者'],
         'races': ['魔女'],
         'price': '1',
         'gui_name': '1-丽桑卓',
         'gui_checkbox_key': 'checkbox_丽桑卓',
         'gui_combo_num_key': 'combo_num_丽桑卓'},
 '黛安娜': {'name': '黛安娜',
         'jobs': ['刺客'],
         'races': ['黑夜使者', '屠龙勇士'],
         'price': '4',
         'gui_name': '4-黛安娜',
         'gui_checkbox_key': 'checkbox_黛安娜',
         'gui_combo_num_key': 'combo_num_黛安娜'},
 '辛德拉': {'name': '辛德拉',
         'jobs': ['神谕者'],
         'races': ['圣光卫士'],
         'price': '2',
         'gui_name': '2-辛德拉',
         'gui_checkbox_key': 'checkbox_辛德拉',
         'gui_combo_num_key': 'combo_num_辛德拉'},
 '婕拉': {'name': '婕拉',
        'jobs': ['法师'],
        'races': ['龙族'],
        'price': '3',
        'gui_name': '3-婕拉',
        'gui_checkbox_key': 'checkbox_婕拉',
        'gui_combo_num_key': 'combo_num_婕拉'},
 '亚索': {'name': '亚索',
        'jobs': ['征服者'],
        'races': ['黑夜使者'],
        'price': '3',
        'gui_name': '3-亚索',
        'gui_checkbox_key': 'checkbox_亚索',
        'gui_combo_num_key': 'combo_num_亚索'},
 '维克兹': {'name': '维克兹',
         'jobs': ['法师'],
         'races': ['圣光卫士'],
         'price': '4',
         'gui_name': '4-维克兹',
         'gui_checkbox_key': 'checkbox_维克兹',
         'gui_combo_num_key': 'combo_num_维克兹'},
 '千珏': {'name': '千珏',
        'jobs': ['游侠', '秘术师'],
        'races': ['永猎双子'],
        'price': '5',
        'gui_name': '5-千珏',
        'gui_checkbox_key': 'checkbox_千珏',
        'gui_combo_num_key': 'combo_num_千珏'},
 '佛耶戈': {'name': '佛耶戈',
         'jobs': ['刺客', '神盾战士'],
         'races': ['破败军团'],
         'price': '5',
         'gui_name': '5-佛耶戈',
         'gui_checkbox_key': 'checkbox_佛耶戈',
         'gui_combo_num_key': 'combo_num_佛耶戈'},
 '克烈': {'name': '克烈',
        'jobs': ['重骑兵'],
        'races': ['小恶魔'],
        'price': '1',
        'gui_name': '1-克烈',
        'gui_checkbox_key': 'checkbox_克烈',
        'gui_combo_num_key': 'combo_num_克烈'},
 '亚托克斯': {'name': '亚托克斯',
          'jobs': ['征服者'],
          'races': ['圣光卫士'],
          'price': '1',
          'gui_name': '1-亚托克斯',
          'gui_checkbox_key': 'checkbox_亚托克斯',
          'gui_combo_num_key': 'combo_num_亚托克斯'},
 '锤石': {'name': '锤石',
        'jobs': ['骑士'],
        'races': ['破败军团'],
        'price': '2',
        'gui_name': '2-锤石',
        'gui_checkbox_key': 'checkbox_锤石',
        'gui_combo_num_key': 'combo_num_锤石'},
 '艾翁': {'name': '艾翁',
        'jobs': ['复苏者', '神谕者'],
        'races': ['复生亡魂'],
        'price': '4',
        'gui_name': '4-艾翁',
        'gui_checkbox_key': 'checkbox_艾翁',
        'gui_combo_num_key': 'combo_num_艾翁'},
 '卡莉丝塔': {'name': '卡莉丝塔',
          'jobs': ['征服者'],
          'races': ['丧尸'],
          'price': '1',
          'gui_name': '1-卡莉丝塔',
          'gui_checkbox_key': 'checkbox_卡莉丝塔',
          'gui_combo_num_key': 'combo_num_卡莉丝塔'},
 '厄斐琉斯': {'name': '厄斐琉斯',
          'jobs': ['游侠'],
          'races': ['黑夜使者'],
          'price': '4',
          'gui_name': '4-厄斐琉斯',
          'gui_checkbox_key': 'checkbox_厄斐琉斯',
          'gui_combo_num_key': 'combo_num_厄斐琉斯'},
 '芮尔': {'name': '芮尔',
        'jobs': ['重骑兵'],
        'races': ['圣光卫士', '铁甲卫士'],
        'price': '4',
        'gui_name': '4-芮尔',
        'gui_checkbox_key': 'checkbox_芮尔',
        'gui_combo_num_key': 'combo_num_芮尔'},
 '瑟提': {'name': '瑟提',
        'jobs': ['斗士'],
        'races': ['龙族'],
        'price': '2',
        'gui_name': '2-瑟提',
        'gui_checkbox_key': 'checkbox_瑟提',
        'gui_combo_num_key': 'combo_num_瑟提'}}
